// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: parking_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GosNumber     string                 `protobuf:"bytes,1,opt,name=GosNumber,proto3" json:"GosNumber,omitempty"`
	UserUUID      string                 `protobuf:"bytes,2,opt,name=UserUUID,proto3" json:"UserUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCarReq) Reset() {
	*x = CreateCarReq{}
	mi := &file_parking_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarReq) ProtoMessage() {}

func (x *CreateCarReq) ProtoReflect() protoreflect.Message {
	mi := &file_parking_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarReq.ProtoReflect.Descriptor instead.
func (*CreateCarReq) Descriptor() ([]byte, []int) {
	return file_parking_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCarReq) GetGosNumber() string {
	if x != nil {
		return x.GosNumber
	}
	return ""
}

func (x *CreateCarReq) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type CreateCarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Car           *Car                   `protobuf:"bytes,1,opt,name=Car,proto3" json:"Car,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCarResp) Reset() {
	*x = CreateCarResp{}
	mi := &file_parking_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarResp) ProtoMessage() {}

func (x *CreateCarResp) ProtoReflect() protoreflect.Message {
	mi := &file_parking_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarResp.ProtoReflect.Descriptor instead.
func (*CreateCarResp) Descriptor() ([]byte, []int) {
	return file_parking_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCarResp) GetCar() *Car {
	if x != nil {
		return x.Car
	}
	return nil
}

type Car struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	UserUUID      string                 `protobuf:"bytes,2,opt,name=UserUUID,proto3" json:"UserUUID,omitempty"`
	GosNumber     string                 `protobuf:"bytes,3,opt,name=GosNumber,proto3" json:"GosNumber,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	Settings      *CarSetting            `protobuf:"bytes,5,opt,name=Settings,proto3" json:"Settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Car) Reset() {
	*x = Car{}
	mi := &file_parking_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_parking_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_parking_service_proto_rawDescGZIP(), []int{2}
}

func (x *Car) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Car) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *Car) GetGosNumber() string {
	if x != nil {
		return x.GosNumber
	}
	return ""
}

func (x *Car) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Car) GetSettings() *CarSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CarSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	CarUUID       string                 `protobuf:"bytes,2,opt,name=CarUUID,proto3" json:"CarUUID,omitempty"`
	Vin           string                 `protobuf:"bytes,3,opt,name=Vin,proto3" json:"Vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarSetting) Reset() {
	*x = CarSetting{}
	mi := &file_parking_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarSetting) ProtoMessage() {}

func (x *CarSetting) ProtoReflect() protoreflect.Message {
	mi := &file_parking_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarSetting.ProtoReflect.Descriptor instead.
func (*CarSetting) Descriptor() ([]byte, []int) {
	return file_parking_service_proto_rawDescGZIP(), []int{3}
}

func (x *CarSetting) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *CarSetting) GetCarUUID() string {
	if x != nil {
		return x.CarUUID
	}
	return ""
}

func (x *CarSetting) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type UpdateSessionPaidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid   string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionPaidRequest) Reset() {
	*x = UpdateSessionPaidRequest{}
	mi := &file_parking_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionPaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionPaidRequest) ProtoMessage() {}

func (x *UpdateSessionPaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parking_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionPaidRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionPaidRequest) Descriptor() ([]byte, []int) {
	return file_parking_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSessionPaidRequest) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

type UpdateSessionPaidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionPaidResponse) Reset() {
	*x = UpdateSessionPaidResponse{}
	mi := &file_parking_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionPaidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionPaidResponse) ProtoMessage() {}

func (x *UpdateSessionPaidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parking_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionPaidResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionPaidResponse) Descriptor() ([]byte, []int) {
	return file_parking_service_proto_rawDescGZIP(), []int{5}
}

var File_parking_service_proto protoreflect.FileDescriptor

const file_parking_service_proto_rawDesc = "" +
	"\n" +
	"\x15parking_service.proto\x12\aparking\"H\n" +
	"\fCreateCarReq\x12\x1c\n" +
	"\tGosNumber\x18\x01 \x01(\tR\tGosNumber\x12\x1a\n" +
	"\bUserUUID\x18\x02 \x01(\tR\bUserUUID\"/\n" +
	"\rCreateCarResp\x12\x1e\n" +
	"\x03Car\x18\x01 \x01(\v2\f.parking.CarR\x03Car\"\xa0\x01\n" +
	"\x03Car\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x1a\n" +
	"\bUserUUID\x18\x02 \x01(\tR\bUserUUID\x12\x1c\n" +
	"\tGosNumber\x18\x03 \x01(\tR\tGosNumber\x12\x1a\n" +
	"\bIsActive\x18\x04 \x01(\bR\bIsActive\x12/\n" +
	"\bSettings\x18\x05 \x01(\v2\x13.parking.CarSettingR\bSettings\"L\n" +
	"\n" +
	"CarSetting\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x18\n" +
	"\aCarUUID\x18\x02 \x01(\tR\aCarUUID\x12\x10\n" +
	"\x03Vin\x18\x03 \x01(\tR\x03Vin\"=\n" +
	"\x18UpdateSessionPaidRequest\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\"\x1b\n" +
	"\x19UpdateSessionPaidResponse2\xa1\x01\n" +
	"\aParking\x12:\n" +
	"\tCreateCar\x12\x15.parking.CreateCarReq\x1a\x16.parking.CreateCarResp\x12Z\n" +
	"\x11UpdateSessionPaid\x12!.parking.UpdateSessionPaidRequest\x1a\".parking.UpdateSessionPaidResponseB\x15Z\x13contracts/pkg/protob\x06proto3"

var (
	file_parking_service_proto_rawDescOnce sync.Once
	file_parking_service_proto_rawDescData []byte
)

func file_parking_service_proto_rawDescGZIP() []byte {
	file_parking_service_proto_rawDescOnce.Do(func() {
		file_parking_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parking_service_proto_rawDesc), len(file_parking_service_proto_rawDesc)))
	})
	return file_parking_service_proto_rawDescData
}

var file_parking_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_parking_service_proto_goTypes = []any{
	(*CreateCarReq)(nil),              // 0: parking.CreateCarReq
	(*CreateCarResp)(nil),             // 1: parking.CreateCarResp
	(*Car)(nil),                       // 2: parking.Car
	(*CarSetting)(nil),                // 3: parking.CarSetting
	(*UpdateSessionPaidRequest)(nil),  // 4: parking.UpdateSessionPaidRequest
	(*UpdateSessionPaidResponse)(nil), // 5: parking.UpdateSessionPaidResponse
}
var file_parking_service_proto_depIdxs = []int32{
	2, // 0: parking.CreateCarResp.Car:type_name -> parking.Car
	3, // 1: parking.Car.Settings:type_name -> parking.CarSetting
	0, // 2: parking.Parking.CreateCar:input_type -> parking.CreateCarReq
	4, // 3: parking.Parking.UpdateSessionPaid:input_type -> parking.UpdateSessionPaidRequest
	1, // 4: parking.Parking.CreateCar:output_type -> parking.CreateCarResp
	5, // 5: parking.Parking.UpdateSessionPaid:output_type -> parking.UpdateSessionPaidResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_parking_service_proto_init() }
func file_parking_service_proto_init() {
	if File_parking_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parking_service_proto_rawDesc), len(file_parking_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parking_service_proto_goTypes,
		DependencyIndexes: file_parking_service_proto_depIdxs,
		MessageInfos:      file_parking_service_proto_msgTypes,
	}.Build()
	File_parking_service_proto = out.File
	file_parking_service_proto_goTypes = nil
	file_parking_service_proto_depIdxs = nil
}
