// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: parking_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParkingClient is the client API for Parking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParkingClient interface {
	CreateCar(ctx context.Context, in *CreateCarReq, opts ...grpc.CallOption) (*CreateCarResp, error)
	UpdateSessionPaid(ctx context.Context, in *UpdateSessionPaidRequest, opts ...grpc.CallOption) (*UpdateSessionPaidResponse, error)
}

type parkingClient struct {
	cc grpc.ClientConnInterface
}

func NewParkingClient(cc grpc.ClientConnInterface) ParkingClient {
	return &parkingClient{cc}
}

func (c *parkingClient) CreateCar(ctx context.Context, in *CreateCarReq, opts ...grpc.CallOption) (*CreateCarResp, error) {
	out := new(CreateCarResp)
	err := c.cc.Invoke(ctx, "/parking.Parking/CreateCar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingClient) UpdateSessionPaid(ctx context.Context, in *UpdateSessionPaidRequest, opts ...grpc.CallOption) (*UpdateSessionPaidResponse, error) {
	out := new(UpdateSessionPaidResponse)
	err := c.cc.Invoke(ctx, "/parking.Parking/UpdateSessionPaid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkingServer is the server API for Parking service.
// All implementations must embed UnimplementedParkingServer
// for forward compatibility
type ParkingServer interface {
	CreateCar(context.Context, *CreateCarReq) (*CreateCarResp, error)
	UpdateSessionPaid(context.Context, *UpdateSessionPaidRequest) (*UpdateSessionPaidResponse, error)
	mustEmbedUnimplementedParkingServer()
}

// UnimplementedParkingServer must be embedded to have forward compatible implementations.
type UnimplementedParkingServer struct {
}

func (UnimplementedParkingServer) CreateCar(context.Context, *CreateCarReq) (*CreateCarResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCar not implemented")
}
func (UnimplementedParkingServer) UpdateSessionPaid(context.Context, *UpdateSessionPaidRequest) (*UpdateSessionPaidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSessionPaid not implemented")
}
func (UnimplementedParkingServer) mustEmbedUnimplementedParkingServer() {}

// UnsafeParkingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParkingServer will
// result in compilation errors.
type UnsafeParkingServer interface {
	mustEmbedUnimplementedParkingServer()
}

func RegisterParkingServer(s grpc.ServiceRegistrar, srv ParkingServer) {
	s.RegisterService(&Parking_ServiceDesc, srv)
}

func _Parking_CreateCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServer).CreateCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parking.Parking/CreateCar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServer).CreateCar(ctx, req.(*CreateCarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parking_UpdateSessionPaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionPaidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServer).UpdateSessionPaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parking.Parking/UpdateSessionPaid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServer).UpdateSessionPaid(ctx, req.(*UpdateSessionPaidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Parking_ServiceDesc is the grpc.ServiceDesc for Parking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Parking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parking.Parking",
	HandlerType: (*ParkingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCar",
			Handler:    _Parking_CreateCar_Handler,
		},
		{
			MethodName: "UpdateSessionPaid",
			Handler:    _Parking_UpdateSessionPaid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parking_service.proto",
}
