// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i k071123/internal/services/notification_service/contracts/pkg/proto.NotificationClient -o notification_client_mock_test.go -n NotificationClientMock -p mocks

import (
	context "context"
	mm_proto "k071123/internal/services/notification_service/contracts/pkg/proto"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	grpc "google.golang.org/grpc"
)

// NotificationClientMock implements mm_proto.NotificationClient
type NotificationClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSendEmail          func(ctx context.Context, in *mm_proto.SendEmailReq, opts ...grpc.CallOption) (sp1 *mm_proto.SendEmailResp, err error)
	funcSendEmailOrigin    string
	inspectFuncSendEmail   func(ctx context.Context, in *mm_proto.SendEmailReq, opts ...grpc.CallOption)
	afterSendEmailCounter  uint64
	beforeSendEmailCounter uint64
	SendEmailMock          mNotificationClientMockSendEmail
}

// NewNotificationClientMock returns a mock for mm_proto.NotificationClient
func NewNotificationClientMock(t minimock.Tester) *NotificationClientMock {
	m := &NotificationClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendEmailMock = mNotificationClientMockSendEmail{mock: m}
	m.SendEmailMock.callArgs = []*NotificationClientMockSendEmailParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mNotificationClientMockSendEmail struct {
	optional           bool
	mock               *NotificationClientMock
	defaultExpectation *NotificationClientMockSendEmailExpectation
	expectations       []*NotificationClientMockSendEmailExpectation

	callArgs []*NotificationClientMockSendEmailParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// NotificationClientMockSendEmailExpectation specifies expectation struct of the NotificationClient.SendEmail
type NotificationClientMockSendEmailExpectation struct {
	mock               *NotificationClientMock
	params             *NotificationClientMockSendEmailParams
	paramPtrs          *NotificationClientMockSendEmailParamPtrs
	expectationOrigins NotificationClientMockSendEmailExpectationOrigins
	results            *NotificationClientMockSendEmailResults
	returnOrigin       string
	Counter            uint64
}

// NotificationClientMockSendEmailParams contains parameters of the NotificationClient.SendEmail
type NotificationClientMockSendEmailParams struct {
	ctx  context.Context
	in   *mm_proto.SendEmailReq
	opts []grpc.CallOption
}

// NotificationClientMockSendEmailParamPtrs contains pointers to parameters of the NotificationClient.SendEmail
type NotificationClientMockSendEmailParamPtrs struct {
	ctx  *context.Context
	in   **mm_proto.SendEmailReq
	opts *[]grpc.CallOption
}

// NotificationClientMockSendEmailResults contains results of the NotificationClient.SendEmail
type NotificationClientMockSendEmailResults struct {
	sp1 *mm_proto.SendEmailResp
	err error
}

// NotificationClientMockSendEmailOrigins contains origins of expectations of the NotificationClient.SendEmail
type NotificationClientMockSendEmailExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendEmail *mNotificationClientMockSendEmail) Optional() *mNotificationClientMockSendEmail {
	mmSendEmail.optional = true
	return mmSendEmail
}

// Expect sets up expected params for NotificationClient.SendEmail
func (mmSendEmail *mNotificationClientMockSendEmail) Expect(ctx context.Context, in *mm_proto.SendEmailReq, opts ...grpc.CallOption) *mNotificationClientMockSendEmail {
	if mmSendEmail.mock.funcSendEmail != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Set")
	}

	if mmSendEmail.defaultExpectation == nil {
		mmSendEmail.defaultExpectation = &NotificationClientMockSendEmailExpectation{}
	}

	if mmSendEmail.defaultExpectation.paramPtrs != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by ExpectParams functions")
	}

	mmSendEmail.defaultExpectation.params = &NotificationClientMockSendEmailParams{ctx, in, opts}
	mmSendEmail.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendEmail.expectations {
		if minimock.Equal(e.params, mmSendEmail.defaultExpectation.params) {
			mmSendEmail.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendEmail.defaultExpectation.params)
		}
	}

	return mmSendEmail
}

// ExpectCtxParam1 sets up expected param ctx for NotificationClient.SendEmail
func (mmSendEmail *mNotificationClientMockSendEmail) ExpectCtxParam1(ctx context.Context) *mNotificationClientMockSendEmail {
	if mmSendEmail.mock.funcSendEmail != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Set")
	}

	if mmSendEmail.defaultExpectation == nil {
		mmSendEmail.defaultExpectation = &NotificationClientMockSendEmailExpectation{}
	}

	if mmSendEmail.defaultExpectation.params != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Expect")
	}

	if mmSendEmail.defaultExpectation.paramPtrs == nil {
		mmSendEmail.defaultExpectation.paramPtrs = &NotificationClientMockSendEmailParamPtrs{}
	}
	mmSendEmail.defaultExpectation.paramPtrs.ctx = &ctx
	mmSendEmail.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSendEmail
}

// ExpectInParam2 sets up expected param in for NotificationClient.SendEmail
func (mmSendEmail *mNotificationClientMockSendEmail) ExpectInParam2(in *mm_proto.SendEmailReq) *mNotificationClientMockSendEmail {
	if mmSendEmail.mock.funcSendEmail != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Set")
	}

	if mmSendEmail.defaultExpectation == nil {
		mmSendEmail.defaultExpectation = &NotificationClientMockSendEmailExpectation{}
	}

	if mmSendEmail.defaultExpectation.params != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Expect")
	}

	if mmSendEmail.defaultExpectation.paramPtrs == nil {
		mmSendEmail.defaultExpectation.paramPtrs = &NotificationClientMockSendEmailParamPtrs{}
	}
	mmSendEmail.defaultExpectation.paramPtrs.in = &in
	mmSendEmail.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmSendEmail
}

// ExpectOptsParam3 sets up expected param opts for NotificationClient.SendEmail
func (mmSendEmail *mNotificationClientMockSendEmail) ExpectOptsParam3(opts ...grpc.CallOption) *mNotificationClientMockSendEmail {
	if mmSendEmail.mock.funcSendEmail != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Set")
	}

	if mmSendEmail.defaultExpectation == nil {
		mmSendEmail.defaultExpectation = &NotificationClientMockSendEmailExpectation{}
	}

	if mmSendEmail.defaultExpectation.params != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Expect")
	}

	if mmSendEmail.defaultExpectation.paramPtrs == nil {
		mmSendEmail.defaultExpectation.paramPtrs = &NotificationClientMockSendEmailParamPtrs{}
	}
	mmSendEmail.defaultExpectation.paramPtrs.opts = &opts
	mmSendEmail.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmSendEmail
}

// Inspect accepts an inspector function that has same arguments as the NotificationClient.SendEmail
func (mmSendEmail *mNotificationClientMockSendEmail) Inspect(f func(ctx context.Context, in *mm_proto.SendEmailReq, opts ...grpc.CallOption)) *mNotificationClientMockSendEmail {
	if mmSendEmail.mock.inspectFuncSendEmail != nil {
		mmSendEmail.mock.t.Fatalf("Inspect function is already set for NotificationClientMock.SendEmail")
	}

	mmSendEmail.mock.inspectFuncSendEmail = f

	return mmSendEmail
}

// Return sets up results that will be returned by NotificationClient.SendEmail
func (mmSendEmail *mNotificationClientMockSendEmail) Return(sp1 *mm_proto.SendEmailResp, err error) *NotificationClientMock {
	if mmSendEmail.mock.funcSendEmail != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Set")
	}

	if mmSendEmail.defaultExpectation == nil {
		mmSendEmail.defaultExpectation = &NotificationClientMockSendEmailExpectation{mock: mmSendEmail.mock}
	}
	mmSendEmail.defaultExpectation.results = &NotificationClientMockSendEmailResults{sp1, err}
	mmSendEmail.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendEmail.mock
}

// Set uses given function f to mock the NotificationClient.SendEmail method
func (mmSendEmail *mNotificationClientMockSendEmail) Set(f func(ctx context.Context, in *mm_proto.SendEmailReq, opts ...grpc.CallOption) (sp1 *mm_proto.SendEmailResp, err error)) *NotificationClientMock {
	if mmSendEmail.defaultExpectation != nil {
		mmSendEmail.mock.t.Fatalf("Default expectation is already set for the NotificationClient.SendEmail method")
	}

	if len(mmSendEmail.expectations) > 0 {
		mmSendEmail.mock.t.Fatalf("Some expectations are already set for the NotificationClient.SendEmail method")
	}

	mmSendEmail.mock.funcSendEmail = f
	mmSendEmail.mock.funcSendEmailOrigin = minimock.CallerInfo(1)
	return mmSendEmail.mock
}

// When sets expectation for the NotificationClient.SendEmail which will trigger the result defined by the following
// Then helper
func (mmSendEmail *mNotificationClientMockSendEmail) When(ctx context.Context, in *mm_proto.SendEmailReq, opts ...grpc.CallOption) *NotificationClientMockSendEmailExpectation {
	if mmSendEmail.mock.funcSendEmail != nil {
		mmSendEmail.mock.t.Fatalf("NotificationClientMock.SendEmail mock is already set by Set")
	}

	expectation := &NotificationClientMockSendEmailExpectation{
		mock:               mmSendEmail.mock,
		params:             &NotificationClientMockSendEmailParams{ctx, in, opts},
		expectationOrigins: NotificationClientMockSendEmailExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendEmail.expectations = append(mmSendEmail.expectations, expectation)
	return expectation
}

// Then sets up NotificationClient.SendEmail return parameters for the expectation previously defined by the When method
func (e *NotificationClientMockSendEmailExpectation) Then(sp1 *mm_proto.SendEmailResp, err error) *NotificationClientMock {
	e.results = &NotificationClientMockSendEmailResults{sp1, err}
	return e.mock
}

// Times sets number of times NotificationClient.SendEmail should be invoked
func (mmSendEmail *mNotificationClientMockSendEmail) Times(n uint64) *mNotificationClientMockSendEmail {
	if n == 0 {
		mmSendEmail.mock.t.Fatalf("Times of NotificationClientMock.SendEmail mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendEmail.expectedInvocations, n)
	mmSendEmail.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendEmail
}

func (mmSendEmail *mNotificationClientMockSendEmail) invocationsDone() bool {
	if len(mmSendEmail.expectations) == 0 && mmSendEmail.defaultExpectation == nil && mmSendEmail.mock.funcSendEmail == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendEmail.mock.afterSendEmailCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendEmail.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendEmail implements mm_proto.NotificationClient
func (mmSendEmail *NotificationClientMock) SendEmail(ctx context.Context, in *mm_proto.SendEmailReq, opts ...grpc.CallOption) (sp1 *mm_proto.SendEmailResp, err error) {
	mm_atomic.AddUint64(&mmSendEmail.beforeSendEmailCounter, 1)
	defer mm_atomic.AddUint64(&mmSendEmail.afterSendEmailCounter, 1)

	mmSendEmail.t.Helper()

	if mmSendEmail.inspectFuncSendEmail != nil {
		mmSendEmail.inspectFuncSendEmail(ctx, in, opts...)
	}

	mm_params := NotificationClientMockSendEmailParams{ctx, in, opts}

	// Record call args
	mmSendEmail.SendEmailMock.mutex.Lock()
	mmSendEmail.SendEmailMock.callArgs = append(mmSendEmail.SendEmailMock.callArgs, &mm_params)
	mmSendEmail.SendEmailMock.mutex.Unlock()

	for _, e := range mmSendEmail.SendEmailMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmSendEmail.SendEmailMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendEmail.SendEmailMock.defaultExpectation.Counter, 1)
		mm_want := mmSendEmail.SendEmailMock.defaultExpectation.params
		mm_want_ptrs := mmSendEmail.SendEmailMock.defaultExpectation.paramPtrs

		mm_got := NotificationClientMockSendEmailParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendEmail.t.Errorf("NotificationClientMock.SendEmail got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendEmail.SendEmailMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmSendEmail.t.Errorf("NotificationClientMock.SendEmail got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendEmail.SendEmailMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmSendEmail.t.Errorf("NotificationClientMock.SendEmail got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendEmail.SendEmailMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendEmail.t.Errorf("NotificationClientMock.SendEmail got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendEmail.SendEmailMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendEmail.SendEmailMock.defaultExpectation.results
		if mm_results == nil {
			mmSendEmail.t.Fatal("No results are set for the NotificationClientMock.SendEmail")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmSendEmail.funcSendEmail != nil {
		return mmSendEmail.funcSendEmail(ctx, in, opts...)
	}
	mmSendEmail.t.Fatalf("Unexpected call to NotificationClientMock.SendEmail. %v %v %v", ctx, in, opts)
	return
}

// SendEmailAfterCounter returns a count of finished NotificationClientMock.SendEmail invocations
func (mmSendEmail *NotificationClientMock) SendEmailAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendEmail.afterSendEmailCounter)
}

// SendEmailBeforeCounter returns a count of NotificationClientMock.SendEmail invocations
func (mmSendEmail *NotificationClientMock) SendEmailBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendEmail.beforeSendEmailCounter)
}

// Calls returns a list of arguments used in each call to NotificationClientMock.SendEmail.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendEmail *mNotificationClientMockSendEmail) Calls() []*NotificationClientMockSendEmailParams {
	mmSendEmail.mutex.RLock()

	argCopy := make([]*NotificationClientMockSendEmailParams, len(mmSendEmail.callArgs))
	copy(argCopy, mmSendEmail.callArgs)

	mmSendEmail.mutex.RUnlock()

	return argCopy
}

// MinimockSendEmailDone returns true if the count of the SendEmail invocations corresponds
// the number of defined expectations
func (m *NotificationClientMock) MinimockSendEmailDone() bool {
	if m.SendEmailMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendEmailMock.invocationsDone()
}

// MinimockSendEmailInspect logs each unmet expectation
func (m *NotificationClientMock) MinimockSendEmailInspect() {
	for _, e := range m.SendEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to NotificationClientMock.SendEmail at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendEmailCounter := mm_atomic.LoadUint64(&m.afterSendEmailCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendEmailMock.defaultExpectation != nil && afterSendEmailCounter < 1 {
		if m.SendEmailMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to NotificationClientMock.SendEmail at\n%s", m.SendEmailMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to NotificationClientMock.SendEmail at\n%s with params: %#v", m.SendEmailMock.defaultExpectation.expectationOrigins.origin, *m.SendEmailMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendEmail != nil && afterSendEmailCounter < 1 {
		m.t.Errorf("Expected call to NotificationClientMock.SendEmail at\n%s", m.funcSendEmailOrigin)
	}

	if !m.SendEmailMock.invocationsDone() && afterSendEmailCounter > 0 {
		m.t.Errorf("Expected %d calls to NotificationClientMock.SendEmail at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendEmailMock.expectedInvocations), m.SendEmailMock.expectedInvocationsOrigin, afterSendEmailCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *NotificationClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendEmailInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *NotificationClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *NotificationClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendEmailDone()
}
