// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i k071123/internal/services/user_service/contracts/pkg/proto.UserClient -o user_client_mock_test.go -n UserClientMock -p mocks

import (
	context "context"
	mm_proto "k071123/internal/services/user_service/contracts/pkg/proto"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	grpc "google.golang.org/grpc"
)

// UserClientMock implements mm_proto.UserClient
type UserClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetUserByUUID          func(ctx context.Context, in *mm_proto.GetUserReq, opts ...grpc.CallOption) (gp1 *mm_proto.GetUserResp, err error)
	funcGetUserByUUIDOrigin    string
	inspectFuncGetUserByUUID   func(ctx context.Context, in *mm_proto.GetUserReq, opts ...grpc.CallOption)
	afterGetUserByUUIDCounter  uint64
	beforeGetUserByUUIDCounter uint64
	GetUserByUUIDMock          mUserClientMockGetUserByUUID
}

// NewUserClientMock returns a mock for mm_proto.UserClient
func NewUserClientMock(t minimock.Tester) *UserClientMock {
	m := &UserClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetUserByUUIDMock = mUserClientMockGetUserByUUID{mock: m}
	m.GetUserByUUIDMock.callArgs = []*UserClientMockGetUserByUUIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserClientMockGetUserByUUID struct {
	optional           bool
	mock               *UserClientMock
	defaultExpectation *UserClientMockGetUserByUUIDExpectation
	expectations       []*UserClientMockGetUserByUUIDExpectation

	callArgs []*UserClientMockGetUserByUUIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserClientMockGetUserByUUIDExpectation specifies expectation struct of the UserClient.GetUserByUUID
type UserClientMockGetUserByUUIDExpectation struct {
	mock               *UserClientMock
	params             *UserClientMockGetUserByUUIDParams
	paramPtrs          *UserClientMockGetUserByUUIDParamPtrs
	expectationOrigins UserClientMockGetUserByUUIDExpectationOrigins
	results            *UserClientMockGetUserByUUIDResults
	returnOrigin       string
	Counter            uint64
}

// UserClientMockGetUserByUUIDParams contains parameters of the UserClient.GetUserByUUID
type UserClientMockGetUserByUUIDParams struct {
	ctx  context.Context
	in   *mm_proto.GetUserReq
	opts []grpc.CallOption
}

// UserClientMockGetUserByUUIDParamPtrs contains pointers to parameters of the UserClient.GetUserByUUID
type UserClientMockGetUserByUUIDParamPtrs struct {
	ctx  *context.Context
	in   **mm_proto.GetUserReq
	opts *[]grpc.CallOption
}

// UserClientMockGetUserByUUIDResults contains results of the UserClient.GetUserByUUID
type UserClientMockGetUserByUUIDResults struct {
	gp1 *mm_proto.GetUserResp
	err error
}

// UserClientMockGetUserByUUIDOrigins contains origins of expectations of the UserClient.GetUserByUUID
type UserClientMockGetUserByUUIDExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) Optional() *mUserClientMockGetUserByUUID {
	mmGetUserByUUID.optional = true
	return mmGetUserByUUID
}

// Expect sets up expected params for UserClient.GetUserByUUID
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) Expect(ctx context.Context, in *mm_proto.GetUserReq, opts ...grpc.CallOption) *mUserClientMockGetUserByUUID {
	if mmGetUserByUUID.mock.funcGetUserByUUID != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Set")
	}

	if mmGetUserByUUID.defaultExpectation == nil {
		mmGetUserByUUID.defaultExpectation = &UserClientMockGetUserByUUIDExpectation{}
	}

	if mmGetUserByUUID.defaultExpectation.paramPtrs != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by ExpectParams functions")
	}

	mmGetUserByUUID.defaultExpectation.params = &UserClientMockGetUserByUUIDParams{ctx, in, opts}
	mmGetUserByUUID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetUserByUUID.expectations {
		if minimock.Equal(e.params, mmGetUserByUUID.defaultExpectation.params) {
			mmGetUserByUUID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetUserByUUID.defaultExpectation.params)
		}
	}

	return mmGetUserByUUID
}

// ExpectCtxParam1 sets up expected param ctx for UserClient.GetUserByUUID
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) ExpectCtxParam1(ctx context.Context) *mUserClientMockGetUserByUUID {
	if mmGetUserByUUID.mock.funcGetUserByUUID != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Set")
	}

	if mmGetUserByUUID.defaultExpectation == nil {
		mmGetUserByUUID.defaultExpectation = &UserClientMockGetUserByUUIDExpectation{}
	}

	if mmGetUserByUUID.defaultExpectation.params != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Expect")
	}

	if mmGetUserByUUID.defaultExpectation.paramPtrs == nil {
		mmGetUserByUUID.defaultExpectation.paramPtrs = &UserClientMockGetUserByUUIDParamPtrs{}
	}
	mmGetUserByUUID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetUserByUUID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetUserByUUID
}

// ExpectInParam2 sets up expected param in for UserClient.GetUserByUUID
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) ExpectInParam2(in *mm_proto.GetUserReq) *mUserClientMockGetUserByUUID {
	if mmGetUserByUUID.mock.funcGetUserByUUID != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Set")
	}

	if mmGetUserByUUID.defaultExpectation == nil {
		mmGetUserByUUID.defaultExpectation = &UserClientMockGetUserByUUIDExpectation{}
	}

	if mmGetUserByUUID.defaultExpectation.params != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Expect")
	}

	if mmGetUserByUUID.defaultExpectation.paramPtrs == nil {
		mmGetUserByUUID.defaultExpectation.paramPtrs = &UserClientMockGetUserByUUIDParamPtrs{}
	}
	mmGetUserByUUID.defaultExpectation.paramPtrs.in = &in
	mmGetUserByUUID.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmGetUserByUUID
}

// ExpectOptsParam3 sets up expected param opts for UserClient.GetUserByUUID
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) ExpectOptsParam3(opts ...grpc.CallOption) *mUserClientMockGetUserByUUID {
	if mmGetUserByUUID.mock.funcGetUserByUUID != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Set")
	}

	if mmGetUserByUUID.defaultExpectation == nil {
		mmGetUserByUUID.defaultExpectation = &UserClientMockGetUserByUUIDExpectation{}
	}

	if mmGetUserByUUID.defaultExpectation.params != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Expect")
	}

	if mmGetUserByUUID.defaultExpectation.paramPtrs == nil {
		mmGetUserByUUID.defaultExpectation.paramPtrs = &UserClientMockGetUserByUUIDParamPtrs{}
	}
	mmGetUserByUUID.defaultExpectation.paramPtrs.opts = &opts
	mmGetUserByUUID.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmGetUserByUUID
}

// Inspect accepts an inspector function that has same arguments as the UserClient.GetUserByUUID
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) Inspect(f func(ctx context.Context, in *mm_proto.GetUserReq, opts ...grpc.CallOption)) *mUserClientMockGetUserByUUID {
	if mmGetUserByUUID.mock.inspectFuncGetUserByUUID != nil {
		mmGetUserByUUID.mock.t.Fatalf("Inspect function is already set for UserClientMock.GetUserByUUID")
	}

	mmGetUserByUUID.mock.inspectFuncGetUserByUUID = f

	return mmGetUserByUUID
}

// Return sets up results that will be returned by UserClient.GetUserByUUID
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) Return(gp1 *mm_proto.GetUserResp, err error) *UserClientMock {
	if mmGetUserByUUID.mock.funcGetUserByUUID != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Set")
	}

	if mmGetUserByUUID.defaultExpectation == nil {
		mmGetUserByUUID.defaultExpectation = &UserClientMockGetUserByUUIDExpectation{mock: mmGetUserByUUID.mock}
	}
	mmGetUserByUUID.defaultExpectation.results = &UserClientMockGetUserByUUIDResults{gp1, err}
	mmGetUserByUUID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetUserByUUID.mock
}

// Set uses given function f to mock the UserClient.GetUserByUUID method
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) Set(f func(ctx context.Context, in *mm_proto.GetUserReq, opts ...grpc.CallOption) (gp1 *mm_proto.GetUserResp, err error)) *UserClientMock {
	if mmGetUserByUUID.defaultExpectation != nil {
		mmGetUserByUUID.mock.t.Fatalf("Default expectation is already set for the UserClient.GetUserByUUID method")
	}

	if len(mmGetUserByUUID.expectations) > 0 {
		mmGetUserByUUID.mock.t.Fatalf("Some expectations are already set for the UserClient.GetUserByUUID method")
	}

	mmGetUserByUUID.mock.funcGetUserByUUID = f
	mmGetUserByUUID.mock.funcGetUserByUUIDOrigin = minimock.CallerInfo(1)
	return mmGetUserByUUID.mock
}

// When sets expectation for the UserClient.GetUserByUUID which will trigger the result defined by the following
// Then helper
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) When(ctx context.Context, in *mm_proto.GetUserReq, opts ...grpc.CallOption) *UserClientMockGetUserByUUIDExpectation {
	if mmGetUserByUUID.mock.funcGetUserByUUID != nil {
		mmGetUserByUUID.mock.t.Fatalf("UserClientMock.GetUserByUUID mock is already set by Set")
	}

	expectation := &UserClientMockGetUserByUUIDExpectation{
		mock:               mmGetUserByUUID.mock,
		params:             &UserClientMockGetUserByUUIDParams{ctx, in, opts},
		expectationOrigins: UserClientMockGetUserByUUIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetUserByUUID.expectations = append(mmGetUserByUUID.expectations, expectation)
	return expectation
}

// Then sets up UserClient.GetUserByUUID return parameters for the expectation previously defined by the When method
func (e *UserClientMockGetUserByUUIDExpectation) Then(gp1 *mm_proto.GetUserResp, err error) *UserClientMock {
	e.results = &UserClientMockGetUserByUUIDResults{gp1, err}
	return e.mock
}

// Times sets number of times UserClient.GetUserByUUID should be invoked
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) Times(n uint64) *mUserClientMockGetUserByUUID {
	if n == 0 {
		mmGetUserByUUID.mock.t.Fatalf("Times of UserClientMock.GetUserByUUID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetUserByUUID.expectedInvocations, n)
	mmGetUserByUUID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetUserByUUID
}

func (mmGetUserByUUID *mUserClientMockGetUserByUUID) invocationsDone() bool {
	if len(mmGetUserByUUID.expectations) == 0 && mmGetUserByUUID.defaultExpectation == nil && mmGetUserByUUID.mock.funcGetUserByUUID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetUserByUUID.mock.afterGetUserByUUIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetUserByUUID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetUserByUUID implements mm_proto.UserClient
func (mmGetUserByUUID *UserClientMock) GetUserByUUID(ctx context.Context, in *mm_proto.GetUserReq, opts ...grpc.CallOption) (gp1 *mm_proto.GetUserResp, err error) {
	mm_atomic.AddUint64(&mmGetUserByUUID.beforeGetUserByUUIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetUserByUUID.afterGetUserByUUIDCounter, 1)

	mmGetUserByUUID.t.Helper()

	if mmGetUserByUUID.inspectFuncGetUserByUUID != nil {
		mmGetUserByUUID.inspectFuncGetUserByUUID(ctx, in, opts...)
	}

	mm_params := UserClientMockGetUserByUUIDParams{ctx, in, opts}

	// Record call args
	mmGetUserByUUID.GetUserByUUIDMock.mutex.Lock()
	mmGetUserByUUID.GetUserByUUIDMock.callArgs = append(mmGetUserByUUID.GetUserByUUIDMock.callArgs, &mm_params)
	mmGetUserByUUID.GetUserByUUIDMock.mutex.Unlock()

	for _, e := range mmGetUserByUUID.GetUserByUUIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.gp1, e.results.err
		}
	}

	if mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation.paramPtrs

		mm_got := UserClientMockGetUserByUUIDParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetUserByUUID.t.Errorf("UserClientMock.GetUserByUUID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmGetUserByUUID.t.Errorf("UserClientMock.GetUserByUUID got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmGetUserByUUID.t.Errorf("UserClientMock.GetUserByUUID got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetUserByUUID.t.Errorf("UserClientMock.GetUserByUUID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetUserByUUID.GetUserByUUIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetUserByUUID.t.Fatal("No results are set for the UserClientMock.GetUserByUUID")
		}
		return (*mm_results).gp1, (*mm_results).err
	}
	if mmGetUserByUUID.funcGetUserByUUID != nil {
		return mmGetUserByUUID.funcGetUserByUUID(ctx, in, opts...)
	}
	mmGetUserByUUID.t.Fatalf("Unexpected call to UserClientMock.GetUserByUUID. %v %v %v", ctx, in, opts)
	return
}

// GetUserByUUIDAfterCounter returns a count of finished UserClientMock.GetUserByUUID invocations
func (mmGetUserByUUID *UserClientMock) GetUserByUUIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByUUID.afterGetUserByUUIDCounter)
}

// GetUserByUUIDBeforeCounter returns a count of UserClientMock.GetUserByUUID invocations
func (mmGetUserByUUID *UserClientMock) GetUserByUUIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetUserByUUID.beforeGetUserByUUIDCounter)
}

// Calls returns a list of arguments used in each call to UserClientMock.GetUserByUUID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetUserByUUID *mUserClientMockGetUserByUUID) Calls() []*UserClientMockGetUserByUUIDParams {
	mmGetUserByUUID.mutex.RLock()

	argCopy := make([]*UserClientMockGetUserByUUIDParams, len(mmGetUserByUUID.callArgs))
	copy(argCopy, mmGetUserByUUID.callArgs)

	mmGetUserByUUID.mutex.RUnlock()

	return argCopy
}

// MinimockGetUserByUUIDDone returns true if the count of the GetUserByUUID invocations corresponds
// the number of defined expectations
func (m *UserClientMock) MinimockGetUserByUUIDDone() bool {
	if m.GetUserByUUIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetUserByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetUserByUUIDMock.invocationsDone()
}

// MinimockGetUserByUUIDInspect logs each unmet expectation
func (m *UserClientMock) MinimockGetUserByUUIDInspect() {
	for _, e := range m.GetUserByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserClientMock.GetUserByUUID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetUserByUUIDCounter := mm_atomic.LoadUint64(&m.afterGetUserByUUIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetUserByUUIDMock.defaultExpectation != nil && afterGetUserByUUIDCounter < 1 {
		if m.GetUserByUUIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserClientMock.GetUserByUUID at\n%s", m.GetUserByUUIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserClientMock.GetUserByUUID at\n%s with params: %#v", m.GetUserByUUIDMock.defaultExpectation.expectationOrigins.origin, *m.GetUserByUUIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetUserByUUID != nil && afterGetUserByUUIDCounter < 1 {
		m.t.Errorf("Expected call to UserClientMock.GetUserByUUID at\n%s", m.funcGetUserByUUIDOrigin)
	}

	if !m.GetUserByUUIDMock.invocationsDone() && afterGetUserByUUIDCounter > 0 {
		m.t.Errorf("Expected %d calls to UserClientMock.GetUserByUUID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetUserByUUIDMock.expectedInvocations), m.GetUserByUUIDMock.expectedInvocationsOrigin, afterGetUserByUUIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetUserByUUIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetUserByUUIDDone()
}
