// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i k071123/internal/services/order_service/contracts/pkg/proto.OrderClient -o order_client_mock_test.go -n OrderClientMock -p mocks

import (
	context "context"
	mm_proto "k071123/internal/services/order_service/contracts/pkg/proto"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	grpc "google.golang.org/grpc"
)

// OrderClientMock implements mm_proto.OrderClient
type OrderClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreatePayment          func(ctx context.Context, in *mm_proto.CreatePaymentReq, opts ...grpc.CallOption) (cp1 *mm_proto.CreatePaymentResp, err error)
	funcCreatePaymentOrigin    string
	inspectFuncCreatePayment   func(ctx context.Context, in *mm_proto.CreatePaymentReq, opts ...grpc.CallOption)
	afterCreatePaymentCounter  uint64
	beforeCreatePaymentCounter uint64
	CreatePaymentMock          mOrderClientMockCreatePayment

	funcGetPreferredByUserUUID          func(ctx context.Context, in *mm_proto.GetPreferredCardReq, opts ...grpc.CallOption) (gp1 *mm_proto.GetPreferredCardResp, err error)
	funcGetPreferredByUserUUIDOrigin    string
	inspectFuncGetPreferredByUserUUID   func(ctx context.Context, in *mm_proto.GetPreferredCardReq, opts ...grpc.CallOption)
	afterGetPreferredByUserUUIDCounter  uint64
	beforeGetPreferredByUserUUIDCounter uint64
	GetPreferredByUserUUIDMock          mOrderClientMockGetPreferredByUserUUID

	funcSaveCard          func(ctx context.Context, in *mm_proto.SaveCardReq, opts ...grpc.CallOption) (sp1 *mm_proto.SaveCardResp, err error)
	funcSaveCardOrigin    string
	inspectFuncSaveCard   func(ctx context.Context, in *mm_proto.SaveCardReq, opts ...grpc.CallOption)
	afterSaveCardCounter  uint64
	beforeSaveCardCounter uint64
	SaveCardMock          mOrderClientMockSaveCard
}

// NewOrderClientMock returns a mock for mm_proto.OrderClient
func NewOrderClientMock(t minimock.Tester) *OrderClientMock {
	m := &OrderClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreatePaymentMock = mOrderClientMockCreatePayment{mock: m}
	m.CreatePaymentMock.callArgs = []*OrderClientMockCreatePaymentParams{}

	m.GetPreferredByUserUUIDMock = mOrderClientMockGetPreferredByUserUUID{mock: m}
	m.GetPreferredByUserUUIDMock.callArgs = []*OrderClientMockGetPreferredByUserUUIDParams{}

	m.SaveCardMock = mOrderClientMockSaveCard{mock: m}
	m.SaveCardMock.callArgs = []*OrderClientMockSaveCardParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrderClientMockCreatePayment struct {
	optional           bool
	mock               *OrderClientMock
	defaultExpectation *OrderClientMockCreatePaymentExpectation
	expectations       []*OrderClientMockCreatePaymentExpectation

	callArgs []*OrderClientMockCreatePaymentParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderClientMockCreatePaymentExpectation specifies expectation struct of the OrderClient.CreatePayment
type OrderClientMockCreatePaymentExpectation struct {
	mock               *OrderClientMock
	params             *OrderClientMockCreatePaymentParams
	paramPtrs          *OrderClientMockCreatePaymentParamPtrs
	expectationOrigins OrderClientMockCreatePaymentExpectationOrigins
	results            *OrderClientMockCreatePaymentResults
	returnOrigin       string
	Counter            uint64
}

// OrderClientMockCreatePaymentParams contains parameters of the OrderClient.CreatePayment
type OrderClientMockCreatePaymentParams struct {
	ctx  context.Context
	in   *mm_proto.CreatePaymentReq
	opts []grpc.CallOption
}

// OrderClientMockCreatePaymentParamPtrs contains pointers to parameters of the OrderClient.CreatePayment
type OrderClientMockCreatePaymentParamPtrs struct {
	ctx  *context.Context
	in   **mm_proto.CreatePaymentReq
	opts *[]grpc.CallOption
}

// OrderClientMockCreatePaymentResults contains results of the OrderClient.CreatePayment
type OrderClientMockCreatePaymentResults struct {
	cp1 *mm_proto.CreatePaymentResp
	err error
}

// OrderClientMockCreatePaymentOrigins contains origins of expectations of the OrderClient.CreatePayment
type OrderClientMockCreatePaymentExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreatePayment *mOrderClientMockCreatePayment) Optional() *mOrderClientMockCreatePayment {
	mmCreatePayment.optional = true
	return mmCreatePayment
}

// Expect sets up expected params for OrderClient.CreatePayment
func (mmCreatePayment *mOrderClientMockCreatePayment) Expect(ctx context.Context, in *mm_proto.CreatePaymentReq, opts ...grpc.CallOption) *mOrderClientMockCreatePayment {
	if mmCreatePayment.mock.funcCreatePayment != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Set")
	}

	if mmCreatePayment.defaultExpectation == nil {
		mmCreatePayment.defaultExpectation = &OrderClientMockCreatePaymentExpectation{}
	}

	if mmCreatePayment.defaultExpectation.paramPtrs != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by ExpectParams functions")
	}

	mmCreatePayment.defaultExpectation.params = &OrderClientMockCreatePaymentParams{ctx, in, opts}
	mmCreatePayment.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreatePayment.expectations {
		if minimock.Equal(e.params, mmCreatePayment.defaultExpectation.params) {
			mmCreatePayment.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreatePayment.defaultExpectation.params)
		}
	}

	return mmCreatePayment
}

// ExpectCtxParam1 sets up expected param ctx for OrderClient.CreatePayment
func (mmCreatePayment *mOrderClientMockCreatePayment) ExpectCtxParam1(ctx context.Context) *mOrderClientMockCreatePayment {
	if mmCreatePayment.mock.funcCreatePayment != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Set")
	}

	if mmCreatePayment.defaultExpectation == nil {
		mmCreatePayment.defaultExpectation = &OrderClientMockCreatePaymentExpectation{}
	}

	if mmCreatePayment.defaultExpectation.params != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Expect")
	}

	if mmCreatePayment.defaultExpectation.paramPtrs == nil {
		mmCreatePayment.defaultExpectation.paramPtrs = &OrderClientMockCreatePaymentParamPtrs{}
	}
	mmCreatePayment.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreatePayment.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreatePayment
}

// ExpectInParam2 sets up expected param in for OrderClient.CreatePayment
func (mmCreatePayment *mOrderClientMockCreatePayment) ExpectInParam2(in *mm_proto.CreatePaymentReq) *mOrderClientMockCreatePayment {
	if mmCreatePayment.mock.funcCreatePayment != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Set")
	}

	if mmCreatePayment.defaultExpectation == nil {
		mmCreatePayment.defaultExpectation = &OrderClientMockCreatePaymentExpectation{}
	}

	if mmCreatePayment.defaultExpectation.params != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Expect")
	}

	if mmCreatePayment.defaultExpectation.paramPtrs == nil {
		mmCreatePayment.defaultExpectation.paramPtrs = &OrderClientMockCreatePaymentParamPtrs{}
	}
	mmCreatePayment.defaultExpectation.paramPtrs.in = &in
	mmCreatePayment.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmCreatePayment
}

// ExpectOptsParam3 sets up expected param opts for OrderClient.CreatePayment
func (mmCreatePayment *mOrderClientMockCreatePayment) ExpectOptsParam3(opts ...grpc.CallOption) *mOrderClientMockCreatePayment {
	if mmCreatePayment.mock.funcCreatePayment != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Set")
	}

	if mmCreatePayment.defaultExpectation == nil {
		mmCreatePayment.defaultExpectation = &OrderClientMockCreatePaymentExpectation{}
	}

	if mmCreatePayment.defaultExpectation.params != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Expect")
	}

	if mmCreatePayment.defaultExpectation.paramPtrs == nil {
		mmCreatePayment.defaultExpectation.paramPtrs = &OrderClientMockCreatePaymentParamPtrs{}
	}
	mmCreatePayment.defaultExpectation.paramPtrs.opts = &opts
	mmCreatePayment.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmCreatePayment
}

// Inspect accepts an inspector function that has same arguments as the OrderClient.CreatePayment
func (mmCreatePayment *mOrderClientMockCreatePayment) Inspect(f func(ctx context.Context, in *mm_proto.CreatePaymentReq, opts ...grpc.CallOption)) *mOrderClientMockCreatePayment {
	if mmCreatePayment.mock.inspectFuncCreatePayment != nil {
		mmCreatePayment.mock.t.Fatalf("Inspect function is already set for OrderClientMock.CreatePayment")
	}

	mmCreatePayment.mock.inspectFuncCreatePayment = f

	return mmCreatePayment
}

// Return sets up results that will be returned by OrderClient.CreatePayment
func (mmCreatePayment *mOrderClientMockCreatePayment) Return(cp1 *mm_proto.CreatePaymentResp, err error) *OrderClientMock {
	if mmCreatePayment.mock.funcCreatePayment != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Set")
	}

	if mmCreatePayment.defaultExpectation == nil {
		mmCreatePayment.defaultExpectation = &OrderClientMockCreatePaymentExpectation{mock: mmCreatePayment.mock}
	}
	mmCreatePayment.defaultExpectation.results = &OrderClientMockCreatePaymentResults{cp1, err}
	mmCreatePayment.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreatePayment.mock
}

// Set uses given function f to mock the OrderClient.CreatePayment method
func (mmCreatePayment *mOrderClientMockCreatePayment) Set(f func(ctx context.Context, in *mm_proto.CreatePaymentReq, opts ...grpc.CallOption) (cp1 *mm_proto.CreatePaymentResp, err error)) *OrderClientMock {
	if mmCreatePayment.defaultExpectation != nil {
		mmCreatePayment.mock.t.Fatalf("Default expectation is already set for the OrderClient.CreatePayment method")
	}

	if len(mmCreatePayment.expectations) > 0 {
		mmCreatePayment.mock.t.Fatalf("Some expectations are already set for the OrderClient.CreatePayment method")
	}

	mmCreatePayment.mock.funcCreatePayment = f
	mmCreatePayment.mock.funcCreatePaymentOrigin = minimock.CallerInfo(1)
	return mmCreatePayment.mock
}

// When sets expectation for the OrderClient.CreatePayment which will trigger the result defined by the following
// Then helper
func (mmCreatePayment *mOrderClientMockCreatePayment) When(ctx context.Context, in *mm_proto.CreatePaymentReq, opts ...grpc.CallOption) *OrderClientMockCreatePaymentExpectation {
	if mmCreatePayment.mock.funcCreatePayment != nil {
		mmCreatePayment.mock.t.Fatalf("OrderClientMock.CreatePayment mock is already set by Set")
	}

	expectation := &OrderClientMockCreatePaymentExpectation{
		mock:               mmCreatePayment.mock,
		params:             &OrderClientMockCreatePaymentParams{ctx, in, opts},
		expectationOrigins: OrderClientMockCreatePaymentExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreatePayment.expectations = append(mmCreatePayment.expectations, expectation)
	return expectation
}

// Then sets up OrderClient.CreatePayment return parameters for the expectation previously defined by the When method
func (e *OrderClientMockCreatePaymentExpectation) Then(cp1 *mm_proto.CreatePaymentResp, err error) *OrderClientMock {
	e.results = &OrderClientMockCreatePaymentResults{cp1, err}
	return e.mock
}

// Times sets number of times OrderClient.CreatePayment should be invoked
func (mmCreatePayment *mOrderClientMockCreatePayment) Times(n uint64) *mOrderClientMockCreatePayment {
	if n == 0 {
		mmCreatePayment.mock.t.Fatalf("Times of OrderClientMock.CreatePayment mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreatePayment.expectedInvocations, n)
	mmCreatePayment.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreatePayment
}

func (mmCreatePayment *mOrderClientMockCreatePayment) invocationsDone() bool {
	if len(mmCreatePayment.expectations) == 0 && mmCreatePayment.defaultExpectation == nil && mmCreatePayment.mock.funcCreatePayment == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreatePayment.mock.afterCreatePaymentCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreatePayment.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreatePayment implements mm_proto.OrderClient
func (mmCreatePayment *OrderClientMock) CreatePayment(ctx context.Context, in *mm_proto.CreatePaymentReq, opts ...grpc.CallOption) (cp1 *mm_proto.CreatePaymentResp, err error) {
	mm_atomic.AddUint64(&mmCreatePayment.beforeCreatePaymentCounter, 1)
	defer mm_atomic.AddUint64(&mmCreatePayment.afterCreatePaymentCounter, 1)

	mmCreatePayment.t.Helper()

	if mmCreatePayment.inspectFuncCreatePayment != nil {
		mmCreatePayment.inspectFuncCreatePayment(ctx, in, opts...)
	}

	mm_params := OrderClientMockCreatePaymentParams{ctx, in, opts}

	// Record call args
	mmCreatePayment.CreatePaymentMock.mutex.Lock()
	mmCreatePayment.CreatePaymentMock.callArgs = append(mmCreatePayment.CreatePaymentMock.callArgs, &mm_params)
	mmCreatePayment.CreatePaymentMock.mutex.Unlock()

	for _, e := range mmCreatePayment.CreatePaymentMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmCreatePayment.CreatePaymentMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreatePayment.CreatePaymentMock.defaultExpectation.Counter, 1)
		mm_want := mmCreatePayment.CreatePaymentMock.defaultExpectation.params
		mm_want_ptrs := mmCreatePayment.CreatePaymentMock.defaultExpectation.paramPtrs

		mm_got := OrderClientMockCreatePaymentParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreatePayment.t.Errorf("OrderClientMock.CreatePayment got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePayment.CreatePaymentMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmCreatePayment.t.Errorf("OrderClientMock.CreatePayment got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePayment.CreatePaymentMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmCreatePayment.t.Errorf("OrderClientMock.CreatePayment got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreatePayment.CreatePaymentMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreatePayment.t.Errorf("OrderClientMock.CreatePayment got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreatePayment.CreatePaymentMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreatePayment.CreatePaymentMock.defaultExpectation.results
		if mm_results == nil {
			mmCreatePayment.t.Fatal("No results are set for the OrderClientMock.CreatePayment")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmCreatePayment.funcCreatePayment != nil {
		return mmCreatePayment.funcCreatePayment(ctx, in, opts...)
	}
	mmCreatePayment.t.Fatalf("Unexpected call to OrderClientMock.CreatePayment. %v %v %v", ctx, in, opts)
	return
}

// CreatePaymentAfterCounter returns a count of finished OrderClientMock.CreatePayment invocations
func (mmCreatePayment *OrderClientMock) CreatePaymentAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreatePayment.afterCreatePaymentCounter)
}

// CreatePaymentBeforeCounter returns a count of OrderClientMock.CreatePayment invocations
func (mmCreatePayment *OrderClientMock) CreatePaymentBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreatePayment.beforeCreatePaymentCounter)
}

// Calls returns a list of arguments used in each call to OrderClientMock.CreatePayment.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreatePayment *mOrderClientMockCreatePayment) Calls() []*OrderClientMockCreatePaymentParams {
	mmCreatePayment.mutex.RLock()

	argCopy := make([]*OrderClientMockCreatePaymentParams, len(mmCreatePayment.callArgs))
	copy(argCopy, mmCreatePayment.callArgs)

	mmCreatePayment.mutex.RUnlock()

	return argCopy
}

// MinimockCreatePaymentDone returns true if the count of the CreatePayment invocations corresponds
// the number of defined expectations
func (m *OrderClientMock) MinimockCreatePaymentDone() bool {
	if m.CreatePaymentMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreatePaymentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreatePaymentMock.invocationsDone()
}

// MinimockCreatePaymentInspect logs each unmet expectation
func (m *OrderClientMock) MinimockCreatePaymentInspect() {
	for _, e := range m.CreatePaymentMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderClientMock.CreatePayment at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreatePaymentCounter := mm_atomic.LoadUint64(&m.afterCreatePaymentCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreatePaymentMock.defaultExpectation != nil && afterCreatePaymentCounter < 1 {
		if m.CreatePaymentMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderClientMock.CreatePayment at\n%s", m.CreatePaymentMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderClientMock.CreatePayment at\n%s with params: %#v", m.CreatePaymentMock.defaultExpectation.expectationOrigins.origin, *m.CreatePaymentMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreatePayment != nil && afterCreatePaymentCounter < 1 {
		m.t.Errorf("Expected call to OrderClientMock.CreatePayment at\n%s", m.funcCreatePaymentOrigin)
	}

	if !m.CreatePaymentMock.invocationsDone() && afterCreatePaymentCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderClientMock.CreatePayment at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreatePaymentMock.expectedInvocations), m.CreatePaymentMock.expectedInvocationsOrigin, afterCreatePaymentCounter)
	}
}

type mOrderClientMockGetPreferredByUserUUID struct {
	optional           bool
	mock               *OrderClientMock
	defaultExpectation *OrderClientMockGetPreferredByUserUUIDExpectation
	expectations       []*OrderClientMockGetPreferredByUserUUIDExpectation

	callArgs []*OrderClientMockGetPreferredByUserUUIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderClientMockGetPreferredByUserUUIDExpectation specifies expectation struct of the OrderClient.GetPreferredByUserUUID
type OrderClientMockGetPreferredByUserUUIDExpectation struct {
	mock               *OrderClientMock
	params             *OrderClientMockGetPreferredByUserUUIDParams
	paramPtrs          *OrderClientMockGetPreferredByUserUUIDParamPtrs
	expectationOrigins OrderClientMockGetPreferredByUserUUIDExpectationOrigins
	results            *OrderClientMockGetPreferredByUserUUIDResults
	returnOrigin       string
	Counter            uint64
}

// OrderClientMockGetPreferredByUserUUIDParams contains parameters of the OrderClient.GetPreferredByUserUUID
type OrderClientMockGetPreferredByUserUUIDParams struct {
	ctx  context.Context
	in   *mm_proto.GetPreferredCardReq
	opts []grpc.CallOption
}

// OrderClientMockGetPreferredByUserUUIDParamPtrs contains pointers to parameters of the OrderClient.GetPreferredByUserUUID
type OrderClientMockGetPreferredByUserUUIDParamPtrs struct {
	ctx  *context.Context
	in   **mm_proto.GetPreferredCardReq
	opts *[]grpc.CallOption
}

// OrderClientMockGetPreferredByUserUUIDResults contains results of the OrderClient.GetPreferredByUserUUID
type OrderClientMockGetPreferredByUserUUIDResults struct {
	gp1 *mm_proto.GetPreferredCardResp
	err error
}

// OrderClientMockGetPreferredByUserUUIDOrigins contains origins of expectations of the OrderClient.GetPreferredByUserUUID
type OrderClientMockGetPreferredByUserUUIDExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) Optional() *mOrderClientMockGetPreferredByUserUUID {
	mmGetPreferredByUserUUID.optional = true
	return mmGetPreferredByUserUUID
}

// Expect sets up expected params for OrderClient.GetPreferredByUserUUID
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) Expect(ctx context.Context, in *mm_proto.GetPreferredCardReq, opts ...grpc.CallOption) *mOrderClientMockGetPreferredByUserUUID {
	if mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUID != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Set")
	}

	if mmGetPreferredByUserUUID.defaultExpectation == nil {
		mmGetPreferredByUserUUID.defaultExpectation = &OrderClientMockGetPreferredByUserUUIDExpectation{}
	}

	if mmGetPreferredByUserUUID.defaultExpectation.paramPtrs != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by ExpectParams functions")
	}

	mmGetPreferredByUserUUID.defaultExpectation.params = &OrderClientMockGetPreferredByUserUUIDParams{ctx, in, opts}
	mmGetPreferredByUserUUID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetPreferredByUserUUID.expectations {
		if minimock.Equal(e.params, mmGetPreferredByUserUUID.defaultExpectation.params) {
			mmGetPreferredByUserUUID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetPreferredByUserUUID.defaultExpectation.params)
		}
	}

	return mmGetPreferredByUserUUID
}

// ExpectCtxParam1 sets up expected param ctx for OrderClient.GetPreferredByUserUUID
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) ExpectCtxParam1(ctx context.Context) *mOrderClientMockGetPreferredByUserUUID {
	if mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUID != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Set")
	}

	if mmGetPreferredByUserUUID.defaultExpectation == nil {
		mmGetPreferredByUserUUID.defaultExpectation = &OrderClientMockGetPreferredByUserUUIDExpectation{}
	}

	if mmGetPreferredByUserUUID.defaultExpectation.params != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Expect")
	}

	if mmGetPreferredByUserUUID.defaultExpectation.paramPtrs == nil {
		mmGetPreferredByUserUUID.defaultExpectation.paramPtrs = &OrderClientMockGetPreferredByUserUUIDParamPtrs{}
	}
	mmGetPreferredByUserUUID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetPreferredByUserUUID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetPreferredByUserUUID
}

// ExpectInParam2 sets up expected param in for OrderClient.GetPreferredByUserUUID
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) ExpectInParam2(in *mm_proto.GetPreferredCardReq) *mOrderClientMockGetPreferredByUserUUID {
	if mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUID != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Set")
	}

	if mmGetPreferredByUserUUID.defaultExpectation == nil {
		mmGetPreferredByUserUUID.defaultExpectation = &OrderClientMockGetPreferredByUserUUIDExpectation{}
	}

	if mmGetPreferredByUserUUID.defaultExpectation.params != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Expect")
	}

	if mmGetPreferredByUserUUID.defaultExpectation.paramPtrs == nil {
		mmGetPreferredByUserUUID.defaultExpectation.paramPtrs = &OrderClientMockGetPreferredByUserUUIDParamPtrs{}
	}
	mmGetPreferredByUserUUID.defaultExpectation.paramPtrs.in = &in
	mmGetPreferredByUserUUID.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmGetPreferredByUserUUID
}

// ExpectOptsParam3 sets up expected param opts for OrderClient.GetPreferredByUserUUID
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) ExpectOptsParam3(opts ...grpc.CallOption) *mOrderClientMockGetPreferredByUserUUID {
	if mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUID != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Set")
	}

	if mmGetPreferredByUserUUID.defaultExpectation == nil {
		mmGetPreferredByUserUUID.defaultExpectation = &OrderClientMockGetPreferredByUserUUIDExpectation{}
	}

	if mmGetPreferredByUserUUID.defaultExpectation.params != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Expect")
	}

	if mmGetPreferredByUserUUID.defaultExpectation.paramPtrs == nil {
		mmGetPreferredByUserUUID.defaultExpectation.paramPtrs = &OrderClientMockGetPreferredByUserUUIDParamPtrs{}
	}
	mmGetPreferredByUserUUID.defaultExpectation.paramPtrs.opts = &opts
	mmGetPreferredByUserUUID.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmGetPreferredByUserUUID
}

// Inspect accepts an inspector function that has same arguments as the OrderClient.GetPreferredByUserUUID
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) Inspect(f func(ctx context.Context, in *mm_proto.GetPreferredCardReq, opts ...grpc.CallOption)) *mOrderClientMockGetPreferredByUserUUID {
	if mmGetPreferredByUserUUID.mock.inspectFuncGetPreferredByUserUUID != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("Inspect function is already set for OrderClientMock.GetPreferredByUserUUID")
	}

	mmGetPreferredByUserUUID.mock.inspectFuncGetPreferredByUserUUID = f

	return mmGetPreferredByUserUUID
}

// Return sets up results that will be returned by OrderClient.GetPreferredByUserUUID
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) Return(gp1 *mm_proto.GetPreferredCardResp, err error) *OrderClientMock {
	if mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUID != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Set")
	}

	if mmGetPreferredByUserUUID.defaultExpectation == nil {
		mmGetPreferredByUserUUID.defaultExpectation = &OrderClientMockGetPreferredByUserUUIDExpectation{mock: mmGetPreferredByUserUUID.mock}
	}
	mmGetPreferredByUserUUID.defaultExpectation.results = &OrderClientMockGetPreferredByUserUUIDResults{gp1, err}
	mmGetPreferredByUserUUID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetPreferredByUserUUID.mock
}

// Set uses given function f to mock the OrderClient.GetPreferredByUserUUID method
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) Set(f func(ctx context.Context, in *mm_proto.GetPreferredCardReq, opts ...grpc.CallOption) (gp1 *mm_proto.GetPreferredCardResp, err error)) *OrderClientMock {
	if mmGetPreferredByUserUUID.defaultExpectation != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("Default expectation is already set for the OrderClient.GetPreferredByUserUUID method")
	}

	if len(mmGetPreferredByUserUUID.expectations) > 0 {
		mmGetPreferredByUserUUID.mock.t.Fatalf("Some expectations are already set for the OrderClient.GetPreferredByUserUUID method")
	}

	mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUID = f
	mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUIDOrigin = minimock.CallerInfo(1)
	return mmGetPreferredByUserUUID.mock
}

// When sets expectation for the OrderClient.GetPreferredByUserUUID which will trigger the result defined by the following
// Then helper
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) When(ctx context.Context, in *mm_proto.GetPreferredCardReq, opts ...grpc.CallOption) *OrderClientMockGetPreferredByUserUUIDExpectation {
	if mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUID != nil {
		mmGetPreferredByUserUUID.mock.t.Fatalf("OrderClientMock.GetPreferredByUserUUID mock is already set by Set")
	}

	expectation := &OrderClientMockGetPreferredByUserUUIDExpectation{
		mock:               mmGetPreferredByUserUUID.mock,
		params:             &OrderClientMockGetPreferredByUserUUIDParams{ctx, in, opts},
		expectationOrigins: OrderClientMockGetPreferredByUserUUIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetPreferredByUserUUID.expectations = append(mmGetPreferredByUserUUID.expectations, expectation)
	return expectation
}

// Then sets up OrderClient.GetPreferredByUserUUID return parameters for the expectation previously defined by the When method
func (e *OrderClientMockGetPreferredByUserUUIDExpectation) Then(gp1 *mm_proto.GetPreferredCardResp, err error) *OrderClientMock {
	e.results = &OrderClientMockGetPreferredByUserUUIDResults{gp1, err}
	return e.mock
}

// Times sets number of times OrderClient.GetPreferredByUserUUID should be invoked
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) Times(n uint64) *mOrderClientMockGetPreferredByUserUUID {
	if n == 0 {
		mmGetPreferredByUserUUID.mock.t.Fatalf("Times of OrderClientMock.GetPreferredByUserUUID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetPreferredByUserUUID.expectedInvocations, n)
	mmGetPreferredByUserUUID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetPreferredByUserUUID
}

func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) invocationsDone() bool {
	if len(mmGetPreferredByUserUUID.expectations) == 0 && mmGetPreferredByUserUUID.defaultExpectation == nil && mmGetPreferredByUserUUID.mock.funcGetPreferredByUserUUID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetPreferredByUserUUID.mock.afterGetPreferredByUserUUIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetPreferredByUserUUID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetPreferredByUserUUID implements mm_proto.OrderClient
func (mmGetPreferredByUserUUID *OrderClientMock) GetPreferredByUserUUID(ctx context.Context, in *mm_proto.GetPreferredCardReq, opts ...grpc.CallOption) (gp1 *mm_proto.GetPreferredCardResp, err error) {
	mm_atomic.AddUint64(&mmGetPreferredByUserUUID.beforeGetPreferredByUserUUIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetPreferredByUserUUID.afterGetPreferredByUserUUIDCounter, 1)

	mmGetPreferredByUserUUID.t.Helper()

	if mmGetPreferredByUserUUID.inspectFuncGetPreferredByUserUUID != nil {
		mmGetPreferredByUserUUID.inspectFuncGetPreferredByUserUUID(ctx, in, opts...)
	}

	mm_params := OrderClientMockGetPreferredByUserUUIDParams{ctx, in, opts}

	// Record call args
	mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.mutex.Lock()
	mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.callArgs = append(mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.callArgs, &mm_params)
	mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.mutex.Unlock()

	for _, e := range mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.gp1, e.results.err
		}
	}

	if mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation.paramPtrs

		mm_got := OrderClientMockGetPreferredByUserUUIDParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetPreferredByUserUUID.t.Errorf("OrderClientMock.GetPreferredByUserUUID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmGetPreferredByUserUUID.t.Errorf("OrderClientMock.GetPreferredByUserUUID got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmGetPreferredByUserUUID.t.Errorf("OrderClientMock.GetPreferredByUserUUID got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetPreferredByUserUUID.t.Errorf("OrderClientMock.GetPreferredByUserUUID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetPreferredByUserUUID.GetPreferredByUserUUIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetPreferredByUserUUID.t.Fatal("No results are set for the OrderClientMock.GetPreferredByUserUUID")
		}
		return (*mm_results).gp1, (*mm_results).err
	}
	if mmGetPreferredByUserUUID.funcGetPreferredByUserUUID != nil {
		return mmGetPreferredByUserUUID.funcGetPreferredByUserUUID(ctx, in, opts...)
	}
	mmGetPreferredByUserUUID.t.Fatalf("Unexpected call to OrderClientMock.GetPreferredByUserUUID. %v %v %v", ctx, in, opts)
	return
}

// GetPreferredByUserUUIDAfterCounter returns a count of finished OrderClientMock.GetPreferredByUserUUID invocations
func (mmGetPreferredByUserUUID *OrderClientMock) GetPreferredByUserUUIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPreferredByUserUUID.afterGetPreferredByUserUUIDCounter)
}

// GetPreferredByUserUUIDBeforeCounter returns a count of OrderClientMock.GetPreferredByUserUUID invocations
func (mmGetPreferredByUserUUID *OrderClientMock) GetPreferredByUserUUIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetPreferredByUserUUID.beforeGetPreferredByUserUUIDCounter)
}

// Calls returns a list of arguments used in each call to OrderClientMock.GetPreferredByUserUUID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetPreferredByUserUUID *mOrderClientMockGetPreferredByUserUUID) Calls() []*OrderClientMockGetPreferredByUserUUIDParams {
	mmGetPreferredByUserUUID.mutex.RLock()

	argCopy := make([]*OrderClientMockGetPreferredByUserUUIDParams, len(mmGetPreferredByUserUUID.callArgs))
	copy(argCopy, mmGetPreferredByUserUUID.callArgs)

	mmGetPreferredByUserUUID.mutex.RUnlock()

	return argCopy
}

// MinimockGetPreferredByUserUUIDDone returns true if the count of the GetPreferredByUserUUID invocations corresponds
// the number of defined expectations
func (m *OrderClientMock) MinimockGetPreferredByUserUUIDDone() bool {
	if m.GetPreferredByUserUUIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetPreferredByUserUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetPreferredByUserUUIDMock.invocationsDone()
}

// MinimockGetPreferredByUserUUIDInspect logs each unmet expectation
func (m *OrderClientMock) MinimockGetPreferredByUserUUIDInspect() {
	for _, e := range m.GetPreferredByUserUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderClientMock.GetPreferredByUserUUID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetPreferredByUserUUIDCounter := mm_atomic.LoadUint64(&m.afterGetPreferredByUserUUIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetPreferredByUserUUIDMock.defaultExpectation != nil && afterGetPreferredByUserUUIDCounter < 1 {
		if m.GetPreferredByUserUUIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderClientMock.GetPreferredByUserUUID at\n%s", m.GetPreferredByUserUUIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderClientMock.GetPreferredByUserUUID at\n%s with params: %#v", m.GetPreferredByUserUUIDMock.defaultExpectation.expectationOrigins.origin, *m.GetPreferredByUserUUIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetPreferredByUserUUID != nil && afterGetPreferredByUserUUIDCounter < 1 {
		m.t.Errorf("Expected call to OrderClientMock.GetPreferredByUserUUID at\n%s", m.funcGetPreferredByUserUUIDOrigin)
	}

	if !m.GetPreferredByUserUUIDMock.invocationsDone() && afterGetPreferredByUserUUIDCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderClientMock.GetPreferredByUserUUID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetPreferredByUserUUIDMock.expectedInvocations), m.GetPreferredByUserUUIDMock.expectedInvocationsOrigin, afterGetPreferredByUserUUIDCounter)
	}
}

type mOrderClientMockSaveCard struct {
	optional           bool
	mock               *OrderClientMock
	defaultExpectation *OrderClientMockSaveCardExpectation
	expectations       []*OrderClientMockSaveCardExpectation

	callArgs []*OrderClientMockSaveCardParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderClientMockSaveCardExpectation specifies expectation struct of the OrderClient.SaveCard
type OrderClientMockSaveCardExpectation struct {
	mock               *OrderClientMock
	params             *OrderClientMockSaveCardParams
	paramPtrs          *OrderClientMockSaveCardParamPtrs
	expectationOrigins OrderClientMockSaveCardExpectationOrigins
	results            *OrderClientMockSaveCardResults
	returnOrigin       string
	Counter            uint64
}

// OrderClientMockSaveCardParams contains parameters of the OrderClient.SaveCard
type OrderClientMockSaveCardParams struct {
	ctx  context.Context
	in   *mm_proto.SaveCardReq
	opts []grpc.CallOption
}

// OrderClientMockSaveCardParamPtrs contains pointers to parameters of the OrderClient.SaveCard
type OrderClientMockSaveCardParamPtrs struct {
	ctx  *context.Context
	in   **mm_proto.SaveCardReq
	opts *[]grpc.CallOption
}

// OrderClientMockSaveCardResults contains results of the OrderClient.SaveCard
type OrderClientMockSaveCardResults struct {
	sp1 *mm_proto.SaveCardResp
	err error
}

// OrderClientMockSaveCardOrigins contains origins of expectations of the OrderClient.SaveCard
type OrderClientMockSaveCardExpectationOrigins struct {
	origin     string
	originCtx  string
	originIn   string
	originOpts string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveCard *mOrderClientMockSaveCard) Optional() *mOrderClientMockSaveCard {
	mmSaveCard.optional = true
	return mmSaveCard
}

// Expect sets up expected params for OrderClient.SaveCard
func (mmSaveCard *mOrderClientMockSaveCard) Expect(ctx context.Context, in *mm_proto.SaveCardReq, opts ...grpc.CallOption) *mOrderClientMockSaveCard {
	if mmSaveCard.mock.funcSaveCard != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Set")
	}

	if mmSaveCard.defaultExpectation == nil {
		mmSaveCard.defaultExpectation = &OrderClientMockSaveCardExpectation{}
	}

	if mmSaveCard.defaultExpectation.paramPtrs != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by ExpectParams functions")
	}

	mmSaveCard.defaultExpectation.params = &OrderClientMockSaveCardParams{ctx, in, opts}
	mmSaveCard.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveCard.expectations {
		if minimock.Equal(e.params, mmSaveCard.defaultExpectation.params) {
			mmSaveCard.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveCard.defaultExpectation.params)
		}
	}

	return mmSaveCard
}

// ExpectCtxParam1 sets up expected param ctx for OrderClient.SaveCard
func (mmSaveCard *mOrderClientMockSaveCard) ExpectCtxParam1(ctx context.Context) *mOrderClientMockSaveCard {
	if mmSaveCard.mock.funcSaveCard != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Set")
	}

	if mmSaveCard.defaultExpectation == nil {
		mmSaveCard.defaultExpectation = &OrderClientMockSaveCardExpectation{}
	}

	if mmSaveCard.defaultExpectation.params != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Expect")
	}

	if mmSaveCard.defaultExpectation.paramPtrs == nil {
		mmSaveCard.defaultExpectation.paramPtrs = &OrderClientMockSaveCardParamPtrs{}
	}
	mmSaveCard.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveCard.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveCard
}

// ExpectInParam2 sets up expected param in for OrderClient.SaveCard
func (mmSaveCard *mOrderClientMockSaveCard) ExpectInParam2(in *mm_proto.SaveCardReq) *mOrderClientMockSaveCard {
	if mmSaveCard.mock.funcSaveCard != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Set")
	}

	if mmSaveCard.defaultExpectation == nil {
		mmSaveCard.defaultExpectation = &OrderClientMockSaveCardExpectation{}
	}

	if mmSaveCard.defaultExpectation.params != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Expect")
	}

	if mmSaveCard.defaultExpectation.paramPtrs == nil {
		mmSaveCard.defaultExpectation.paramPtrs = &OrderClientMockSaveCardParamPtrs{}
	}
	mmSaveCard.defaultExpectation.paramPtrs.in = &in
	mmSaveCard.defaultExpectation.expectationOrigins.originIn = minimock.CallerInfo(1)

	return mmSaveCard
}

// ExpectOptsParam3 sets up expected param opts for OrderClient.SaveCard
func (mmSaveCard *mOrderClientMockSaveCard) ExpectOptsParam3(opts ...grpc.CallOption) *mOrderClientMockSaveCard {
	if mmSaveCard.mock.funcSaveCard != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Set")
	}

	if mmSaveCard.defaultExpectation == nil {
		mmSaveCard.defaultExpectation = &OrderClientMockSaveCardExpectation{}
	}

	if mmSaveCard.defaultExpectation.params != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Expect")
	}

	if mmSaveCard.defaultExpectation.paramPtrs == nil {
		mmSaveCard.defaultExpectation.paramPtrs = &OrderClientMockSaveCardParamPtrs{}
	}
	mmSaveCard.defaultExpectation.paramPtrs.opts = &opts
	mmSaveCard.defaultExpectation.expectationOrigins.originOpts = minimock.CallerInfo(1)

	return mmSaveCard
}

// Inspect accepts an inspector function that has same arguments as the OrderClient.SaveCard
func (mmSaveCard *mOrderClientMockSaveCard) Inspect(f func(ctx context.Context, in *mm_proto.SaveCardReq, opts ...grpc.CallOption)) *mOrderClientMockSaveCard {
	if mmSaveCard.mock.inspectFuncSaveCard != nil {
		mmSaveCard.mock.t.Fatalf("Inspect function is already set for OrderClientMock.SaveCard")
	}

	mmSaveCard.mock.inspectFuncSaveCard = f

	return mmSaveCard
}

// Return sets up results that will be returned by OrderClient.SaveCard
func (mmSaveCard *mOrderClientMockSaveCard) Return(sp1 *mm_proto.SaveCardResp, err error) *OrderClientMock {
	if mmSaveCard.mock.funcSaveCard != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Set")
	}

	if mmSaveCard.defaultExpectation == nil {
		mmSaveCard.defaultExpectation = &OrderClientMockSaveCardExpectation{mock: mmSaveCard.mock}
	}
	mmSaveCard.defaultExpectation.results = &OrderClientMockSaveCardResults{sp1, err}
	mmSaveCard.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveCard.mock
}

// Set uses given function f to mock the OrderClient.SaveCard method
func (mmSaveCard *mOrderClientMockSaveCard) Set(f func(ctx context.Context, in *mm_proto.SaveCardReq, opts ...grpc.CallOption) (sp1 *mm_proto.SaveCardResp, err error)) *OrderClientMock {
	if mmSaveCard.defaultExpectation != nil {
		mmSaveCard.mock.t.Fatalf("Default expectation is already set for the OrderClient.SaveCard method")
	}

	if len(mmSaveCard.expectations) > 0 {
		mmSaveCard.mock.t.Fatalf("Some expectations are already set for the OrderClient.SaveCard method")
	}

	mmSaveCard.mock.funcSaveCard = f
	mmSaveCard.mock.funcSaveCardOrigin = minimock.CallerInfo(1)
	return mmSaveCard.mock
}

// When sets expectation for the OrderClient.SaveCard which will trigger the result defined by the following
// Then helper
func (mmSaveCard *mOrderClientMockSaveCard) When(ctx context.Context, in *mm_proto.SaveCardReq, opts ...grpc.CallOption) *OrderClientMockSaveCardExpectation {
	if mmSaveCard.mock.funcSaveCard != nil {
		mmSaveCard.mock.t.Fatalf("OrderClientMock.SaveCard mock is already set by Set")
	}

	expectation := &OrderClientMockSaveCardExpectation{
		mock:               mmSaveCard.mock,
		params:             &OrderClientMockSaveCardParams{ctx, in, opts},
		expectationOrigins: OrderClientMockSaveCardExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveCard.expectations = append(mmSaveCard.expectations, expectation)
	return expectation
}

// Then sets up OrderClient.SaveCard return parameters for the expectation previously defined by the When method
func (e *OrderClientMockSaveCardExpectation) Then(sp1 *mm_proto.SaveCardResp, err error) *OrderClientMock {
	e.results = &OrderClientMockSaveCardResults{sp1, err}
	return e.mock
}

// Times sets number of times OrderClient.SaveCard should be invoked
func (mmSaveCard *mOrderClientMockSaveCard) Times(n uint64) *mOrderClientMockSaveCard {
	if n == 0 {
		mmSaveCard.mock.t.Fatalf("Times of OrderClientMock.SaveCard mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveCard.expectedInvocations, n)
	mmSaveCard.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveCard
}

func (mmSaveCard *mOrderClientMockSaveCard) invocationsDone() bool {
	if len(mmSaveCard.expectations) == 0 && mmSaveCard.defaultExpectation == nil && mmSaveCard.mock.funcSaveCard == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveCard.mock.afterSaveCardCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveCard.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveCard implements mm_proto.OrderClient
func (mmSaveCard *OrderClientMock) SaveCard(ctx context.Context, in *mm_proto.SaveCardReq, opts ...grpc.CallOption) (sp1 *mm_proto.SaveCardResp, err error) {
	mm_atomic.AddUint64(&mmSaveCard.beforeSaveCardCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveCard.afterSaveCardCounter, 1)

	mmSaveCard.t.Helper()

	if mmSaveCard.inspectFuncSaveCard != nil {
		mmSaveCard.inspectFuncSaveCard(ctx, in, opts...)
	}

	mm_params := OrderClientMockSaveCardParams{ctx, in, opts}

	// Record call args
	mmSaveCard.SaveCardMock.mutex.Lock()
	mmSaveCard.SaveCardMock.callArgs = append(mmSaveCard.SaveCardMock.callArgs, &mm_params)
	mmSaveCard.SaveCardMock.mutex.Unlock()

	for _, e := range mmSaveCard.SaveCardMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmSaveCard.SaveCardMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveCard.SaveCardMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveCard.SaveCardMock.defaultExpectation.params
		mm_want_ptrs := mmSaveCard.SaveCardMock.defaultExpectation.paramPtrs

		mm_got := OrderClientMockSaveCardParams{ctx, in, opts}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveCard.t.Errorf("OrderClientMock.SaveCard got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveCard.SaveCardMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.in != nil && !minimock.Equal(*mm_want_ptrs.in, mm_got.in) {
				mmSaveCard.t.Errorf("OrderClientMock.SaveCard got unexpected parameter in, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveCard.SaveCardMock.defaultExpectation.expectationOrigins.originIn, *mm_want_ptrs.in, mm_got.in, minimock.Diff(*mm_want_ptrs.in, mm_got.in))
			}

			if mm_want_ptrs.opts != nil && !minimock.Equal(*mm_want_ptrs.opts, mm_got.opts) {
				mmSaveCard.t.Errorf("OrderClientMock.SaveCard got unexpected parameter opts, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveCard.SaveCardMock.defaultExpectation.expectationOrigins.originOpts, *mm_want_ptrs.opts, mm_got.opts, minimock.Diff(*mm_want_ptrs.opts, mm_got.opts))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveCard.t.Errorf("OrderClientMock.SaveCard got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveCard.SaveCardMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveCard.SaveCardMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveCard.t.Fatal("No results are set for the OrderClientMock.SaveCard")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmSaveCard.funcSaveCard != nil {
		return mmSaveCard.funcSaveCard(ctx, in, opts...)
	}
	mmSaveCard.t.Fatalf("Unexpected call to OrderClientMock.SaveCard. %v %v %v", ctx, in, opts)
	return
}

// SaveCardAfterCounter returns a count of finished OrderClientMock.SaveCard invocations
func (mmSaveCard *OrderClientMock) SaveCardAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveCard.afterSaveCardCounter)
}

// SaveCardBeforeCounter returns a count of OrderClientMock.SaveCard invocations
func (mmSaveCard *OrderClientMock) SaveCardBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveCard.beforeSaveCardCounter)
}

// Calls returns a list of arguments used in each call to OrderClientMock.SaveCard.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveCard *mOrderClientMockSaveCard) Calls() []*OrderClientMockSaveCardParams {
	mmSaveCard.mutex.RLock()

	argCopy := make([]*OrderClientMockSaveCardParams, len(mmSaveCard.callArgs))
	copy(argCopy, mmSaveCard.callArgs)

	mmSaveCard.mutex.RUnlock()

	return argCopy
}

// MinimockSaveCardDone returns true if the count of the SaveCard invocations corresponds
// the number of defined expectations
func (m *OrderClientMock) MinimockSaveCardDone() bool {
	if m.SaveCardMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveCardMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveCardMock.invocationsDone()
}

// MinimockSaveCardInspect logs each unmet expectation
func (m *OrderClientMock) MinimockSaveCardInspect() {
	for _, e := range m.SaveCardMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderClientMock.SaveCard at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveCardCounter := mm_atomic.LoadUint64(&m.afterSaveCardCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveCardMock.defaultExpectation != nil && afterSaveCardCounter < 1 {
		if m.SaveCardMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderClientMock.SaveCard at\n%s", m.SaveCardMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderClientMock.SaveCard at\n%s with params: %#v", m.SaveCardMock.defaultExpectation.expectationOrigins.origin, *m.SaveCardMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveCard != nil && afterSaveCardCounter < 1 {
		m.t.Errorf("Expected call to OrderClientMock.SaveCard at\n%s", m.funcSaveCardOrigin)
	}

	if !m.SaveCardMock.invocationsDone() && afterSaveCardCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderClientMock.SaveCard at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveCardMock.expectedInvocations), m.SaveCardMock.expectedInvocationsOrigin, afterSaveCardCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreatePaymentInspect()

			m.MinimockGetPreferredByUserUUIDInspect()

			m.MinimockSaveCardInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreatePaymentDone() &&
		m.MinimockGetPreferredByUserUUIDDone() &&
		m.MinimockSaveCardDone()
}
