// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i k071123/internal/services/parking_service/domain/repositories.ParkingRepository -o parking_repository_mock_test.go -n ParkingRepositoryMock -p mocks

import (
	"k071123/internal/services/parking_service/domain/models"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ParkingRepositoryMock implements mm_repositories.ParkingRepository
type ParkingRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(model *models.Parking) (err error)
	funcAddOrigin    string
	inspectFuncAdd   func(model *models.Parking)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mParkingRepositoryMockAdd

	funcGetByUUID          func(uuid string) (pp1 *models.Parking, err error)
	funcGetByUUIDOrigin    string
	inspectFuncGetByUUID   func(uuid string)
	afterGetByUUIDCounter  uint64
	beforeGetByUUIDCounter uint64
	GetByUUIDMock          mParkingRepositoryMockGetByUUID
}

// NewParkingRepositoryMock returns a mock for mm_repositories.ParkingRepository
func NewParkingRepositoryMock(t minimock.Tester) *ParkingRepositoryMock {
	m := &ParkingRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mParkingRepositoryMockAdd{mock: m}
	m.AddMock.callArgs = []*ParkingRepositoryMockAddParams{}

	m.GetByUUIDMock = mParkingRepositoryMockGetByUUID{mock: m}
	m.GetByUUIDMock.callArgs = []*ParkingRepositoryMockGetByUUIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mParkingRepositoryMockAdd struct {
	optional           bool
	mock               *ParkingRepositoryMock
	defaultExpectation *ParkingRepositoryMockAddExpectation
	expectations       []*ParkingRepositoryMockAddExpectation

	callArgs []*ParkingRepositoryMockAddParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ParkingRepositoryMockAddExpectation specifies expectation struct of the ParkingRepository.Add
type ParkingRepositoryMockAddExpectation struct {
	mock               *ParkingRepositoryMock
	params             *ParkingRepositoryMockAddParams
	paramPtrs          *ParkingRepositoryMockAddParamPtrs
	expectationOrigins ParkingRepositoryMockAddExpectationOrigins
	results            *ParkingRepositoryMockAddResults
	returnOrigin       string
	Counter            uint64
}

// ParkingRepositoryMockAddParams contains parameters of the ParkingRepository.Add
type ParkingRepositoryMockAddParams struct {
	model *models.Parking
}

// ParkingRepositoryMockAddParamPtrs contains pointers to parameters of the ParkingRepository.Add
type ParkingRepositoryMockAddParamPtrs struct {
	model **models.Parking
}

// ParkingRepositoryMockAddResults contains results of the ParkingRepository.Add
type ParkingRepositoryMockAddResults struct {
	err error
}

// ParkingRepositoryMockAddOrigins contains origins of expectations of the ParkingRepository.Add
type ParkingRepositoryMockAddExpectationOrigins struct {
	origin      string
	originModel string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAdd *mParkingRepositoryMockAdd) Optional() *mParkingRepositoryMockAdd {
	mmAdd.optional = true
	return mmAdd
}

// Expect sets up expected params for ParkingRepository.Add
func (mmAdd *mParkingRepositoryMockAdd) Expect(model *models.Parking) *mParkingRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ParkingRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &ParkingRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.paramPtrs != nil {
		mmAdd.mock.t.Fatalf("ParkingRepositoryMock.Add mock is already set by ExpectParams functions")
	}

	mmAdd.defaultExpectation.params = &ParkingRepositoryMockAddParams{model}
	mmAdd.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// ExpectModelParam1 sets up expected param model for ParkingRepository.Add
func (mmAdd *mParkingRepositoryMockAdd) ExpectModelParam1(model *models.Parking) *mParkingRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ParkingRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &ParkingRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("ParkingRepositoryMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &ParkingRepositoryMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.model = &model
	mmAdd.defaultExpectation.expectationOrigins.originModel = minimock.CallerInfo(1)

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the ParkingRepository.Add
func (mmAdd *mParkingRepositoryMockAdd) Inspect(f func(model *models.Parking)) *mParkingRepositoryMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for ParkingRepositoryMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by ParkingRepository.Add
func (mmAdd *mParkingRepositoryMockAdd) Return(err error) *ParkingRepositoryMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ParkingRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &ParkingRepositoryMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &ParkingRepositoryMockAddResults{err}
	mmAdd.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// Set uses given function f to mock the ParkingRepository.Add method
func (mmAdd *mParkingRepositoryMockAdd) Set(f func(model *models.Parking) (err error)) *ParkingRepositoryMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the ParkingRepository.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the ParkingRepository.Add method")
	}

	mmAdd.mock.funcAdd = f
	mmAdd.mock.funcAddOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// When sets expectation for the ParkingRepository.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mParkingRepositoryMockAdd) When(model *models.Parking) *ParkingRepositoryMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("ParkingRepositoryMock.Add mock is already set by Set")
	}

	expectation := &ParkingRepositoryMockAddExpectation{
		mock:               mmAdd.mock,
		params:             &ParkingRepositoryMockAddParams{model},
		expectationOrigins: ParkingRepositoryMockAddExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up ParkingRepository.Add return parameters for the expectation previously defined by the When method
func (e *ParkingRepositoryMockAddExpectation) Then(err error) *ParkingRepositoryMock {
	e.results = &ParkingRepositoryMockAddResults{err}
	return e.mock
}

// Times sets number of times ParkingRepository.Add should be invoked
func (mmAdd *mParkingRepositoryMockAdd) Times(n uint64) *mParkingRepositoryMockAdd {
	if n == 0 {
		mmAdd.mock.t.Fatalf("Times of ParkingRepositoryMock.Add mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAdd.expectedInvocations, n)
	mmAdd.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAdd
}

func (mmAdd *mParkingRepositoryMockAdd) invocationsDone() bool {
	if len(mmAdd.expectations) == 0 && mmAdd.defaultExpectation == nil && mmAdd.mock.funcAdd == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAdd.mock.afterAddCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAdd.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Add implements mm_repositories.ParkingRepository
func (mmAdd *ParkingRepositoryMock) Add(model *models.Parking) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	mmAdd.t.Helper()

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(model)
	}

	mm_params := ParkingRepositoryMockAddParams{model}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_want_ptrs := mmAdd.AddMock.defaultExpectation.paramPtrs

		mm_got := ParkingRepositoryMockAddParams{model}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.model != nil && !minimock.Equal(*mm_want_ptrs.model, mm_got.model) {
				mmAdd.t.Errorf("ParkingRepositoryMock.Add got unexpected parameter model, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originModel, *mm_want_ptrs.model, mm_got.model, minimock.Diff(*mm_want_ptrs.model, mm_got.model))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("ParkingRepositoryMock.Add got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAdd.AddMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results == nil {
			mmAdd.t.Fatal("No results are set for the ParkingRepositoryMock.Add")
		}
		return (*mm_results).err
	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(model)
	}
	mmAdd.t.Fatalf("Unexpected call to ParkingRepositoryMock.Add. %v", model)
	return
}

// AddAfterCounter returns a count of finished ParkingRepositoryMock.Add invocations
func (mmAdd *ParkingRepositoryMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of ParkingRepositoryMock.Add invocations
func (mmAdd *ParkingRepositoryMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to ParkingRepositoryMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mParkingRepositoryMockAdd) Calls() []*ParkingRepositoryMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*ParkingRepositoryMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *ParkingRepositoryMock) MinimockAddDone() bool {
	if m.AddMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddMock.invocationsDone()
}

// MinimockAddInspect logs each unmet expectation
func (m *ParkingRepositoryMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ParkingRepositoryMock.Add at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddCounter := mm_atomic.LoadUint64(&m.afterAddCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && afterAddCounter < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ParkingRepositoryMock.Add at\n%s", m.AddMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ParkingRepositoryMock.Add at\n%s with params: %#v", m.AddMock.defaultExpectation.expectationOrigins.origin, *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && afterAddCounter < 1 {
		m.t.Errorf("Expected call to ParkingRepositoryMock.Add at\n%s", m.funcAddOrigin)
	}

	if !m.AddMock.invocationsDone() && afterAddCounter > 0 {
		m.t.Errorf("Expected %d calls to ParkingRepositoryMock.Add at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddMock.expectedInvocations), m.AddMock.expectedInvocationsOrigin, afterAddCounter)
	}
}

type mParkingRepositoryMockGetByUUID struct {
	optional           bool
	mock               *ParkingRepositoryMock
	defaultExpectation *ParkingRepositoryMockGetByUUIDExpectation
	expectations       []*ParkingRepositoryMockGetByUUIDExpectation

	callArgs []*ParkingRepositoryMockGetByUUIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ParkingRepositoryMockGetByUUIDExpectation specifies expectation struct of the ParkingRepository.GetByUUID
type ParkingRepositoryMockGetByUUIDExpectation struct {
	mock               *ParkingRepositoryMock
	params             *ParkingRepositoryMockGetByUUIDParams
	paramPtrs          *ParkingRepositoryMockGetByUUIDParamPtrs
	expectationOrigins ParkingRepositoryMockGetByUUIDExpectationOrigins
	results            *ParkingRepositoryMockGetByUUIDResults
	returnOrigin       string
	Counter            uint64
}

// ParkingRepositoryMockGetByUUIDParams contains parameters of the ParkingRepository.GetByUUID
type ParkingRepositoryMockGetByUUIDParams struct {
	uuid string
}

// ParkingRepositoryMockGetByUUIDParamPtrs contains pointers to parameters of the ParkingRepository.GetByUUID
type ParkingRepositoryMockGetByUUIDParamPtrs struct {
	uuid *string
}

// ParkingRepositoryMockGetByUUIDResults contains results of the ParkingRepository.GetByUUID
type ParkingRepositoryMockGetByUUIDResults struct {
	pp1 *models.Parking
	err error
}

// ParkingRepositoryMockGetByUUIDOrigins contains origins of expectations of the ParkingRepository.GetByUUID
type ParkingRepositoryMockGetByUUIDExpectationOrigins struct {
	origin     string
	originUuid string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) Optional() *mParkingRepositoryMockGetByUUID {
	mmGetByUUID.optional = true
	return mmGetByUUID
}

// Expect sets up expected params for ParkingRepository.GetByUUID
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) Expect(uuid string) *mParkingRepositoryMockGetByUUID {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("ParkingRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &ParkingRepositoryMockGetByUUIDExpectation{}
	}

	if mmGetByUUID.defaultExpectation.paramPtrs != nil {
		mmGetByUUID.mock.t.Fatalf("ParkingRepositoryMock.GetByUUID mock is already set by ExpectParams functions")
	}

	mmGetByUUID.defaultExpectation.params = &ParkingRepositoryMockGetByUUIDParams{uuid}
	mmGetByUUID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByUUID.expectations {
		if minimock.Equal(e.params, mmGetByUUID.defaultExpectation.params) {
			mmGetByUUID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByUUID.defaultExpectation.params)
		}
	}

	return mmGetByUUID
}

// ExpectUuidParam1 sets up expected param uuid for ParkingRepository.GetByUUID
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) ExpectUuidParam1(uuid string) *mParkingRepositoryMockGetByUUID {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("ParkingRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &ParkingRepositoryMockGetByUUIDExpectation{}
	}

	if mmGetByUUID.defaultExpectation.params != nil {
		mmGetByUUID.mock.t.Fatalf("ParkingRepositoryMock.GetByUUID mock is already set by Expect")
	}

	if mmGetByUUID.defaultExpectation.paramPtrs == nil {
		mmGetByUUID.defaultExpectation.paramPtrs = &ParkingRepositoryMockGetByUUIDParamPtrs{}
	}
	mmGetByUUID.defaultExpectation.paramPtrs.uuid = &uuid
	mmGetByUUID.defaultExpectation.expectationOrigins.originUuid = minimock.CallerInfo(1)

	return mmGetByUUID
}

// Inspect accepts an inspector function that has same arguments as the ParkingRepository.GetByUUID
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) Inspect(f func(uuid string)) *mParkingRepositoryMockGetByUUID {
	if mmGetByUUID.mock.inspectFuncGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("Inspect function is already set for ParkingRepositoryMock.GetByUUID")
	}

	mmGetByUUID.mock.inspectFuncGetByUUID = f

	return mmGetByUUID
}

// Return sets up results that will be returned by ParkingRepository.GetByUUID
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) Return(pp1 *models.Parking, err error) *ParkingRepositoryMock {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("ParkingRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &ParkingRepositoryMockGetByUUIDExpectation{mock: mmGetByUUID.mock}
	}
	mmGetByUUID.defaultExpectation.results = &ParkingRepositoryMockGetByUUIDResults{pp1, err}
	mmGetByUUID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByUUID.mock
}

// Set uses given function f to mock the ParkingRepository.GetByUUID method
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) Set(f func(uuid string) (pp1 *models.Parking, err error)) *ParkingRepositoryMock {
	if mmGetByUUID.defaultExpectation != nil {
		mmGetByUUID.mock.t.Fatalf("Default expectation is already set for the ParkingRepository.GetByUUID method")
	}

	if len(mmGetByUUID.expectations) > 0 {
		mmGetByUUID.mock.t.Fatalf("Some expectations are already set for the ParkingRepository.GetByUUID method")
	}

	mmGetByUUID.mock.funcGetByUUID = f
	mmGetByUUID.mock.funcGetByUUIDOrigin = minimock.CallerInfo(1)
	return mmGetByUUID.mock
}

// When sets expectation for the ParkingRepository.GetByUUID which will trigger the result defined by the following
// Then helper
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) When(uuid string) *ParkingRepositoryMockGetByUUIDExpectation {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("ParkingRepositoryMock.GetByUUID mock is already set by Set")
	}

	expectation := &ParkingRepositoryMockGetByUUIDExpectation{
		mock:               mmGetByUUID.mock,
		params:             &ParkingRepositoryMockGetByUUIDParams{uuid},
		expectationOrigins: ParkingRepositoryMockGetByUUIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByUUID.expectations = append(mmGetByUUID.expectations, expectation)
	return expectation
}

// Then sets up ParkingRepository.GetByUUID return parameters for the expectation previously defined by the When method
func (e *ParkingRepositoryMockGetByUUIDExpectation) Then(pp1 *models.Parking, err error) *ParkingRepositoryMock {
	e.results = &ParkingRepositoryMockGetByUUIDResults{pp1, err}
	return e.mock
}

// Times sets number of times ParkingRepository.GetByUUID should be invoked
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) Times(n uint64) *mParkingRepositoryMockGetByUUID {
	if n == 0 {
		mmGetByUUID.mock.t.Fatalf("Times of ParkingRepositoryMock.GetByUUID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByUUID.expectedInvocations, n)
	mmGetByUUID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByUUID
}

func (mmGetByUUID *mParkingRepositoryMockGetByUUID) invocationsDone() bool {
	if len(mmGetByUUID.expectations) == 0 && mmGetByUUID.defaultExpectation == nil && mmGetByUUID.mock.funcGetByUUID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByUUID.mock.afterGetByUUIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByUUID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByUUID implements mm_repositories.ParkingRepository
func (mmGetByUUID *ParkingRepositoryMock) GetByUUID(uuid string) (pp1 *models.Parking, err error) {
	mm_atomic.AddUint64(&mmGetByUUID.beforeGetByUUIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByUUID.afterGetByUUIDCounter, 1)

	mmGetByUUID.t.Helper()

	if mmGetByUUID.inspectFuncGetByUUID != nil {
		mmGetByUUID.inspectFuncGetByUUID(uuid)
	}

	mm_params := ParkingRepositoryMockGetByUUIDParams{uuid}

	// Record call args
	mmGetByUUID.GetByUUIDMock.mutex.Lock()
	mmGetByUUID.GetByUUIDMock.callArgs = append(mmGetByUUID.GetByUUIDMock.callArgs, &mm_params)
	mmGetByUUID.GetByUUIDMock.mutex.Unlock()

	for _, e := range mmGetByUUID.GetByUUIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pp1, e.results.err
		}
	}

	if mmGetByUUID.GetByUUIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByUUID.GetByUUIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByUUID.GetByUUIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByUUID.GetByUUIDMock.defaultExpectation.paramPtrs

		mm_got := ParkingRepositoryMockGetByUUIDParams{uuid}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.uuid != nil && !minimock.Equal(*mm_want_ptrs.uuid, mm_got.uuid) {
				mmGetByUUID.t.Errorf("ParkingRepositoryMock.GetByUUID got unexpected parameter uuid, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByUUID.GetByUUIDMock.defaultExpectation.expectationOrigins.originUuid, *mm_want_ptrs.uuid, mm_got.uuid, minimock.Diff(*mm_want_ptrs.uuid, mm_got.uuid))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByUUID.t.Errorf("ParkingRepositoryMock.GetByUUID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByUUID.GetByUUIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByUUID.GetByUUIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByUUID.t.Fatal("No results are set for the ParkingRepositoryMock.GetByUUID")
		}
		return (*mm_results).pp1, (*mm_results).err
	}
	if mmGetByUUID.funcGetByUUID != nil {
		return mmGetByUUID.funcGetByUUID(uuid)
	}
	mmGetByUUID.t.Fatalf("Unexpected call to ParkingRepositoryMock.GetByUUID. %v", uuid)
	return
}

// GetByUUIDAfterCounter returns a count of finished ParkingRepositoryMock.GetByUUID invocations
func (mmGetByUUID *ParkingRepositoryMock) GetByUUIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUUID.afterGetByUUIDCounter)
}

// GetByUUIDBeforeCounter returns a count of ParkingRepositoryMock.GetByUUID invocations
func (mmGetByUUID *ParkingRepositoryMock) GetByUUIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUUID.beforeGetByUUIDCounter)
}

// Calls returns a list of arguments used in each call to ParkingRepositoryMock.GetByUUID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByUUID *mParkingRepositoryMockGetByUUID) Calls() []*ParkingRepositoryMockGetByUUIDParams {
	mmGetByUUID.mutex.RLock()

	argCopy := make([]*ParkingRepositoryMockGetByUUIDParams, len(mmGetByUUID.callArgs))
	copy(argCopy, mmGetByUUID.callArgs)

	mmGetByUUID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByUUIDDone returns true if the count of the GetByUUID invocations corresponds
// the number of defined expectations
func (m *ParkingRepositoryMock) MinimockGetByUUIDDone() bool {
	if m.GetByUUIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByUUIDMock.invocationsDone()
}

// MinimockGetByUUIDInspect logs each unmet expectation
func (m *ParkingRepositoryMock) MinimockGetByUUIDInspect() {
	for _, e := range m.GetByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ParkingRepositoryMock.GetByUUID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByUUIDCounter := mm_atomic.LoadUint64(&m.afterGetByUUIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByUUIDMock.defaultExpectation != nil && afterGetByUUIDCounter < 1 {
		if m.GetByUUIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ParkingRepositoryMock.GetByUUID at\n%s", m.GetByUUIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ParkingRepositoryMock.GetByUUID at\n%s with params: %#v", m.GetByUUIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByUUIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByUUID != nil && afterGetByUUIDCounter < 1 {
		m.t.Errorf("Expected call to ParkingRepositoryMock.GetByUUID at\n%s", m.funcGetByUUIDOrigin)
	}

	if !m.GetByUUIDMock.invocationsDone() && afterGetByUUIDCounter > 0 {
		m.t.Errorf("Expected %d calls to ParkingRepositoryMock.GetByUUID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByUUIDMock.expectedInvocations), m.GetByUUIDMock.expectedInvocationsOrigin, afterGetByUUIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ParkingRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()

			m.MinimockGetByUUIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ParkingRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ParkingRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone() &&
		m.MinimockGetByUUIDDone()
}
