// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i k071123/internal/services/parking_service/domain/repositories.SessionRepository -o session_repository_mock_test.go -n SessionRepositoryMock -p mocks

import (
	"k071123/internal/services/parking_service/domain/models"
	mm_repositories "k071123/internal/services/parking_service/domain/repositories"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// SessionRepositoryMock implements mm_repositories.SessionRepository
type SessionRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(model *models.Session) (err error)
	funcAddOrigin    string
	inspectFuncAdd   func(model *models.Session)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mSessionRepositoryMockAdd

	funcFilter          func() (s1 mm_repositories.SessionFilter)
	funcFilterOrigin    string
	inspectFuncFilter   func()
	afterFilterCounter  uint64
	beforeFilterCounter uint64
	FilterMock          mSessionRepositoryMockFilter

	funcGetByUUID          func(uuid string) (sp1 *models.Session, err error)
	funcGetByUUIDOrigin    string
	inspectFuncGetByUUID   func(uuid string)
	afterGetByUUIDCounter  uint64
	beforeGetByUUIDCounter uint64
	GetByUUIDMock          mSessionRepositoryMockGetByUUID

	funcUpdate          func(uuid uuid.UUID, updates mm_repositories.SessionUpdates) (err error)
	funcUpdateOrigin    string
	inspectFuncUpdate   func(uuid uuid.UUID, updates mm_repositories.SessionUpdates)
	afterUpdateCounter  uint64
	beforeUpdateCounter uint64
	UpdateMock          mSessionRepositoryMockUpdate

	funcUpdates          func() (s1 mm_repositories.SessionUpdates)
	funcUpdatesOrigin    string
	inspectFuncUpdates   func()
	afterUpdatesCounter  uint64
	beforeUpdatesCounter uint64
	UpdatesMock          mSessionRepositoryMockUpdates

	funcWhereFilter          func(filter mm_repositories.SessionFilter) (sa1 []models.Session, err error)
	funcWhereFilterOrigin    string
	inspectFuncWhereFilter   func(filter mm_repositories.SessionFilter)
	afterWhereFilterCounter  uint64
	beforeWhereFilterCounter uint64
	WhereFilterMock          mSessionRepositoryMockWhereFilter
}

// NewSessionRepositoryMock returns a mock for mm_repositories.SessionRepository
func NewSessionRepositoryMock(t minimock.Tester) *SessionRepositoryMock {
	m := &SessionRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mSessionRepositoryMockAdd{mock: m}
	m.AddMock.callArgs = []*SessionRepositoryMockAddParams{}

	m.FilterMock = mSessionRepositoryMockFilter{mock: m}

	m.GetByUUIDMock = mSessionRepositoryMockGetByUUID{mock: m}
	m.GetByUUIDMock.callArgs = []*SessionRepositoryMockGetByUUIDParams{}

	m.UpdateMock = mSessionRepositoryMockUpdate{mock: m}
	m.UpdateMock.callArgs = []*SessionRepositoryMockUpdateParams{}

	m.UpdatesMock = mSessionRepositoryMockUpdates{mock: m}

	m.WhereFilterMock = mSessionRepositoryMockWhereFilter{mock: m}
	m.WhereFilterMock.callArgs = []*SessionRepositoryMockWhereFilterParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSessionRepositoryMockAdd struct {
	optional           bool
	mock               *SessionRepositoryMock
	defaultExpectation *SessionRepositoryMockAddExpectation
	expectations       []*SessionRepositoryMockAddExpectation

	callArgs []*SessionRepositoryMockAddParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepositoryMockAddExpectation specifies expectation struct of the SessionRepository.Add
type SessionRepositoryMockAddExpectation struct {
	mock               *SessionRepositoryMock
	params             *SessionRepositoryMockAddParams
	paramPtrs          *SessionRepositoryMockAddParamPtrs
	expectationOrigins SessionRepositoryMockAddExpectationOrigins
	results            *SessionRepositoryMockAddResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepositoryMockAddParams contains parameters of the SessionRepository.Add
type SessionRepositoryMockAddParams struct {
	model *models.Session
}

// SessionRepositoryMockAddParamPtrs contains pointers to parameters of the SessionRepository.Add
type SessionRepositoryMockAddParamPtrs struct {
	model **models.Session
}

// SessionRepositoryMockAddResults contains results of the SessionRepository.Add
type SessionRepositoryMockAddResults struct {
	err error
}

// SessionRepositoryMockAddOrigins contains origins of expectations of the SessionRepository.Add
type SessionRepositoryMockAddExpectationOrigins struct {
	origin      string
	originModel string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAdd *mSessionRepositoryMockAdd) Optional() *mSessionRepositoryMockAdd {
	mmAdd.optional = true
	return mmAdd
}

// Expect sets up expected params for SessionRepository.Add
func (mmAdd *mSessionRepositoryMockAdd) Expect(model *models.Session) *mSessionRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("SessionRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &SessionRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.paramPtrs != nil {
		mmAdd.mock.t.Fatalf("SessionRepositoryMock.Add mock is already set by ExpectParams functions")
	}

	mmAdd.defaultExpectation.params = &SessionRepositoryMockAddParams{model}
	mmAdd.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// ExpectModelParam1 sets up expected param model for SessionRepository.Add
func (mmAdd *mSessionRepositoryMockAdd) ExpectModelParam1(model *models.Session) *mSessionRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("SessionRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &SessionRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("SessionRepositoryMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &SessionRepositoryMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.model = &model
	mmAdd.defaultExpectation.expectationOrigins.originModel = minimock.CallerInfo(1)

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the SessionRepository.Add
func (mmAdd *mSessionRepositoryMockAdd) Inspect(f func(model *models.Session)) *mSessionRepositoryMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for SessionRepositoryMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by SessionRepository.Add
func (mmAdd *mSessionRepositoryMockAdd) Return(err error) *SessionRepositoryMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("SessionRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &SessionRepositoryMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &SessionRepositoryMockAddResults{err}
	mmAdd.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// Set uses given function f to mock the SessionRepository.Add method
func (mmAdd *mSessionRepositoryMockAdd) Set(f func(model *models.Session) (err error)) *SessionRepositoryMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the SessionRepository.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the SessionRepository.Add method")
	}

	mmAdd.mock.funcAdd = f
	mmAdd.mock.funcAddOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// When sets expectation for the SessionRepository.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mSessionRepositoryMockAdd) When(model *models.Session) *SessionRepositoryMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("SessionRepositoryMock.Add mock is already set by Set")
	}

	expectation := &SessionRepositoryMockAddExpectation{
		mock:               mmAdd.mock,
		params:             &SessionRepositoryMockAddParams{model},
		expectationOrigins: SessionRepositoryMockAddExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up SessionRepository.Add return parameters for the expectation previously defined by the When method
func (e *SessionRepositoryMockAddExpectation) Then(err error) *SessionRepositoryMock {
	e.results = &SessionRepositoryMockAddResults{err}
	return e.mock
}

// Times sets number of times SessionRepository.Add should be invoked
func (mmAdd *mSessionRepositoryMockAdd) Times(n uint64) *mSessionRepositoryMockAdd {
	if n == 0 {
		mmAdd.mock.t.Fatalf("Times of SessionRepositoryMock.Add mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAdd.expectedInvocations, n)
	mmAdd.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAdd
}

func (mmAdd *mSessionRepositoryMockAdd) invocationsDone() bool {
	if len(mmAdd.expectations) == 0 && mmAdd.defaultExpectation == nil && mmAdd.mock.funcAdd == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAdd.mock.afterAddCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAdd.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Add implements mm_repositories.SessionRepository
func (mmAdd *SessionRepositoryMock) Add(model *models.Session) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	mmAdd.t.Helper()

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(model)
	}

	mm_params := SessionRepositoryMockAddParams{model}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_want_ptrs := mmAdd.AddMock.defaultExpectation.paramPtrs

		mm_got := SessionRepositoryMockAddParams{model}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.model != nil && !minimock.Equal(*mm_want_ptrs.model, mm_got.model) {
				mmAdd.t.Errorf("SessionRepositoryMock.Add got unexpected parameter model, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originModel, *mm_want_ptrs.model, mm_got.model, minimock.Diff(*mm_want_ptrs.model, mm_got.model))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("SessionRepositoryMock.Add got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAdd.AddMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results == nil {
			mmAdd.t.Fatal("No results are set for the SessionRepositoryMock.Add")
		}
		return (*mm_results).err
	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(model)
	}
	mmAdd.t.Fatalf("Unexpected call to SessionRepositoryMock.Add. %v", model)
	return
}

// AddAfterCounter returns a count of finished SessionRepositoryMock.Add invocations
func (mmAdd *SessionRepositoryMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of SessionRepositoryMock.Add invocations
func (mmAdd *SessionRepositoryMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to SessionRepositoryMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mSessionRepositoryMockAdd) Calls() []*SessionRepositoryMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*SessionRepositoryMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *SessionRepositoryMock) MinimockAddDone() bool {
	if m.AddMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddMock.invocationsDone()
}

// MinimockAddInspect logs each unmet expectation
func (m *SessionRepositoryMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepositoryMock.Add at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddCounter := mm_atomic.LoadUint64(&m.afterAddCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && afterAddCounter < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepositoryMock.Add at\n%s", m.AddMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepositoryMock.Add at\n%s with params: %#v", m.AddMock.defaultExpectation.expectationOrigins.origin, *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && afterAddCounter < 1 {
		m.t.Errorf("Expected call to SessionRepositoryMock.Add at\n%s", m.funcAddOrigin)
	}

	if !m.AddMock.invocationsDone() && afterAddCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepositoryMock.Add at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddMock.expectedInvocations), m.AddMock.expectedInvocationsOrigin, afterAddCounter)
	}
}

type mSessionRepositoryMockFilter struct {
	optional           bool
	mock               *SessionRepositoryMock
	defaultExpectation *SessionRepositoryMockFilterExpectation
	expectations       []*SessionRepositoryMockFilterExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepositoryMockFilterExpectation specifies expectation struct of the SessionRepository.Filter
type SessionRepositoryMockFilterExpectation struct {
	mock *SessionRepositoryMock

	results      *SessionRepositoryMockFilterResults
	returnOrigin string
	Counter      uint64
}

// SessionRepositoryMockFilterResults contains results of the SessionRepository.Filter
type SessionRepositoryMockFilterResults struct {
	s1 mm_repositories.SessionFilter
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFilter *mSessionRepositoryMockFilter) Optional() *mSessionRepositoryMockFilter {
	mmFilter.optional = true
	return mmFilter
}

// Expect sets up expected params for SessionRepository.Filter
func (mmFilter *mSessionRepositoryMockFilter) Expect() *mSessionRepositoryMockFilter {
	if mmFilter.mock.funcFilter != nil {
		mmFilter.mock.t.Fatalf("SessionRepositoryMock.Filter mock is already set by Set")
	}

	if mmFilter.defaultExpectation == nil {
		mmFilter.defaultExpectation = &SessionRepositoryMockFilterExpectation{}
	}

	return mmFilter
}

// Inspect accepts an inspector function that has same arguments as the SessionRepository.Filter
func (mmFilter *mSessionRepositoryMockFilter) Inspect(f func()) *mSessionRepositoryMockFilter {
	if mmFilter.mock.inspectFuncFilter != nil {
		mmFilter.mock.t.Fatalf("Inspect function is already set for SessionRepositoryMock.Filter")
	}

	mmFilter.mock.inspectFuncFilter = f

	return mmFilter
}

// Return sets up results that will be returned by SessionRepository.Filter
func (mmFilter *mSessionRepositoryMockFilter) Return(s1 mm_repositories.SessionFilter) *SessionRepositoryMock {
	if mmFilter.mock.funcFilter != nil {
		mmFilter.mock.t.Fatalf("SessionRepositoryMock.Filter mock is already set by Set")
	}

	if mmFilter.defaultExpectation == nil {
		mmFilter.defaultExpectation = &SessionRepositoryMockFilterExpectation{mock: mmFilter.mock}
	}
	mmFilter.defaultExpectation.results = &SessionRepositoryMockFilterResults{s1}
	mmFilter.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFilter.mock
}

// Set uses given function f to mock the SessionRepository.Filter method
func (mmFilter *mSessionRepositoryMockFilter) Set(f func() (s1 mm_repositories.SessionFilter)) *SessionRepositoryMock {
	if mmFilter.defaultExpectation != nil {
		mmFilter.mock.t.Fatalf("Default expectation is already set for the SessionRepository.Filter method")
	}

	if len(mmFilter.expectations) > 0 {
		mmFilter.mock.t.Fatalf("Some expectations are already set for the SessionRepository.Filter method")
	}

	mmFilter.mock.funcFilter = f
	mmFilter.mock.funcFilterOrigin = minimock.CallerInfo(1)
	return mmFilter.mock
}

// Times sets number of times SessionRepository.Filter should be invoked
func (mmFilter *mSessionRepositoryMockFilter) Times(n uint64) *mSessionRepositoryMockFilter {
	if n == 0 {
		mmFilter.mock.t.Fatalf("Times of SessionRepositoryMock.Filter mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFilter.expectedInvocations, n)
	mmFilter.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFilter
}

func (mmFilter *mSessionRepositoryMockFilter) invocationsDone() bool {
	if len(mmFilter.expectations) == 0 && mmFilter.defaultExpectation == nil && mmFilter.mock.funcFilter == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFilter.mock.afterFilterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFilter.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Filter implements mm_repositories.SessionRepository
func (mmFilter *SessionRepositoryMock) Filter() (s1 mm_repositories.SessionFilter) {
	mm_atomic.AddUint64(&mmFilter.beforeFilterCounter, 1)
	defer mm_atomic.AddUint64(&mmFilter.afterFilterCounter, 1)

	mmFilter.t.Helper()

	if mmFilter.inspectFuncFilter != nil {
		mmFilter.inspectFuncFilter()
	}

	if mmFilter.FilterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFilter.FilterMock.defaultExpectation.Counter, 1)

		mm_results := mmFilter.FilterMock.defaultExpectation.results
		if mm_results == nil {
			mmFilter.t.Fatal("No results are set for the SessionRepositoryMock.Filter")
		}
		return (*mm_results).s1
	}
	if mmFilter.funcFilter != nil {
		return mmFilter.funcFilter()
	}
	mmFilter.t.Fatalf("Unexpected call to SessionRepositoryMock.Filter.")
	return
}

// FilterAfterCounter returns a count of finished SessionRepositoryMock.Filter invocations
func (mmFilter *SessionRepositoryMock) FilterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFilter.afterFilterCounter)
}

// FilterBeforeCounter returns a count of SessionRepositoryMock.Filter invocations
func (mmFilter *SessionRepositoryMock) FilterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFilter.beforeFilterCounter)
}

// MinimockFilterDone returns true if the count of the Filter invocations corresponds
// the number of defined expectations
func (m *SessionRepositoryMock) MinimockFilterDone() bool {
	if m.FilterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FilterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FilterMock.invocationsDone()
}

// MinimockFilterInspect logs each unmet expectation
func (m *SessionRepositoryMock) MinimockFilterInspect() {
	for _, e := range m.FilterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to SessionRepositoryMock.Filter")
		}
	}

	afterFilterCounter := mm_atomic.LoadUint64(&m.afterFilterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FilterMock.defaultExpectation != nil && afterFilterCounter < 1 {
		m.t.Errorf("Expected call to SessionRepositoryMock.Filter at\n%s", m.FilterMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFilter != nil && afterFilterCounter < 1 {
		m.t.Errorf("Expected call to SessionRepositoryMock.Filter at\n%s", m.funcFilterOrigin)
	}

	if !m.FilterMock.invocationsDone() && afterFilterCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepositoryMock.Filter at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FilterMock.expectedInvocations), m.FilterMock.expectedInvocationsOrigin, afterFilterCounter)
	}
}

type mSessionRepositoryMockGetByUUID struct {
	optional           bool
	mock               *SessionRepositoryMock
	defaultExpectation *SessionRepositoryMockGetByUUIDExpectation
	expectations       []*SessionRepositoryMockGetByUUIDExpectation

	callArgs []*SessionRepositoryMockGetByUUIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepositoryMockGetByUUIDExpectation specifies expectation struct of the SessionRepository.GetByUUID
type SessionRepositoryMockGetByUUIDExpectation struct {
	mock               *SessionRepositoryMock
	params             *SessionRepositoryMockGetByUUIDParams
	paramPtrs          *SessionRepositoryMockGetByUUIDParamPtrs
	expectationOrigins SessionRepositoryMockGetByUUIDExpectationOrigins
	results            *SessionRepositoryMockGetByUUIDResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepositoryMockGetByUUIDParams contains parameters of the SessionRepository.GetByUUID
type SessionRepositoryMockGetByUUIDParams struct {
	uuid string
}

// SessionRepositoryMockGetByUUIDParamPtrs contains pointers to parameters of the SessionRepository.GetByUUID
type SessionRepositoryMockGetByUUIDParamPtrs struct {
	uuid *string
}

// SessionRepositoryMockGetByUUIDResults contains results of the SessionRepository.GetByUUID
type SessionRepositoryMockGetByUUIDResults struct {
	sp1 *models.Session
	err error
}

// SessionRepositoryMockGetByUUIDOrigins contains origins of expectations of the SessionRepository.GetByUUID
type SessionRepositoryMockGetByUUIDExpectationOrigins struct {
	origin     string
	originUuid string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) Optional() *mSessionRepositoryMockGetByUUID {
	mmGetByUUID.optional = true
	return mmGetByUUID
}

// Expect sets up expected params for SessionRepository.GetByUUID
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) Expect(uuid string) *mSessionRepositoryMockGetByUUID {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("SessionRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &SessionRepositoryMockGetByUUIDExpectation{}
	}

	if mmGetByUUID.defaultExpectation.paramPtrs != nil {
		mmGetByUUID.mock.t.Fatalf("SessionRepositoryMock.GetByUUID mock is already set by ExpectParams functions")
	}

	mmGetByUUID.defaultExpectation.params = &SessionRepositoryMockGetByUUIDParams{uuid}
	mmGetByUUID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByUUID.expectations {
		if minimock.Equal(e.params, mmGetByUUID.defaultExpectation.params) {
			mmGetByUUID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByUUID.defaultExpectation.params)
		}
	}

	return mmGetByUUID
}

// ExpectUuidParam1 sets up expected param uuid for SessionRepository.GetByUUID
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) ExpectUuidParam1(uuid string) *mSessionRepositoryMockGetByUUID {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("SessionRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &SessionRepositoryMockGetByUUIDExpectation{}
	}

	if mmGetByUUID.defaultExpectation.params != nil {
		mmGetByUUID.mock.t.Fatalf("SessionRepositoryMock.GetByUUID mock is already set by Expect")
	}

	if mmGetByUUID.defaultExpectation.paramPtrs == nil {
		mmGetByUUID.defaultExpectation.paramPtrs = &SessionRepositoryMockGetByUUIDParamPtrs{}
	}
	mmGetByUUID.defaultExpectation.paramPtrs.uuid = &uuid
	mmGetByUUID.defaultExpectation.expectationOrigins.originUuid = minimock.CallerInfo(1)

	return mmGetByUUID
}

// Inspect accepts an inspector function that has same arguments as the SessionRepository.GetByUUID
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) Inspect(f func(uuid string)) *mSessionRepositoryMockGetByUUID {
	if mmGetByUUID.mock.inspectFuncGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("Inspect function is already set for SessionRepositoryMock.GetByUUID")
	}

	mmGetByUUID.mock.inspectFuncGetByUUID = f

	return mmGetByUUID
}

// Return sets up results that will be returned by SessionRepository.GetByUUID
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) Return(sp1 *models.Session, err error) *SessionRepositoryMock {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("SessionRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &SessionRepositoryMockGetByUUIDExpectation{mock: mmGetByUUID.mock}
	}
	mmGetByUUID.defaultExpectation.results = &SessionRepositoryMockGetByUUIDResults{sp1, err}
	mmGetByUUID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByUUID.mock
}

// Set uses given function f to mock the SessionRepository.GetByUUID method
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) Set(f func(uuid string) (sp1 *models.Session, err error)) *SessionRepositoryMock {
	if mmGetByUUID.defaultExpectation != nil {
		mmGetByUUID.mock.t.Fatalf("Default expectation is already set for the SessionRepository.GetByUUID method")
	}

	if len(mmGetByUUID.expectations) > 0 {
		mmGetByUUID.mock.t.Fatalf("Some expectations are already set for the SessionRepository.GetByUUID method")
	}

	mmGetByUUID.mock.funcGetByUUID = f
	mmGetByUUID.mock.funcGetByUUIDOrigin = minimock.CallerInfo(1)
	return mmGetByUUID.mock
}

// When sets expectation for the SessionRepository.GetByUUID which will trigger the result defined by the following
// Then helper
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) When(uuid string) *SessionRepositoryMockGetByUUIDExpectation {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("SessionRepositoryMock.GetByUUID mock is already set by Set")
	}

	expectation := &SessionRepositoryMockGetByUUIDExpectation{
		mock:               mmGetByUUID.mock,
		params:             &SessionRepositoryMockGetByUUIDParams{uuid},
		expectationOrigins: SessionRepositoryMockGetByUUIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByUUID.expectations = append(mmGetByUUID.expectations, expectation)
	return expectation
}

// Then sets up SessionRepository.GetByUUID return parameters for the expectation previously defined by the When method
func (e *SessionRepositoryMockGetByUUIDExpectation) Then(sp1 *models.Session, err error) *SessionRepositoryMock {
	e.results = &SessionRepositoryMockGetByUUIDResults{sp1, err}
	return e.mock
}

// Times sets number of times SessionRepository.GetByUUID should be invoked
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) Times(n uint64) *mSessionRepositoryMockGetByUUID {
	if n == 0 {
		mmGetByUUID.mock.t.Fatalf("Times of SessionRepositoryMock.GetByUUID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByUUID.expectedInvocations, n)
	mmGetByUUID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByUUID
}

func (mmGetByUUID *mSessionRepositoryMockGetByUUID) invocationsDone() bool {
	if len(mmGetByUUID.expectations) == 0 && mmGetByUUID.defaultExpectation == nil && mmGetByUUID.mock.funcGetByUUID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByUUID.mock.afterGetByUUIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByUUID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByUUID implements mm_repositories.SessionRepository
func (mmGetByUUID *SessionRepositoryMock) GetByUUID(uuid string) (sp1 *models.Session, err error) {
	mm_atomic.AddUint64(&mmGetByUUID.beforeGetByUUIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByUUID.afterGetByUUIDCounter, 1)

	mmGetByUUID.t.Helper()

	if mmGetByUUID.inspectFuncGetByUUID != nil {
		mmGetByUUID.inspectFuncGetByUUID(uuid)
	}

	mm_params := SessionRepositoryMockGetByUUIDParams{uuid}

	// Record call args
	mmGetByUUID.GetByUUIDMock.mutex.Lock()
	mmGetByUUID.GetByUUIDMock.callArgs = append(mmGetByUUID.GetByUUIDMock.callArgs, &mm_params)
	mmGetByUUID.GetByUUIDMock.mutex.Unlock()

	for _, e := range mmGetByUUID.GetByUUIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmGetByUUID.GetByUUIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByUUID.GetByUUIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByUUID.GetByUUIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByUUID.GetByUUIDMock.defaultExpectation.paramPtrs

		mm_got := SessionRepositoryMockGetByUUIDParams{uuid}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.uuid != nil && !minimock.Equal(*mm_want_ptrs.uuid, mm_got.uuid) {
				mmGetByUUID.t.Errorf("SessionRepositoryMock.GetByUUID got unexpected parameter uuid, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByUUID.GetByUUIDMock.defaultExpectation.expectationOrigins.originUuid, *mm_want_ptrs.uuid, mm_got.uuid, minimock.Diff(*mm_want_ptrs.uuid, mm_got.uuid))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByUUID.t.Errorf("SessionRepositoryMock.GetByUUID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByUUID.GetByUUIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByUUID.GetByUUIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByUUID.t.Fatal("No results are set for the SessionRepositoryMock.GetByUUID")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmGetByUUID.funcGetByUUID != nil {
		return mmGetByUUID.funcGetByUUID(uuid)
	}
	mmGetByUUID.t.Fatalf("Unexpected call to SessionRepositoryMock.GetByUUID. %v", uuid)
	return
}

// GetByUUIDAfterCounter returns a count of finished SessionRepositoryMock.GetByUUID invocations
func (mmGetByUUID *SessionRepositoryMock) GetByUUIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUUID.afterGetByUUIDCounter)
}

// GetByUUIDBeforeCounter returns a count of SessionRepositoryMock.GetByUUID invocations
func (mmGetByUUID *SessionRepositoryMock) GetByUUIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUUID.beforeGetByUUIDCounter)
}

// Calls returns a list of arguments used in each call to SessionRepositoryMock.GetByUUID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByUUID *mSessionRepositoryMockGetByUUID) Calls() []*SessionRepositoryMockGetByUUIDParams {
	mmGetByUUID.mutex.RLock()

	argCopy := make([]*SessionRepositoryMockGetByUUIDParams, len(mmGetByUUID.callArgs))
	copy(argCopy, mmGetByUUID.callArgs)

	mmGetByUUID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByUUIDDone returns true if the count of the GetByUUID invocations corresponds
// the number of defined expectations
func (m *SessionRepositoryMock) MinimockGetByUUIDDone() bool {
	if m.GetByUUIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByUUIDMock.invocationsDone()
}

// MinimockGetByUUIDInspect logs each unmet expectation
func (m *SessionRepositoryMock) MinimockGetByUUIDInspect() {
	for _, e := range m.GetByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepositoryMock.GetByUUID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByUUIDCounter := mm_atomic.LoadUint64(&m.afterGetByUUIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByUUIDMock.defaultExpectation != nil && afterGetByUUIDCounter < 1 {
		if m.GetByUUIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepositoryMock.GetByUUID at\n%s", m.GetByUUIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepositoryMock.GetByUUID at\n%s with params: %#v", m.GetByUUIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByUUIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByUUID != nil && afterGetByUUIDCounter < 1 {
		m.t.Errorf("Expected call to SessionRepositoryMock.GetByUUID at\n%s", m.funcGetByUUIDOrigin)
	}

	if !m.GetByUUIDMock.invocationsDone() && afterGetByUUIDCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepositoryMock.GetByUUID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByUUIDMock.expectedInvocations), m.GetByUUIDMock.expectedInvocationsOrigin, afterGetByUUIDCounter)
	}
}

type mSessionRepositoryMockUpdate struct {
	optional           bool
	mock               *SessionRepositoryMock
	defaultExpectation *SessionRepositoryMockUpdateExpectation
	expectations       []*SessionRepositoryMockUpdateExpectation

	callArgs []*SessionRepositoryMockUpdateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepositoryMockUpdateExpectation specifies expectation struct of the SessionRepository.Update
type SessionRepositoryMockUpdateExpectation struct {
	mock               *SessionRepositoryMock
	params             *SessionRepositoryMockUpdateParams
	paramPtrs          *SessionRepositoryMockUpdateParamPtrs
	expectationOrigins SessionRepositoryMockUpdateExpectationOrigins
	results            *SessionRepositoryMockUpdateResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepositoryMockUpdateParams contains parameters of the SessionRepository.Update
type SessionRepositoryMockUpdateParams struct {
	uuid    uuid.UUID
	updates mm_repositories.SessionUpdates
}

// SessionRepositoryMockUpdateParamPtrs contains pointers to parameters of the SessionRepository.Update
type SessionRepositoryMockUpdateParamPtrs struct {
	uuid    *uuid.UUID
	updates *mm_repositories.SessionUpdates
}

// SessionRepositoryMockUpdateResults contains results of the SessionRepository.Update
type SessionRepositoryMockUpdateResults struct {
	err error
}

// SessionRepositoryMockUpdateOrigins contains origins of expectations of the SessionRepository.Update
type SessionRepositoryMockUpdateExpectationOrigins struct {
	origin        string
	originUuid    string
	originUpdates string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdate *mSessionRepositoryMockUpdate) Optional() *mSessionRepositoryMockUpdate {
	mmUpdate.optional = true
	return mmUpdate
}

// Expect sets up expected params for SessionRepository.Update
func (mmUpdate *mSessionRepositoryMockUpdate) Expect(uuid uuid.UUID, updates mm_repositories.SessionUpdates) *mSessionRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SessionRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SessionRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.paramPtrs != nil {
		mmUpdate.mock.t.Fatalf("SessionRepositoryMock.Update mock is already set by ExpectParams functions")
	}

	mmUpdate.defaultExpectation.params = &SessionRepositoryMockUpdateParams{uuid, updates}
	mmUpdate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdate.expectations {
		if minimock.Equal(e.params, mmUpdate.defaultExpectation.params) {
			mmUpdate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdate.defaultExpectation.params)
		}
	}

	return mmUpdate
}

// ExpectUuidParam1 sets up expected param uuid for SessionRepository.Update
func (mmUpdate *mSessionRepositoryMockUpdate) ExpectUuidParam1(uuid uuid.UUID) *mSessionRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SessionRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SessionRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("SessionRepositoryMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &SessionRepositoryMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.uuid = &uuid
	mmUpdate.defaultExpectation.expectationOrigins.originUuid = minimock.CallerInfo(1)

	return mmUpdate
}

// ExpectUpdatesParam2 sets up expected param updates for SessionRepository.Update
func (mmUpdate *mSessionRepositoryMockUpdate) ExpectUpdatesParam2(updates mm_repositories.SessionUpdates) *mSessionRepositoryMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SessionRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SessionRepositoryMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("SessionRepositoryMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &SessionRepositoryMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.updates = &updates
	mmUpdate.defaultExpectation.expectationOrigins.originUpdates = minimock.CallerInfo(1)

	return mmUpdate
}

// Inspect accepts an inspector function that has same arguments as the SessionRepository.Update
func (mmUpdate *mSessionRepositoryMockUpdate) Inspect(f func(uuid uuid.UUID, updates mm_repositories.SessionUpdates)) *mSessionRepositoryMockUpdate {
	if mmUpdate.mock.inspectFuncUpdate != nil {
		mmUpdate.mock.t.Fatalf("Inspect function is already set for SessionRepositoryMock.Update")
	}

	mmUpdate.mock.inspectFuncUpdate = f

	return mmUpdate
}

// Return sets up results that will be returned by SessionRepository.Update
func (mmUpdate *mSessionRepositoryMockUpdate) Return(err error) *SessionRepositoryMock {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SessionRepositoryMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &SessionRepositoryMockUpdateExpectation{mock: mmUpdate.mock}
	}
	mmUpdate.defaultExpectation.results = &SessionRepositoryMockUpdateResults{err}
	mmUpdate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// Set uses given function f to mock the SessionRepository.Update method
func (mmUpdate *mSessionRepositoryMockUpdate) Set(f func(uuid uuid.UUID, updates mm_repositories.SessionUpdates) (err error)) *SessionRepositoryMock {
	if mmUpdate.defaultExpectation != nil {
		mmUpdate.mock.t.Fatalf("Default expectation is already set for the SessionRepository.Update method")
	}

	if len(mmUpdate.expectations) > 0 {
		mmUpdate.mock.t.Fatalf("Some expectations are already set for the SessionRepository.Update method")
	}

	mmUpdate.mock.funcUpdate = f
	mmUpdate.mock.funcUpdateOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// When sets expectation for the SessionRepository.Update which will trigger the result defined by the following
// Then helper
func (mmUpdate *mSessionRepositoryMockUpdate) When(uuid uuid.UUID, updates mm_repositories.SessionUpdates) *SessionRepositoryMockUpdateExpectation {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("SessionRepositoryMock.Update mock is already set by Set")
	}

	expectation := &SessionRepositoryMockUpdateExpectation{
		mock:               mmUpdate.mock,
		params:             &SessionRepositoryMockUpdateParams{uuid, updates},
		expectationOrigins: SessionRepositoryMockUpdateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdate.expectations = append(mmUpdate.expectations, expectation)
	return expectation
}

// Then sets up SessionRepository.Update return parameters for the expectation previously defined by the When method
func (e *SessionRepositoryMockUpdateExpectation) Then(err error) *SessionRepositoryMock {
	e.results = &SessionRepositoryMockUpdateResults{err}
	return e.mock
}

// Times sets number of times SessionRepository.Update should be invoked
func (mmUpdate *mSessionRepositoryMockUpdate) Times(n uint64) *mSessionRepositoryMockUpdate {
	if n == 0 {
		mmUpdate.mock.t.Fatalf("Times of SessionRepositoryMock.Update mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdate.expectedInvocations, n)
	mmUpdate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdate
}

func (mmUpdate *mSessionRepositoryMockUpdate) invocationsDone() bool {
	if len(mmUpdate.expectations) == 0 && mmUpdate.defaultExpectation == nil && mmUpdate.mock.funcUpdate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdate.mock.afterUpdateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Update implements mm_repositories.SessionRepository
func (mmUpdate *SessionRepositoryMock) Update(uuid uuid.UUID, updates mm_repositories.SessionUpdates) (err error) {
	mm_atomic.AddUint64(&mmUpdate.beforeUpdateCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdate.afterUpdateCounter, 1)

	mmUpdate.t.Helper()

	if mmUpdate.inspectFuncUpdate != nil {
		mmUpdate.inspectFuncUpdate(uuid, updates)
	}

	mm_params := SessionRepositoryMockUpdateParams{uuid, updates}

	// Record call args
	mmUpdate.UpdateMock.mutex.Lock()
	mmUpdate.UpdateMock.callArgs = append(mmUpdate.UpdateMock.callArgs, &mm_params)
	mmUpdate.UpdateMock.mutex.Unlock()

	for _, e := range mmUpdate.UpdateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdate.UpdateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdate.UpdateMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdate.UpdateMock.defaultExpectation.params
		mm_want_ptrs := mmUpdate.UpdateMock.defaultExpectation.paramPtrs

		mm_got := SessionRepositoryMockUpdateParams{uuid, updates}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.uuid != nil && !minimock.Equal(*mm_want_ptrs.uuid, mm_got.uuid) {
				mmUpdate.t.Errorf("SessionRepositoryMock.Update got unexpected parameter uuid, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originUuid, *mm_want_ptrs.uuid, mm_got.uuid, minimock.Diff(*mm_want_ptrs.uuid, mm_got.uuid))
			}

			if mm_want_ptrs.updates != nil && !minimock.Equal(*mm_want_ptrs.updates, mm_got.updates) {
				mmUpdate.t.Errorf("SessionRepositoryMock.Update got unexpected parameter updates, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originUpdates, *mm_want_ptrs.updates, mm_got.updates, minimock.Diff(*mm_want_ptrs.updates, mm_got.updates))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdate.t.Errorf("SessionRepositoryMock.Update got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdate.UpdateMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdate.t.Fatal("No results are set for the SessionRepositoryMock.Update")
		}
		return (*mm_results).err
	}
	if mmUpdate.funcUpdate != nil {
		return mmUpdate.funcUpdate(uuid, updates)
	}
	mmUpdate.t.Fatalf("Unexpected call to SessionRepositoryMock.Update. %v %v", uuid, updates)
	return
}

// UpdateAfterCounter returns a count of finished SessionRepositoryMock.Update invocations
func (mmUpdate *SessionRepositoryMock) UpdateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.afterUpdateCounter)
}

// UpdateBeforeCounter returns a count of SessionRepositoryMock.Update invocations
func (mmUpdate *SessionRepositoryMock) UpdateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.beforeUpdateCounter)
}

// Calls returns a list of arguments used in each call to SessionRepositoryMock.Update.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdate *mSessionRepositoryMockUpdate) Calls() []*SessionRepositoryMockUpdateParams {
	mmUpdate.mutex.RLock()

	argCopy := make([]*SessionRepositoryMockUpdateParams, len(mmUpdate.callArgs))
	copy(argCopy, mmUpdate.callArgs)

	mmUpdate.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateDone returns true if the count of the Update invocations corresponds
// the number of defined expectations
func (m *SessionRepositoryMock) MinimockUpdateDone() bool {
	if m.UpdateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateMock.invocationsDone()
}

// MinimockUpdateInspect logs each unmet expectation
func (m *SessionRepositoryMock) MinimockUpdateInspect() {
	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepositoryMock.Update at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateCounter := mm_atomic.LoadUint64(&m.afterUpdateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateMock.defaultExpectation != nil && afterUpdateCounter < 1 {
		if m.UpdateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepositoryMock.Update at\n%s", m.UpdateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepositoryMock.Update at\n%s with params: %#v", m.UpdateMock.defaultExpectation.expectationOrigins.origin, *m.UpdateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdate != nil && afterUpdateCounter < 1 {
		m.t.Errorf("Expected call to SessionRepositoryMock.Update at\n%s", m.funcUpdateOrigin)
	}

	if !m.UpdateMock.invocationsDone() && afterUpdateCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepositoryMock.Update at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateMock.expectedInvocations), m.UpdateMock.expectedInvocationsOrigin, afterUpdateCounter)
	}
}

type mSessionRepositoryMockUpdates struct {
	optional           bool
	mock               *SessionRepositoryMock
	defaultExpectation *SessionRepositoryMockUpdatesExpectation
	expectations       []*SessionRepositoryMockUpdatesExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepositoryMockUpdatesExpectation specifies expectation struct of the SessionRepository.Updates
type SessionRepositoryMockUpdatesExpectation struct {
	mock *SessionRepositoryMock

	results      *SessionRepositoryMockUpdatesResults
	returnOrigin string
	Counter      uint64
}

// SessionRepositoryMockUpdatesResults contains results of the SessionRepository.Updates
type SessionRepositoryMockUpdatesResults struct {
	s1 mm_repositories.SessionUpdates
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdates *mSessionRepositoryMockUpdates) Optional() *mSessionRepositoryMockUpdates {
	mmUpdates.optional = true
	return mmUpdates
}

// Expect sets up expected params for SessionRepository.Updates
func (mmUpdates *mSessionRepositoryMockUpdates) Expect() *mSessionRepositoryMockUpdates {
	if mmUpdates.mock.funcUpdates != nil {
		mmUpdates.mock.t.Fatalf("SessionRepositoryMock.Updates mock is already set by Set")
	}

	if mmUpdates.defaultExpectation == nil {
		mmUpdates.defaultExpectation = &SessionRepositoryMockUpdatesExpectation{}
	}

	return mmUpdates
}

// Inspect accepts an inspector function that has same arguments as the SessionRepository.Updates
func (mmUpdates *mSessionRepositoryMockUpdates) Inspect(f func()) *mSessionRepositoryMockUpdates {
	if mmUpdates.mock.inspectFuncUpdates != nil {
		mmUpdates.mock.t.Fatalf("Inspect function is already set for SessionRepositoryMock.Updates")
	}

	mmUpdates.mock.inspectFuncUpdates = f

	return mmUpdates
}

// Return sets up results that will be returned by SessionRepository.Updates
func (mmUpdates *mSessionRepositoryMockUpdates) Return(s1 mm_repositories.SessionUpdates) *SessionRepositoryMock {
	if mmUpdates.mock.funcUpdates != nil {
		mmUpdates.mock.t.Fatalf("SessionRepositoryMock.Updates mock is already set by Set")
	}

	if mmUpdates.defaultExpectation == nil {
		mmUpdates.defaultExpectation = &SessionRepositoryMockUpdatesExpectation{mock: mmUpdates.mock}
	}
	mmUpdates.defaultExpectation.results = &SessionRepositoryMockUpdatesResults{s1}
	mmUpdates.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdates.mock
}

// Set uses given function f to mock the SessionRepository.Updates method
func (mmUpdates *mSessionRepositoryMockUpdates) Set(f func() (s1 mm_repositories.SessionUpdates)) *SessionRepositoryMock {
	if mmUpdates.defaultExpectation != nil {
		mmUpdates.mock.t.Fatalf("Default expectation is already set for the SessionRepository.Updates method")
	}

	if len(mmUpdates.expectations) > 0 {
		mmUpdates.mock.t.Fatalf("Some expectations are already set for the SessionRepository.Updates method")
	}

	mmUpdates.mock.funcUpdates = f
	mmUpdates.mock.funcUpdatesOrigin = minimock.CallerInfo(1)
	return mmUpdates.mock
}

// Times sets number of times SessionRepository.Updates should be invoked
func (mmUpdates *mSessionRepositoryMockUpdates) Times(n uint64) *mSessionRepositoryMockUpdates {
	if n == 0 {
		mmUpdates.mock.t.Fatalf("Times of SessionRepositoryMock.Updates mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdates.expectedInvocations, n)
	mmUpdates.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdates
}

func (mmUpdates *mSessionRepositoryMockUpdates) invocationsDone() bool {
	if len(mmUpdates.expectations) == 0 && mmUpdates.defaultExpectation == nil && mmUpdates.mock.funcUpdates == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdates.mock.afterUpdatesCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdates.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Updates implements mm_repositories.SessionRepository
func (mmUpdates *SessionRepositoryMock) Updates() (s1 mm_repositories.SessionUpdates) {
	mm_atomic.AddUint64(&mmUpdates.beforeUpdatesCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdates.afterUpdatesCounter, 1)

	mmUpdates.t.Helper()

	if mmUpdates.inspectFuncUpdates != nil {
		mmUpdates.inspectFuncUpdates()
	}

	if mmUpdates.UpdatesMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdates.UpdatesMock.defaultExpectation.Counter, 1)

		mm_results := mmUpdates.UpdatesMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdates.t.Fatal("No results are set for the SessionRepositoryMock.Updates")
		}
		return (*mm_results).s1
	}
	if mmUpdates.funcUpdates != nil {
		return mmUpdates.funcUpdates()
	}
	mmUpdates.t.Fatalf("Unexpected call to SessionRepositoryMock.Updates.")
	return
}

// UpdatesAfterCounter returns a count of finished SessionRepositoryMock.Updates invocations
func (mmUpdates *SessionRepositoryMock) UpdatesAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdates.afterUpdatesCounter)
}

// UpdatesBeforeCounter returns a count of SessionRepositoryMock.Updates invocations
func (mmUpdates *SessionRepositoryMock) UpdatesBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdates.beforeUpdatesCounter)
}

// MinimockUpdatesDone returns true if the count of the Updates invocations corresponds
// the number of defined expectations
func (m *SessionRepositoryMock) MinimockUpdatesDone() bool {
	if m.UpdatesMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdatesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdatesMock.invocationsDone()
}

// MinimockUpdatesInspect logs each unmet expectation
func (m *SessionRepositoryMock) MinimockUpdatesInspect() {
	for _, e := range m.UpdatesMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to SessionRepositoryMock.Updates")
		}
	}

	afterUpdatesCounter := mm_atomic.LoadUint64(&m.afterUpdatesCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdatesMock.defaultExpectation != nil && afterUpdatesCounter < 1 {
		m.t.Errorf("Expected call to SessionRepositoryMock.Updates at\n%s", m.UpdatesMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdates != nil && afterUpdatesCounter < 1 {
		m.t.Errorf("Expected call to SessionRepositoryMock.Updates at\n%s", m.funcUpdatesOrigin)
	}

	if !m.UpdatesMock.invocationsDone() && afterUpdatesCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepositoryMock.Updates at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdatesMock.expectedInvocations), m.UpdatesMock.expectedInvocationsOrigin, afterUpdatesCounter)
	}
}

type mSessionRepositoryMockWhereFilter struct {
	optional           bool
	mock               *SessionRepositoryMock
	defaultExpectation *SessionRepositoryMockWhereFilterExpectation
	expectations       []*SessionRepositoryMockWhereFilterExpectation

	callArgs []*SessionRepositoryMockWhereFilterParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepositoryMockWhereFilterExpectation specifies expectation struct of the SessionRepository.WhereFilter
type SessionRepositoryMockWhereFilterExpectation struct {
	mock               *SessionRepositoryMock
	params             *SessionRepositoryMockWhereFilterParams
	paramPtrs          *SessionRepositoryMockWhereFilterParamPtrs
	expectationOrigins SessionRepositoryMockWhereFilterExpectationOrigins
	results            *SessionRepositoryMockWhereFilterResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepositoryMockWhereFilterParams contains parameters of the SessionRepository.WhereFilter
type SessionRepositoryMockWhereFilterParams struct {
	filter mm_repositories.SessionFilter
}

// SessionRepositoryMockWhereFilterParamPtrs contains pointers to parameters of the SessionRepository.WhereFilter
type SessionRepositoryMockWhereFilterParamPtrs struct {
	filter *mm_repositories.SessionFilter
}

// SessionRepositoryMockWhereFilterResults contains results of the SessionRepository.WhereFilter
type SessionRepositoryMockWhereFilterResults struct {
	sa1 []models.Session
	err error
}

// SessionRepositoryMockWhereFilterOrigins contains origins of expectations of the SessionRepository.WhereFilter
type SessionRepositoryMockWhereFilterExpectationOrigins struct {
	origin       string
	originFilter string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) Optional() *mSessionRepositoryMockWhereFilter {
	mmWhereFilter.optional = true
	return mmWhereFilter
}

// Expect sets up expected params for SessionRepository.WhereFilter
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) Expect(filter mm_repositories.SessionFilter) *mSessionRepositoryMockWhereFilter {
	if mmWhereFilter.mock.funcWhereFilter != nil {
		mmWhereFilter.mock.t.Fatalf("SessionRepositoryMock.WhereFilter mock is already set by Set")
	}

	if mmWhereFilter.defaultExpectation == nil {
		mmWhereFilter.defaultExpectation = &SessionRepositoryMockWhereFilterExpectation{}
	}

	if mmWhereFilter.defaultExpectation.paramPtrs != nil {
		mmWhereFilter.mock.t.Fatalf("SessionRepositoryMock.WhereFilter mock is already set by ExpectParams functions")
	}

	mmWhereFilter.defaultExpectation.params = &SessionRepositoryMockWhereFilterParams{filter}
	mmWhereFilter.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmWhereFilter.expectations {
		if minimock.Equal(e.params, mmWhereFilter.defaultExpectation.params) {
			mmWhereFilter.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWhereFilter.defaultExpectation.params)
		}
	}

	return mmWhereFilter
}

// ExpectFilterParam1 sets up expected param filter for SessionRepository.WhereFilter
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) ExpectFilterParam1(filter mm_repositories.SessionFilter) *mSessionRepositoryMockWhereFilter {
	if mmWhereFilter.mock.funcWhereFilter != nil {
		mmWhereFilter.mock.t.Fatalf("SessionRepositoryMock.WhereFilter mock is already set by Set")
	}

	if mmWhereFilter.defaultExpectation == nil {
		mmWhereFilter.defaultExpectation = &SessionRepositoryMockWhereFilterExpectation{}
	}

	if mmWhereFilter.defaultExpectation.params != nil {
		mmWhereFilter.mock.t.Fatalf("SessionRepositoryMock.WhereFilter mock is already set by Expect")
	}

	if mmWhereFilter.defaultExpectation.paramPtrs == nil {
		mmWhereFilter.defaultExpectation.paramPtrs = &SessionRepositoryMockWhereFilterParamPtrs{}
	}
	mmWhereFilter.defaultExpectation.paramPtrs.filter = &filter
	mmWhereFilter.defaultExpectation.expectationOrigins.originFilter = minimock.CallerInfo(1)

	return mmWhereFilter
}

// Inspect accepts an inspector function that has same arguments as the SessionRepository.WhereFilter
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) Inspect(f func(filter mm_repositories.SessionFilter)) *mSessionRepositoryMockWhereFilter {
	if mmWhereFilter.mock.inspectFuncWhereFilter != nil {
		mmWhereFilter.mock.t.Fatalf("Inspect function is already set for SessionRepositoryMock.WhereFilter")
	}

	mmWhereFilter.mock.inspectFuncWhereFilter = f

	return mmWhereFilter
}

// Return sets up results that will be returned by SessionRepository.WhereFilter
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) Return(sa1 []models.Session, err error) *SessionRepositoryMock {
	if mmWhereFilter.mock.funcWhereFilter != nil {
		mmWhereFilter.mock.t.Fatalf("SessionRepositoryMock.WhereFilter mock is already set by Set")
	}

	if mmWhereFilter.defaultExpectation == nil {
		mmWhereFilter.defaultExpectation = &SessionRepositoryMockWhereFilterExpectation{mock: mmWhereFilter.mock}
	}
	mmWhereFilter.defaultExpectation.results = &SessionRepositoryMockWhereFilterResults{sa1, err}
	mmWhereFilter.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmWhereFilter.mock
}

// Set uses given function f to mock the SessionRepository.WhereFilter method
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) Set(f func(filter mm_repositories.SessionFilter) (sa1 []models.Session, err error)) *SessionRepositoryMock {
	if mmWhereFilter.defaultExpectation != nil {
		mmWhereFilter.mock.t.Fatalf("Default expectation is already set for the SessionRepository.WhereFilter method")
	}

	if len(mmWhereFilter.expectations) > 0 {
		mmWhereFilter.mock.t.Fatalf("Some expectations are already set for the SessionRepository.WhereFilter method")
	}

	mmWhereFilter.mock.funcWhereFilter = f
	mmWhereFilter.mock.funcWhereFilterOrigin = minimock.CallerInfo(1)
	return mmWhereFilter.mock
}

// When sets expectation for the SessionRepository.WhereFilter which will trigger the result defined by the following
// Then helper
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) When(filter mm_repositories.SessionFilter) *SessionRepositoryMockWhereFilterExpectation {
	if mmWhereFilter.mock.funcWhereFilter != nil {
		mmWhereFilter.mock.t.Fatalf("SessionRepositoryMock.WhereFilter mock is already set by Set")
	}

	expectation := &SessionRepositoryMockWhereFilterExpectation{
		mock:               mmWhereFilter.mock,
		params:             &SessionRepositoryMockWhereFilterParams{filter},
		expectationOrigins: SessionRepositoryMockWhereFilterExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmWhereFilter.expectations = append(mmWhereFilter.expectations, expectation)
	return expectation
}

// Then sets up SessionRepository.WhereFilter return parameters for the expectation previously defined by the When method
func (e *SessionRepositoryMockWhereFilterExpectation) Then(sa1 []models.Session, err error) *SessionRepositoryMock {
	e.results = &SessionRepositoryMockWhereFilterResults{sa1, err}
	return e.mock
}

// Times sets number of times SessionRepository.WhereFilter should be invoked
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) Times(n uint64) *mSessionRepositoryMockWhereFilter {
	if n == 0 {
		mmWhereFilter.mock.t.Fatalf("Times of SessionRepositoryMock.WhereFilter mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmWhereFilter.expectedInvocations, n)
	mmWhereFilter.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmWhereFilter
}

func (mmWhereFilter *mSessionRepositoryMockWhereFilter) invocationsDone() bool {
	if len(mmWhereFilter.expectations) == 0 && mmWhereFilter.defaultExpectation == nil && mmWhereFilter.mock.funcWhereFilter == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmWhereFilter.mock.afterWhereFilterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmWhereFilter.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// WhereFilter implements mm_repositories.SessionRepository
func (mmWhereFilter *SessionRepositoryMock) WhereFilter(filter mm_repositories.SessionFilter) (sa1 []models.Session, err error) {
	mm_atomic.AddUint64(&mmWhereFilter.beforeWhereFilterCounter, 1)
	defer mm_atomic.AddUint64(&mmWhereFilter.afterWhereFilterCounter, 1)

	mmWhereFilter.t.Helper()

	if mmWhereFilter.inspectFuncWhereFilter != nil {
		mmWhereFilter.inspectFuncWhereFilter(filter)
	}

	mm_params := SessionRepositoryMockWhereFilterParams{filter}

	// Record call args
	mmWhereFilter.WhereFilterMock.mutex.Lock()
	mmWhereFilter.WhereFilterMock.callArgs = append(mmWhereFilter.WhereFilterMock.callArgs, &mm_params)
	mmWhereFilter.WhereFilterMock.mutex.Unlock()

	for _, e := range mmWhereFilter.WhereFilterMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmWhereFilter.WhereFilterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWhereFilter.WhereFilterMock.defaultExpectation.Counter, 1)
		mm_want := mmWhereFilter.WhereFilterMock.defaultExpectation.params
		mm_want_ptrs := mmWhereFilter.WhereFilterMock.defaultExpectation.paramPtrs

		mm_got := SessionRepositoryMockWhereFilterParams{filter}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.filter != nil && !minimock.Equal(*mm_want_ptrs.filter, mm_got.filter) {
				mmWhereFilter.t.Errorf("SessionRepositoryMock.WhereFilter got unexpected parameter filter, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWhereFilter.WhereFilterMock.defaultExpectation.expectationOrigins.originFilter, *mm_want_ptrs.filter, mm_got.filter, minimock.Diff(*mm_want_ptrs.filter, mm_got.filter))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWhereFilter.t.Errorf("SessionRepositoryMock.WhereFilter got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmWhereFilter.WhereFilterMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWhereFilter.WhereFilterMock.defaultExpectation.results
		if mm_results == nil {
			mmWhereFilter.t.Fatal("No results are set for the SessionRepositoryMock.WhereFilter")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmWhereFilter.funcWhereFilter != nil {
		return mmWhereFilter.funcWhereFilter(filter)
	}
	mmWhereFilter.t.Fatalf("Unexpected call to SessionRepositoryMock.WhereFilter. %v", filter)
	return
}

// WhereFilterAfterCounter returns a count of finished SessionRepositoryMock.WhereFilter invocations
func (mmWhereFilter *SessionRepositoryMock) WhereFilterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWhereFilter.afterWhereFilterCounter)
}

// WhereFilterBeforeCounter returns a count of SessionRepositoryMock.WhereFilter invocations
func (mmWhereFilter *SessionRepositoryMock) WhereFilterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWhereFilter.beforeWhereFilterCounter)
}

// Calls returns a list of arguments used in each call to SessionRepositoryMock.WhereFilter.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWhereFilter *mSessionRepositoryMockWhereFilter) Calls() []*SessionRepositoryMockWhereFilterParams {
	mmWhereFilter.mutex.RLock()

	argCopy := make([]*SessionRepositoryMockWhereFilterParams, len(mmWhereFilter.callArgs))
	copy(argCopy, mmWhereFilter.callArgs)

	mmWhereFilter.mutex.RUnlock()

	return argCopy
}

// MinimockWhereFilterDone returns true if the count of the WhereFilter invocations corresponds
// the number of defined expectations
func (m *SessionRepositoryMock) MinimockWhereFilterDone() bool {
	if m.WhereFilterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.WhereFilterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.WhereFilterMock.invocationsDone()
}

// MinimockWhereFilterInspect logs each unmet expectation
func (m *SessionRepositoryMock) MinimockWhereFilterInspect() {
	for _, e := range m.WhereFilterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepositoryMock.WhereFilter at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterWhereFilterCounter := mm_atomic.LoadUint64(&m.afterWhereFilterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.WhereFilterMock.defaultExpectation != nil && afterWhereFilterCounter < 1 {
		if m.WhereFilterMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepositoryMock.WhereFilter at\n%s", m.WhereFilterMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepositoryMock.WhereFilter at\n%s with params: %#v", m.WhereFilterMock.defaultExpectation.expectationOrigins.origin, *m.WhereFilterMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWhereFilter != nil && afterWhereFilterCounter < 1 {
		m.t.Errorf("Expected call to SessionRepositoryMock.WhereFilter at\n%s", m.funcWhereFilterOrigin)
	}

	if !m.WhereFilterMock.invocationsDone() && afterWhereFilterCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepositoryMock.WhereFilter at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.WhereFilterMock.expectedInvocations), m.WhereFilterMock.expectedInvocationsOrigin, afterWhereFilterCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SessionRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()

			m.MinimockFilterInspect()

			m.MinimockGetByUUIDInspect()

			m.MinimockUpdateInspect()

			m.MinimockUpdatesInspect()

			m.MinimockWhereFilterInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SessionRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SessionRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone() &&
		m.MinimockFilterDone() &&
		m.MinimockGetByUUIDDone() &&
		m.MinimockUpdateDone() &&
		m.MinimockUpdatesDone() &&
		m.MinimockWhereFilterDone()
}
