// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i k071123/internal/services/parking_service/domain/repositories.TariffRepository -o tariff_repository_mock_test.go -n TariffRepositoryMock -p mocks

import (
	"k071123/internal/services/parking_service/domain/models"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TariffRepositoryMock implements mm_repositories.TariffRepository
type TariffRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(model *models.Tariff) (err error)
	funcAddOrigin    string
	inspectFuncAdd   func(model *models.Tariff)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mTariffRepositoryMockAdd

	funcGetByUUID          func(uuid string) (tp1 *models.Tariff, err error)
	funcGetByUUIDOrigin    string
	inspectFuncGetByUUID   func(uuid string)
	afterGetByUUIDCounter  uint64
	beforeGetByUUIDCounter uint64
	GetByUUIDMock          mTariffRepositoryMockGetByUUID
}

// NewTariffRepositoryMock returns a mock for mm_repositories.TariffRepository
func NewTariffRepositoryMock(t minimock.Tester) *TariffRepositoryMock {
	m := &TariffRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mTariffRepositoryMockAdd{mock: m}
	m.AddMock.callArgs = []*TariffRepositoryMockAddParams{}

	m.GetByUUIDMock = mTariffRepositoryMockGetByUUID{mock: m}
	m.GetByUUIDMock.callArgs = []*TariffRepositoryMockGetByUUIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTariffRepositoryMockAdd struct {
	optional           bool
	mock               *TariffRepositoryMock
	defaultExpectation *TariffRepositoryMockAddExpectation
	expectations       []*TariffRepositoryMockAddExpectation

	callArgs []*TariffRepositoryMockAddParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TariffRepositoryMockAddExpectation specifies expectation struct of the TariffRepository.Add
type TariffRepositoryMockAddExpectation struct {
	mock               *TariffRepositoryMock
	params             *TariffRepositoryMockAddParams
	paramPtrs          *TariffRepositoryMockAddParamPtrs
	expectationOrigins TariffRepositoryMockAddExpectationOrigins
	results            *TariffRepositoryMockAddResults
	returnOrigin       string
	Counter            uint64
}

// TariffRepositoryMockAddParams contains parameters of the TariffRepository.Add
type TariffRepositoryMockAddParams struct {
	model *models.Tariff
}

// TariffRepositoryMockAddParamPtrs contains pointers to parameters of the TariffRepository.Add
type TariffRepositoryMockAddParamPtrs struct {
	model **models.Tariff
}

// TariffRepositoryMockAddResults contains results of the TariffRepository.Add
type TariffRepositoryMockAddResults struct {
	err error
}

// TariffRepositoryMockAddOrigins contains origins of expectations of the TariffRepository.Add
type TariffRepositoryMockAddExpectationOrigins struct {
	origin      string
	originModel string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAdd *mTariffRepositoryMockAdd) Optional() *mTariffRepositoryMockAdd {
	mmAdd.optional = true
	return mmAdd
}

// Expect sets up expected params for TariffRepository.Add
func (mmAdd *mTariffRepositoryMockAdd) Expect(model *models.Tariff) *mTariffRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("TariffRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &TariffRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.paramPtrs != nil {
		mmAdd.mock.t.Fatalf("TariffRepositoryMock.Add mock is already set by ExpectParams functions")
	}

	mmAdd.defaultExpectation.params = &TariffRepositoryMockAddParams{model}
	mmAdd.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// ExpectModelParam1 sets up expected param model for TariffRepository.Add
func (mmAdd *mTariffRepositoryMockAdd) ExpectModelParam1(model *models.Tariff) *mTariffRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("TariffRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &TariffRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("TariffRepositoryMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &TariffRepositoryMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.model = &model
	mmAdd.defaultExpectation.expectationOrigins.originModel = minimock.CallerInfo(1)

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the TariffRepository.Add
func (mmAdd *mTariffRepositoryMockAdd) Inspect(f func(model *models.Tariff)) *mTariffRepositoryMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for TariffRepositoryMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by TariffRepository.Add
func (mmAdd *mTariffRepositoryMockAdd) Return(err error) *TariffRepositoryMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("TariffRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &TariffRepositoryMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &TariffRepositoryMockAddResults{err}
	mmAdd.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// Set uses given function f to mock the TariffRepository.Add method
func (mmAdd *mTariffRepositoryMockAdd) Set(f func(model *models.Tariff) (err error)) *TariffRepositoryMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the TariffRepository.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the TariffRepository.Add method")
	}

	mmAdd.mock.funcAdd = f
	mmAdd.mock.funcAddOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// When sets expectation for the TariffRepository.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mTariffRepositoryMockAdd) When(model *models.Tariff) *TariffRepositoryMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("TariffRepositoryMock.Add mock is already set by Set")
	}

	expectation := &TariffRepositoryMockAddExpectation{
		mock:               mmAdd.mock,
		params:             &TariffRepositoryMockAddParams{model},
		expectationOrigins: TariffRepositoryMockAddExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up TariffRepository.Add return parameters for the expectation previously defined by the When method
func (e *TariffRepositoryMockAddExpectation) Then(err error) *TariffRepositoryMock {
	e.results = &TariffRepositoryMockAddResults{err}
	return e.mock
}

// Times sets number of times TariffRepository.Add should be invoked
func (mmAdd *mTariffRepositoryMockAdd) Times(n uint64) *mTariffRepositoryMockAdd {
	if n == 0 {
		mmAdd.mock.t.Fatalf("Times of TariffRepositoryMock.Add mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAdd.expectedInvocations, n)
	mmAdd.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAdd
}

func (mmAdd *mTariffRepositoryMockAdd) invocationsDone() bool {
	if len(mmAdd.expectations) == 0 && mmAdd.defaultExpectation == nil && mmAdd.mock.funcAdd == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAdd.mock.afterAddCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAdd.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Add implements mm_repositories.TariffRepository
func (mmAdd *TariffRepositoryMock) Add(model *models.Tariff) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	mmAdd.t.Helper()

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(model)
	}

	mm_params := TariffRepositoryMockAddParams{model}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_want_ptrs := mmAdd.AddMock.defaultExpectation.paramPtrs

		mm_got := TariffRepositoryMockAddParams{model}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.model != nil && !minimock.Equal(*mm_want_ptrs.model, mm_got.model) {
				mmAdd.t.Errorf("TariffRepositoryMock.Add got unexpected parameter model, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originModel, *mm_want_ptrs.model, mm_got.model, minimock.Diff(*mm_want_ptrs.model, mm_got.model))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("TariffRepositoryMock.Add got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAdd.AddMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results == nil {
			mmAdd.t.Fatal("No results are set for the TariffRepositoryMock.Add")
		}
		return (*mm_results).err
	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(model)
	}
	mmAdd.t.Fatalf("Unexpected call to TariffRepositoryMock.Add. %v", model)
	return
}

// AddAfterCounter returns a count of finished TariffRepositoryMock.Add invocations
func (mmAdd *TariffRepositoryMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of TariffRepositoryMock.Add invocations
func (mmAdd *TariffRepositoryMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to TariffRepositoryMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mTariffRepositoryMockAdd) Calls() []*TariffRepositoryMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*TariffRepositoryMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *TariffRepositoryMock) MinimockAddDone() bool {
	if m.AddMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddMock.invocationsDone()
}

// MinimockAddInspect logs each unmet expectation
func (m *TariffRepositoryMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TariffRepositoryMock.Add at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddCounter := mm_atomic.LoadUint64(&m.afterAddCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && afterAddCounter < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TariffRepositoryMock.Add at\n%s", m.AddMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TariffRepositoryMock.Add at\n%s with params: %#v", m.AddMock.defaultExpectation.expectationOrigins.origin, *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && afterAddCounter < 1 {
		m.t.Errorf("Expected call to TariffRepositoryMock.Add at\n%s", m.funcAddOrigin)
	}

	if !m.AddMock.invocationsDone() && afterAddCounter > 0 {
		m.t.Errorf("Expected %d calls to TariffRepositoryMock.Add at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddMock.expectedInvocations), m.AddMock.expectedInvocationsOrigin, afterAddCounter)
	}
}

type mTariffRepositoryMockGetByUUID struct {
	optional           bool
	mock               *TariffRepositoryMock
	defaultExpectation *TariffRepositoryMockGetByUUIDExpectation
	expectations       []*TariffRepositoryMockGetByUUIDExpectation

	callArgs []*TariffRepositoryMockGetByUUIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TariffRepositoryMockGetByUUIDExpectation specifies expectation struct of the TariffRepository.GetByUUID
type TariffRepositoryMockGetByUUIDExpectation struct {
	mock               *TariffRepositoryMock
	params             *TariffRepositoryMockGetByUUIDParams
	paramPtrs          *TariffRepositoryMockGetByUUIDParamPtrs
	expectationOrigins TariffRepositoryMockGetByUUIDExpectationOrigins
	results            *TariffRepositoryMockGetByUUIDResults
	returnOrigin       string
	Counter            uint64
}

// TariffRepositoryMockGetByUUIDParams contains parameters of the TariffRepository.GetByUUID
type TariffRepositoryMockGetByUUIDParams struct {
	uuid string
}

// TariffRepositoryMockGetByUUIDParamPtrs contains pointers to parameters of the TariffRepository.GetByUUID
type TariffRepositoryMockGetByUUIDParamPtrs struct {
	uuid *string
}

// TariffRepositoryMockGetByUUIDResults contains results of the TariffRepository.GetByUUID
type TariffRepositoryMockGetByUUIDResults struct {
	tp1 *models.Tariff
	err error
}

// TariffRepositoryMockGetByUUIDOrigins contains origins of expectations of the TariffRepository.GetByUUID
type TariffRepositoryMockGetByUUIDExpectationOrigins struct {
	origin     string
	originUuid string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) Optional() *mTariffRepositoryMockGetByUUID {
	mmGetByUUID.optional = true
	return mmGetByUUID
}

// Expect sets up expected params for TariffRepository.GetByUUID
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) Expect(uuid string) *mTariffRepositoryMockGetByUUID {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("TariffRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &TariffRepositoryMockGetByUUIDExpectation{}
	}

	if mmGetByUUID.defaultExpectation.paramPtrs != nil {
		mmGetByUUID.mock.t.Fatalf("TariffRepositoryMock.GetByUUID mock is already set by ExpectParams functions")
	}

	mmGetByUUID.defaultExpectation.params = &TariffRepositoryMockGetByUUIDParams{uuid}
	mmGetByUUID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByUUID.expectations {
		if minimock.Equal(e.params, mmGetByUUID.defaultExpectation.params) {
			mmGetByUUID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByUUID.defaultExpectation.params)
		}
	}

	return mmGetByUUID
}

// ExpectUuidParam1 sets up expected param uuid for TariffRepository.GetByUUID
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) ExpectUuidParam1(uuid string) *mTariffRepositoryMockGetByUUID {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("TariffRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &TariffRepositoryMockGetByUUIDExpectation{}
	}

	if mmGetByUUID.defaultExpectation.params != nil {
		mmGetByUUID.mock.t.Fatalf("TariffRepositoryMock.GetByUUID mock is already set by Expect")
	}

	if mmGetByUUID.defaultExpectation.paramPtrs == nil {
		mmGetByUUID.defaultExpectation.paramPtrs = &TariffRepositoryMockGetByUUIDParamPtrs{}
	}
	mmGetByUUID.defaultExpectation.paramPtrs.uuid = &uuid
	mmGetByUUID.defaultExpectation.expectationOrigins.originUuid = minimock.CallerInfo(1)

	return mmGetByUUID
}

// Inspect accepts an inspector function that has same arguments as the TariffRepository.GetByUUID
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) Inspect(f func(uuid string)) *mTariffRepositoryMockGetByUUID {
	if mmGetByUUID.mock.inspectFuncGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("Inspect function is already set for TariffRepositoryMock.GetByUUID")
	}

	mmGetByUUID.mock.inspectFuncGetByUUID = f

	return mmGetByUUID
}

// Return sets up results that will be returned by TariffRepository.GetByUUID
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) Return(tp1 *models.Tariff, err error) *TariffRepositoryMock {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("TariffRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &TariffRepositoryMockGetByUUIDExpectation{mock: mmGetByUUID.mock}
	}
	mmGetByUUID.defaultExpectation.results = &TariffRepositoryMockGetByUUIDResults{tp1, err}
	mmGetByUUID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByUUID.mock
}

// Set uses given function f to mock the TariffRepository.GetByUUID method
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) Set(f func(uuid string) (tp1 *models.Tariff, err error)) *TariffRepositoryMock {
	if mmGetByUUID.defaultExpectation != nil {
		mmGetByUUID.mock.t.Fatalf("Default expectation is already set for the TariffRepository.GetByUUID method")
	}

	if len(mmGetByUUID.expectations) > 0 {
		mmGetByUUID.mock.t.Fatalf("Some expectations are already set for the TariffRepository.GetByUUID method")
	}

	mmGetByUUID.mock.funcGetByUUID = f
	mmGetByUUID.mock.funcGetByUUIDOrigin = minimock.CallerInfo(1)
	return mmGetByUUID.mock
}

// When sets expectation for the TariffRepository.GetByUUID which will trigger the result defined by the following
// Then helper
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) When(uuid string) *TariffRepositoryMockGetByUUIDExpectation {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("TariffRepositoryMock.GetByUUID mock is already set by Set")
	}

	expectation := &TariffRepositoryMockGetByUUIDExpectation{
		mock:               mmGetByUUID.mock,
		params:             &TariffRepositoryMockGetByUUIDParams{uuid},
		expectationOrigins: TariffRepositoryMockGetByUUIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByUUID.expectations = append(mmGetByUUID.expectations, expectation)
	return expectation
}

// Then sets up TariffRepository.GetByUUID return parameters for the expectation previously defined by the When method
func (e *TariffRepositoryMockGetByUUIDExpectation) Then(tp1 *models.Tariff, err error) *TariffRepositoryMock {
	e.results = &TariffRepositoryMockGetByUUIDResults{tp1, err}
	return e.mock
}

// Times sets number of times TariffRepository.GetByUUID should be invoked
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) Times(n uint64) *mTariffRepositoryMockGetByUUID {
	if n == 0 {
		mmGetByUUID.mock.t.Fatalf("Times of TariffRepositoryMock.GetByUUID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByUUID.expectedInvocations, n)
	mmGetByUUID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByUUID
}

func (mmGetByUUID *mTariffRepositoryMockGetByUUID) invocationsDone() bool {
	if len(mmGetByUUID.expectations) == 0 && mmGetByUUID.defaultExpectation == nil && mmGetByUUID.mock.funcGetByUUID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByUUID.mock.afterGetByUUIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByUUID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByUUID implements mm_repositories.TariffRepository
func (mmGetByUUID *TariffRepositoryMock) GetByUUID(uuid string) (tp1 *models.Tariff, err error) {
	mm_atomic.AddUint64(&mmGetByUUID.beforeGetByUUIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByUUID.afterGetByUUIDCounter, 1)

	mmGetByUUID.t.Helper()

	if mmGetByUUID.inspectFuncGetByUUID != nil {
		mmGetByUUID.inspectFuncGetByUUID(uuid)
	}

	mm_params := TariffRepositoryMockGetByUUIDParams{uuid}

	// Record call args
	mmGetByUUID.GetByUUIDMock.mutex.Lock()
	mmGetByUUID.GetByUUIDMock.callArgs = append(mmGetByUUID.GetByUUIDMock.callArgs, &mm_params)
	mmGetByUUID.GetByUUIDMock.mutex.Unlock()

	for _, e := range mmGetByUUID.GetByUUIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.tp1, e.results.err
		}
	}

	if mmGetByUUID.GetByUUIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByUUID.GetByUUIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByUUID.GetByUUIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByUUID.GetByUUIDMock.defaultExpectation.paramPtrs

		mm_got := TariffRepositoryMockGetByUUIDParams{uuid}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.uuid != nil && !minimock.Equal(*mm_want_ptrs.uuid, mm_got.uuid) {
				mmGetByUUID.t.Errorf("TariffRepositoryMock.GetByUUID got unexpected parameter uuid, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByUUID.GetByUUIDMock.defaultExpectation.expectationOrigins.originUuid, *mm_want_ptrs.uuid, mm_got.uuid, minimock.Diff(*mm_want_ptrs.uuid, mm_got.uuid))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByUUID.t.Errorf("TariffRepositoryMock.GetByUUID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByUUID.GetByUUIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByUUID.GetByUUIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByUUID.t.Fatal("No results are set for the TariffRepositoryMock.GetByUUID")
		}
		return (*mm_results).tp1, (*mm_results).err
	}
	if mmGetByUUID.funcGetByUUID != nil {
		return mmGetByUUID.funcGetByUUID(uuid)
	}
	mmGetByUUID.t.Fatalf("Unexpected call to TariffRepositoryMock.GetByUUID. %v", uuid)
	return
}

// GetByUUIDAfterCounter returns a count of finished TariffRepositoryMock.GetByUUID invocations
func (mmGetByUUID *TariffRepositoryMock) GetByUUIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUUID.afterGetByUUIDCounter)
}

// GetByUUIDBeforeCounter returns a count of TariffRepositoryMock.GetByUUID invocations
func (mmGetByUUID *TariffRepositoryMock) GetByUUIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUUID.beforeGetByUUIDCounter)
}

// Calls returns a list of arguments used in each call to TariffRepositoryMock.GetByUUID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByUUID *mTariffRepositoryMockGetByUUID) Calls() []*TariffRepositoryMockGetByUUIDParams {
	mmGetByUUID.mutex.RLock()

	argCopy := make([]*TariffRepositoryMockGetByUUIDParams, len(mmGetByUUID.callArgs))
	copy(argCopy, mmGetByUUID.callArgs)

	mmGetByUUID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByUUIDDone returns true if the count of the GetByUUID invocations corresponds
// the number of defined expectations
func (m *TariffRepositoryMock) MinimockGetByUUIDDone() bool {
	if m.GetByUUIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByUUIDMock.invocationsDone()
}

// MinimockGetByUUIDInspect logs each unmet expectation
func (m *TariffRepositoryMock) MinimockGetByUUIDInspect() {
	for _, e := range m.GetByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TariffRepositoryMock.GetByUUID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByUUIDCounter := mm_atomic.LoadUint64(&m.afterGetByUUIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByUUIDMock.defaultExpectation != nil && afterGetByUUIDCounter < 1 {
		if m.GetByUUIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TariffRepositoryMock.GetByUUID at\n%s", m.GetByUUIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TariffRepositoryMock.GetByUUID at\n%s with params: %#v", m.GetByUUIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByUUIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByUUID != nil && afterGetByUUIDCounter < 1 {
		m.t.Errorf("Expected call to TariffRepositoryMock.GetByUUID at\n%s", m.funcGetByUUIDOrigin)
	}

	if !m.GetByUUIDMock.invocationsDone() && afterGetByUUIDCounter > 0 {
		m.t.Errorf("Expected %d calls to TariffRepositoryMock.GetByUUID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByUUIDMock.expectedInvocations), m.GetByUUIDMock.expectedInvocationsOrigin, afterGetByUUIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TariffRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()

			m.MinimockGetByUUIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TariffRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TariffRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone() &&
		m.MinimockGetByUUIDDone()
}
