// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i k071123/internal/services/parking_service/domain/repositories.UnitRepository -o unit_repository_mock_test.go -n UnitRepositoryMock -p mocks

import (
	"k071123/internal/services/parking_service/domain/models"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UnitRepositoryMock implements mm_repositories.UnitRepository
type UnitRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAdd          func(model *models.Unit) (err error)
	funcAddOrigin    string
	inspectFuncAdd   func(model *models.Unit)
	afterAddCounter  uint64
	beforeAddCounter uint64
	AddMock          mUnitRepositoryMockAdd

	funcGetByUUID          func(uuid string) (up1 *models.Unit, err error)
	funcGetByUUIDOrigin    string
	inspectFuncGetByUUID   func(uuid string)
	afterGetByUUIDCounter  uint64
	beforeGetByUUIDCounter uint64
	GetByUUIDMock          mUnitRepositoryMockGetByUUID
}

// NewUnitRepositoryMock returns a mock for mm_repositories.UnitRepository
func NewUnitRepositoryMock(t minimock.Tester) *UnitRepositoryMock {
	m := &UnitRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddMock = mUnitRepositoryMockAdd{mock: m}
	m.AddMock.callArgs = []*UnitRepositoryMockAddParams{}

	m.GetByUUIDMock = mUnitRepositoryMockGetByUUID{mock: m}
	m.GetByUUIDMock.callArgs = []*UnitRepositoryMockGetByUUIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUnitRepositoryMockAdd struct {
	optional           bool
	mock               *UnitRepositoryMock
	defaultExpectation *UnitRepositoryMockAddExpectation
	expectations       []*UnitRepositoryMockAddExpectation

	callArgs []*UnitRepositoryMockAddParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UnitRepositoryMockAddExpectation specifies expectation struct of the UnitRepository.Add
type UnitRepositoryMockAddExpectation struct {
	mock               *UnitRepositoryMock
	params             *UnitRepositoryMockAddParams
	paramPtrs          *UnitRepositoryMockAddParamPtrs
	expectationOrigins UnitRepositoryMockAddExpectationOrigins
	results            *UnitRepositoryMockAddResults
	returnOrigin       string
	Counter            uint64
}

// UnitRepositoryMockAddParams contains parameters of the UnitRepository.Add
type UnitRepositoryMockAddParams struct {
	model *models.Unit
}

// UnitRepositoryMockAddParamPtrs contains pointers to parameters of the UnitRepository.Add
type UnitRepositoryMockAddParamPtrs struct {
	model **models.Unit
}

// UnitRepositoryMockAddResults contains results of the UnitRepository.Add
type UnitRepositoryMockAddResults struct {
	err error
}

// UnitRepositoryMockAddOrigins contains origins of expectations of the UnitRepository.Add
type UnitRepositoryMockAddExpectationOrigins struct {
	origin      string
	originModel string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAdd *mUnitRepositoryMockAdd) Optional() *mUnitRepositoryMockAdd {
	mmAdd.optional = true
	return mmAdd
}

// Expect sets up expected params for UnitRepository.Add
func (mmAdd *mUnitRepositoryMockAdd) Expect(model *models.Unit) *mUnitRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UnitRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &UnitRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.paramPtrs != nil {
		mmAdd.mock.t.Fatalf("UnitRepositoryMock.Add mock is already set by ExpectParams functions")
	}

	mmAdd.defaultExpectation.params = &UnitRepositoryMockAddParams{model}
	mmAdd.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAdd.expectations {
		if minimock.Equal(e.params, mmAdd.defaultExpectation.params) {
			mmAdd.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAdd.defaultExpectation.params)
		}
	}

	return mmAdd
}

// ExpectModelParam1 sets up expected param model for UnitRepository.Add
func (mmAdd *mUnitRepositoryMockAdd) ExpectModelParam1(model *models.Unit) *mUnitRepositoryMockAdd {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UnitRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &UnitRepositoryMockAddExpectation{}
	}

	if mmAdd.defaultExpectation.params != nil {
		mmAdd.mock.t.Fatalf("UnitRepositoryMock.Add mock is already set by Expect")
	}

	if mmAdd.defaultExpectation.paramPtrs == nil {
		mmAdd.defaultExpectation.paramPtrs = &UnitRepositoryMockAddParamPtrs{}
	}
	mmAdd.defaultExpectation.paramPtrs.model = &model
	mmAdd.defaultExpectation.expectationOrigins.originModel = minimock.CallerInfo(1)

	return mmAdd
}

// Inspect accepts an inspector function that has same arguments as the UnitRepository.Add
func (mmAdd *mUnitRepositoryMockAdd) Inspect(f func(model *models.Unit)) *mUnitRepositoryMockAdd {
	if mmAdd.mock.inspectFuncAdd != nil {
		mmAdd.mock.t.Fatalf("Inspect function is already set for UnitRepositoryMock.Add")
	}

	mmAdd.mock.inspectFuncAdd = f

	return mmAdd
}

// Return sets up results that will be returned by UnitRepository.Add
func (mmAdd *mUnitRepositoryMockAdd) Return(err error) *UnitRepositoryMock {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UnitRepositoryMock.Add mock is already set by Set")
	}

	if mmAdd.defaultExpectation == nil {
		mmAdd.defaultExpectation = &UnitRepositoryMockAddExpectation{mock: mmAdd.mock}
	}
	mmAdd.defaultExpectation.results = &UnitRepositoryMockAddResults{err}
	mmAdd.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// Set uses given function f to mock the UnitRepository.Add method
func (mmAdd *mUnitRepositoryMockAdd) Set(f func(model *models.Unit) (err error)) *UnitRepositoryMock {
	if mmAdd.defaultExpectation != nil {
		mmAdd.mock.t.Fatalf("Default expectation is already set for the UnitRepository.Add method")
	}

	if len(mmAdd.expectations) > 0 {
		mmAdd.mock.t.Fatalf("Some expectations are already set for the UnitRepository.Add method")
	}

	mmAdd.mock.funcAdd = f
	mmAdd.mock.funcAddOrigin = minimock.CallerInfo(1)
	return mmAdd.mock
}

// When sets expectation for the UnitRepository.Add which will trigger the result defined by the following
// Then helper
func (mmAdd *mUnitRepositoryMockAdd) When(model *models.Unit) *UnitRepositoryMockAddExpectation {
	if mmAdd.mock.funcAdd != nil {
		mmAdd.mock.t.Fatalf("UnitRepositoryMock.Add mock is already set by Set")
	}

	expectation := &UnitRepositoryMockAddExpectation{
		mock:               mmAdd.mock,
		params:             &UnitRepositoryMockAddParams{model},
		expectationOrigins: UnitRepositoryMockAddExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAdd.expectations = append(mmAdd.expectations, expectation)
	return expectation
}

// Then sets up UnitRepository.Add return parameters for the expectation previously defined by the When method
func (e *UnitRepositoryMockAddExpectation) Then(err error) *UnitRepositoryMock {
	e.results = &UnitRepositoryMockAddResults{err}
	return e.mock
}

// Times sets number of times UnitRepository.Add should be invoked
func (mmAdd *mUnitRepositoryMockAdd) Times(n uint64) *mUnitRepositoryMockAdd {
	if n == 0 {
		mmAdd.mock.t.Fatalf("Times of UnitRepositoryMock.Add mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAdd.expectedInvocations, n)
	mmAdd.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAdd
}

func (mmAdd *mUnitRepositoryMockAdd) invocationsDone() bool {
	if len(mmAdd.expectations) == 0 && mmAdd.defaultExpectation == nil && mmAdd.mock.funcAdd == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAdd.mock.afterAddCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAdd.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Add implements mm_repositories.UnitRepository
func (mmAdd *UnitRepositoryMock) Add(model *models.Unit) (err error) {
	mm_atomic.AddUint64(&mmAdd.beforeAddCounter, 1)
	defer mm_atomic.AddUint64(&mmAdd.afterAddCounter, 1)

	mmAdd.t.Helper()

	if mmAdd.inspectFuncAdd != nil {
		mmAdd.inspectFuncAdd(model)
	}

	mm_params := UnitRepositoryMockAddParams{model}

	// Record call args
	mmAdd.AddMock.mutex.Lock()
	mmAdd.AddMock.callArgs = append(mmAdd.AddMock.callArgs, &mm_params)
	mmAdd.AddMock.mutex.Unlock()

	for _, e := range mmAdd.AddMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAdd.AddMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAdd.AddMock.defaultExpectation.Counter, 1)
		mm_want := mmAdd.AddMock.defaultExpectation.params
		mm_want_ptrs := mmAdd.AddMock.defaultExpectation.paramPtrs

		mm_got := UnitRepositoryMockAddParams{model}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.model != nil && !minimock.Equal(*mm_want_ptrs.model, mm_got.model) {
				mmAdd.t.Errorf("UnitRepositoryMock.Add got unexpected parameter model, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAdd.AddMock.defaultExpectation.expectationOrigins.originModel, *mm_want_ptrs.model, mm_got.model, minimock.Diff(*mm_want_ptrs.model, mm_got.model))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAdd.t.Errorf("UnitRepositoryMock.Add got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAdd.AddMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAdd.AddMock.defaultExpectation.results
		if mm_results == nil {
			mmAdd.t.Fatal("No results are set for the UnitRepositoryMock.Add")
		}
		return (*mm_results).err
	}
	if mmAdd.funcAdd != nil {
		return mmAdd.funcAdd(model)
	}
	mmAdd.t.Fatalf("Unexpected call to UnitRepositoryMock.Add. %v", model)
	return
}

// AddAfterCounter returns a count of finished UnitRepositoryMock.Add invocations
func (mmAdd *UnitRepositoryMock) AddAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.afterAddCounter)
}

// AddBeforeCounter returns a count of UnitRepositoryMock.Add invocations
func (mmAdd *UnitRepositoryMock) AddBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAdd.beforeAddCounter)
}

// Calls returns a list of arguments used in each call to UnitRepositoryMock.Add.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAdd *mUnitRepositoryMockAdd) Calls() []*UnitRepositoryMockAddParams {
	mmAdd.mutex.RLock()

	argCopy := make([]*UnitRepositoryMockAddParams, len(mmAdd.callArgs))
	copy(argCopy, mmAdd.callArgs)

	mmAdd.mutex.RUnlock()

	return argCopy
}

// MinimockAddDone returns true if the count of the Add invocations corresponds
// the number of defined expectations
func (m *UnitRepositoryMock) MinimockAddDone() bool {
	if m.AddMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddMock.invocationsDone()
}

// MinimockAddInspect logs each unmet expectation
func (m *UnitRepositoryMock) MinimockAddInspect() {
	for _, e := range m.AddMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UnitRepositoryMock.Add at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddCounter := mm_atomic.LoadUint64(&m.afterAddCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddMock.defaultExpectation != nil && afterAddCounter < 1 {
		if m.AddMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UnitRepositoryMock.Add at\n%s", m.AddMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UnitRepositoryMock.Add at\n%s with params: %#v", m.AddMock.defaultExpectation.expectationOrigins.origin, *m.AddMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAdd != nil && afterAddCounter < 1 {
		m.t.Errorf("Expected call to UnitRepositoryMock.Add at\n%s", m.funcAddOrigin)
	}

	if !m.AddMock.invocationsDone() && afterAddCounter > 0 {
		m.t.Errorf("Expected %d calls to UnitRepositoryMock.Add at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddMock.expectedInvocations), m.AddMock.expectedInvocationsOrigin, afterAddCounter)
	}
}

type mUnitRepositoryMockGetByUUID struct {
	optional           bool
	mock               *UnitRepositoryMock
	defaultExpectation *UnitRepositoryMockGetByUUIDExpectation
	expectations       []*UnitRepositoryMockGetByUUIDExpectation

	callArgs []*UnitRepositoryMockGetByUUIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UnitRepositoryMockGetByUUIDExpectation specifies expectation struct of the UnitRepository.GetByUUID
type UnitRepositoryMockGetByUUIDExpectation struct {
	mock               *UnitRepositoryMock
	params             *UnitRepositoryMockGetByUUIDParams
	paramPtrs          *UnitRepositoryMockGetByUUIDParamPtrs
	expectationOrigins UnitRepositoryMockGetByUUIDExpectationOrigins
	results            *UnitRepositoryMockGetByUUIDResults
	returnOrigin       string
	Counter            uint64
}

// UnitRepositoryMockGetByUUIDParams contains parameters of the UnitRepository.GetByUUID
type UnitRepositoryMockGetByUUIDParams struct {
	uuid string
}

// UnitRepositoryMockGetByUUIDParamPtrs contains pointers to parameters of the UnitRepository.GetByUUID
type UnitRepositoryMockGetByUUIDParamPtrs struct {
	uuid *string
}

// UnitRepositoryMockGetByUUIDResults contains results of the UnitRepository.GetByUUID
type UnitRepositoryMockGetByUUIDResults struct {
	up1 *models.Unit
	err error
}

// UnitRepositoryMockGetByUUIDOrigins contains origins of expectations of the UnitRepository.GetByUUID
type UnitRepositoryMockGetByUUIDExpectationOrigins struct {
	origin     string
	originUuid string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) Optional() *mUnitRepositoryMockGetByUUID {
	mmGetByUUID.optional = true
	return mmGetByUUID
}

// Expect sets up expected params for UnitRepository.GetByUUID
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) Expect(uuid string) *mUnitRepositoryMockGetByUUID {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("UnitRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &UnitRepositoryMockGetByUUIDExpectation{}
	}

	if mmGetByUUID.defaultExpectation.paramPtrs != nil {
		mmGetByUUID.mock.t.Fatalf("UnitRepositoryMock.GetByUUID mock is already set by ExpectParams functions")
	}

	mmGetByUUID.defaultExpectation.params = &UnitRepositoryMockGetByUUIDParams{uuid}
	mmGetByUUID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByUUID.expectations {
		if minimock.Equal(e.params, mmGetByUUID.defaultExpectation.params) {
			mmGetByUUID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByUUID.defaultExpectation.params)
		}
	}

	return mmGetByUUID
}

// ExpectUuidParam1 sets up expected param uuid for UnitRepository.GetByUUID
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) ExpectUuidParam1(uuid string) *mUnitRepositoryMockGetByUUID {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("UnitRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &UnitRepositoryMockGetByUUIDExpectation{}
	}

	if mmGetByUUID.defaultExpectation.params != nil {
		mmGetByUUID.mock.t.Fatalf("UnitRepositoryMock.GetByUUID mock is already set by Expect")
	}

	if mmGetByUUID.defaultExpectation.paramPtrs == nil {
		mmGetByUUID.defaultExpectation.paramPtrs = &UnitRepositoryMockGetByUUIDParamPtrs{}
	}
	mmGetByUUID.defaultExpectation.paramPtrs.uuid = &uuid
	mmGetByUUID.defaultExpectation.expectationOrigins.originUuid = minimock.CallerInfo(1)

	return mmGetByUUID
}

// Inspect accepts an inspector function that has same arguments as the UnitRepository.GetByUUID
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) Inspect(f func(uuid string)) *mUnitRepositoryMockGetByUUID {
	if mmGetByUUID.mock.inspectFuncGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("Inspect function is already set for UnitRepositoryMock.GetByUUID")
	}

	mmGetByUUID.mock.inspectFuncGetByUUID = f

	return mmGetByUUID
}

// Return sets up results that will be returned by UnitRepository.GetByUUID
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) Return(up1 *models.Unit, err error) *UnitRepositoryMock {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("UnitRepositoryMock.GetByUUID mock is already set by Set")
	}

	if mmGetByUUID.defaultExpectation == nil {
		mmGetByUUID.defaultExpectation = &UnitRepositoryMockGetByUUIDExpectation{mock: mmGetByUUID.mock}
	}
	mmGetByUUID.defaultExpectation.results = &UnitRepositoryMockGetByUUIDResults{up1, err}
	mmGetByUUID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByUUID.mock
}

// Set uses given function f to mock the UnitRepository.GetByUUID method
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) Set(f func(uuid string) (up1 *models.Unit, err error)) *UnitRepositoryMock {
	if mmGetByUUID.defaultExpectation != nil {
		mmGetByUUID.mock.t.Fatalf("Default expectation is already set for the UnitRepository.GetByUUID method")
	}

	if len(mmGetByUUID.expectations) > 0 {
		mmGetByUUID.mock.t.Fatalf("Some expectations are already set for the UnitRepository.GetByUUID method")
	}

	mmGetByUUID.mock.funcGetByUUID = f
	mmGetByUUID.mock.funcGetByUUIDOrigin = minimock.CallerInfo(1)
	return mmGetByUUID.mock
}

// When sets expectation for the UnitRepository.GetByUUID which will trigger the result defined by the following
// Then helper
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) When(uuid string) *UnitRepositoryMockGetByUUIDExpectation {
	if mmGetByUUID.mock.funcGetByUUID != nil {
		mmGetByUUID.mock.t.Fatalf("UnitRepositoryMock.GetByUUID mock is already set by Set")
	}

	expectation := &UnitRepositoryMockGetByUUIDExpectation{
		mock:               mmGetByUUID.mock,
		params:             &UnitRepositoryMockGetByUUIDParams{uuid},
		expectationOrigins: UnitRepositoryMockGetByUUIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByUUID.expectations = append(mmGetByUUID.expectations, expectation)
	return expectation
}

// Then sets up UnitRepository.GetByUUID return parameters for the expectation previously defined by the When method
func (e *UnitRepositoryMockGetByUUIDExpectation) Then(up1 *models.Unit, err error) *UnitRepositoryMock {
	e.results = &UnitRepositoryMockGetByUUIDResults{up1, err}
	return e.mock
}

// Times sets number of times UnitRepository.GetByUUID should be invoked
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) Times(n uint64) *mUnitRepositoryMockGetByUUID {
	if n == 0 {
		mmGetByUUID.mock.t.Fatalf("Times of UnitRepositoryMock.GetByUUID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByUUID.expectedInvocations, n)
	mmGetByUUID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByUUID
}

func (mmGetByUUID *mUnitRepositoryMockGetByUUID) invocationsDone() bool {
	if len(mmGetByUUID.expectations) == 0 && mmGetByUUID.defaultExpectation == nil && mmGetByUUID.mock.funcGetByUUID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByUUID.mock.afterGetByUUIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByUUID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByUUID implements mm_repositories.UnitRepository
func (mmGetByUUID *UnitRepositoryMock) GetByUUID(uuid string) (up1 *models.Unit, err error) {
	mm_atomic.AddUint64(&mmGetByUUID.beforeGetByUUIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByUUID.afterGetByUUIDCounter, 1)

	mmGetByUUID.t.Helper()

	if mmGetByUUID.inspectFuncGetByUUID != nil {
		mmGetByUUID.inspectFuncGetByUUID(uuid)
	}

	mm_params := UnitRepositoryMockGetByUUIDParams{uuid}

	// Record call args
	mmGetByUUID.GetByUUIDMock.mutex.Lock()
	mmGetByUUID.GetByUUIDMock.callArgs = append(mmGetByUUID.GetByUUIDMock.callArgs, &mm_params)
	mmGetByUUID.GetByUUIDMock.mutex.Unlock()

	for _, e := range mmGetByUUID.GetByUUIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetByUUID.GetByUUIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByUUID.GetByUUIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByUUID.GetByUUIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByUUID.GetByUUIDMock.defaultExpectation.paramPtrs

		mm_got := UnitRepositoryMockGetByUUIDParams{uuid}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.uuid != nil && !minimock.Equal(*mm_want_ptrs.uuid, mm_got.uuid) {
				mmGetByUUID.t.Errorf("UnitRepositoryMock.GetByUUID got unexpected parameter uuid, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByUUID.GetByUUIDMock.defaultExpectation.expectationOrigins.originUuid, *mm_want_ptrs.uuid, mm_got.uuid, minimock.Diff(*mm_want_ptrs.uuid, mm_got.uuid))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByUUID.t.Errorf("UnitRepositoryMock.GetByUUID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByUUID.GetByUUIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByUUID.GetByUUIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByUUID.t.Fatal("No results are set for the UnitRepositoryMock.GetByUUID")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetByUUID.funcGetByUUID != nil {
		return mmGetByUUID.funcGetByUUID(uuid)
	}
	mmGetByUUID.t.Fatalf("Unexpected call to UnitRepositoryMock.GetByUUID. %v", uuid)
	return
}

// GetByUUIDAfterCounter returns a count of finished UnitRepositoryMock.GetByUUID invocations
func (mmGetByUUID *UnitRepositoryMock) GetByUUIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUUID.afterGetByUUIDCounter)
}

// GetByUUIDBeforeCounter returns a count of UnitRepositoryMock.GetByUUID invocations
func (mmGetByUUID *UnitRepositoryMock) GetByUUIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByUUID.beforeGetByUUIDCounter)
}

// Calls returns a list of arguments used in each call to UnitRepositoryMock.GetByUUID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByUUID *mUnitRepositoryMockGetByUUID) Calls() []*UnitRepositoryMockGetByUUIDParams {
	mmGetByUUID.mutex.RLock()

	argCopy := make([]*UnitRepositoryMockGetByUUIDParams, len(mmGetByUUID.callArgs))
	copy(argCopy, mmGetByUUID.callArgs)

	mmGetByUUID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByUUIDDone returns true if the count of the GetByUUID invocations corresponds
// the number of defined expectations
func (m *UnitRepositoryMock) MinimockGetByUUIDDone() bool {
	if m.GetByUUIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByUUIDMock.invocationsDone()
}

// MinimockGetByUUIDInspect logs each unmet expectation
func (m *UnitRepositoryMock) MinimockGetByUUIDInspect() {
	for _, e := range m.GetByUUIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UnitRepositoryMock.GetByUUID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByUUIDCounter := mm_atomic.LoadUint64(&m.afterGetByUUIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByUUIDMock.defaultExpectation != nil && afterGetByUUIDCounter < 1 {
		if m.GetByUUIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UnitRepositoryMock.GetByUUID at\n%s", m.GetByUUIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UnitRepositoryMock.GetByUUID at\n%s with params: %#v", m.GetByUUIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByUUIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByUUID != nil && afterGetByUUIDCounter < 1 {
		m.t.Errorf("Expected call to UnitRepositoryMock.GetByUUID at\n%s", m.funcGetByUUIDOrigin)
	}

	if !m.GetByUUIDMock.invocationsDone() && afterGetByUUIDCounter > 0 {
		m.t.Errorf("Expected %d calls to UnitRepositoryMock.GetByUUID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByUUIDMock.expectedInvocations), m.GetByUUIDMock.expectedInvocationsOrigin, afterGetByUUIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UnitRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddInspect()

			m.MinimockGetByUUIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UnitRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UnitRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddDone() &&
		m.MinimockGetByUUIDDone()
}
