// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: order_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Cvc           string                 `protobuf:"bytes,4,opt,name=cvc,proto3" json:"cvc,omitempty"`
	PaymentSystem string                 `protobuf:"bytes,5,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty"`
	IsPreferred   bool                   `protobuf:"varint,6,opt,name=is_preferred,json=isPreferred,proto3" json:"is_preferred,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCardReq) Reset() {
	*x = SaveCardReq{}
	mi := &file_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCardReq) ProtoMessage() {}

func (x *SaveCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCardReq.ProtoReflect.Descriptor instead.
func (*SaveCardReq) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *SaveCardReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *SaveCardReq) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *SaveCardReq) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *SaveCardReq) GetCvc() string {
	if x != nil {
		return x.Cvc
	}
	return ""
}

func (x *SaveCardReq) GetPaymentSystem() string {
	if x != nil {
		return x.PaymentSystem
	}
	return ""
}

func (x *SaveCardReq) GetIsPreferred() bool {
	if x != nil {
		return x.IsPreferred
	}
	return false
}

func (x *SaveCardReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SaveCardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCardResp) Reset() {
	*x = SaveCardResp{}
	mi := &file_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCardResp) ProtoMessage() {}

func (x *SaveCardResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCardResp.ProtoReflect.Descriptor instead.
func (*SaveCardResp) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveCardResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPreferredCardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferredCardReq) Reset() {
	*x = GetPreferredCardReq{}
	mi := &file_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferredCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferredCardReq) ProtoMessage() {}

func (x *GetPreferredCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferredCardReq.ProtoReflect.Descriptor instead.
func (*GetPreferredCardReq) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPreferredCardReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetPreferredCardResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=Card,proto3" json:"Card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferredCardResp) Reset() {
	*x = GetPreferredCardResp{}
	mi := &file_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferredCardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferredCardResp) ProtoMessage() {}

func (x *GetPreferredCardResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferredCardResp.ProtoReflect.Descriptor instead.
func (*GetPreferredCardResp) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPreferredCardResp) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Last_4Digits  string                 `protobuf:"bytes,2,opt,name=last_4_digits,json=last4Digits,proto3" json:"last_4_digits,omitempty"`
	PaymentSystem string                 `protobuf:"bytes,3,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty"`
	UserUuid      string                 `protobuf:"bytes,4,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	IsPreferred   bool                   `protobuf:"varint,5,opt,name=is_preferred,json=isPreferred,proto3" json:"is_preferred,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *Card) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Card) GetLast_4Digits() string {
	if x != nil {
		return x.Last_4Digits
	}
	return ""
}

func (x *Card) GetPaymentSystem() string {
	if x != nil {
		return x.PaymentSystem
	}
	return ""
}

func (x *Card) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *Card) GetIsPreferred() bool {
	if x != nil {
		return x.IsPreferred
	}
	return false
}

func (x *Card) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Card) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SessionUuid   string                 `protobuf:"bytes,2,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        float32                `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	PlatformFee   float32                `protobuf:"fixed32,7,opt,name=platform_fee,json=platformFee,proto3" json:"platform_fee,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *Payment) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Payment) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetPlatformFee() float32 {
	if x != nil {
		return x.PlatformFee
	}
	return 0
}

func (x *Payment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid   string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	UserUuid      string                 `protobuf:"bytes,5,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	CardUuid      string                 `protobuf:"bytes,6,opt,name=card_uuid,json=cardUuid,proto3" json:"card_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePaymentReq) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *CreatePaymentReq) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePaymentReq) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreatePaymentReq) GetCardUuid() string {
	if x != nil {
		return x.CardUuid
	}
	return ""
}

type CreatePaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=Payment,proto3" json:"Payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResp) Reset() {
	*x = CreatePaymentResp{}
	mi := &file_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResp) ProtoMessage() {}

func (x *CreatePaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResp.ProtoReflect.Descriptor instead.
func (*CreatePaymentResp) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePaymentResp) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_order_service_proto protoreflect.FileDescriptor

const file_order_service_proto_rawDesc = "" +
	"\n" +
	"\x13order_service.proto\x12\x05order\"\xd1\x01\n" +
	"\vSaveCardReq\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\x12\x10\n" +
	"\x03cvc\x18\x04 \x01(\tR\x03cvc\x12%\n" +
	"\x0epayment_system\x18\x05 \x01(\tR\rpaymentSystem\x12!\n" +
	"\fis_preferred\x18\x06 \x01(\bR\visPreferred\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\"(\n" +
	"\fSaveCardResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"2\n" +
	"\x13GetPreferredCardReq\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"7\n" +
	"\x14GetPreferredCardResp\x12\x1f\n" +
	"\x04Card\x18\x01 \x01(\v2\v.order.CardR\x04Card\"\xd8\x01\n" +
	"\x04Card\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\"\n" +
	"\rlast_4_digits\x18\x02 \x01(\tR\vlast4Digits\x12%\n" +
	"\x0epayment_system\x18\x03 \x01(\tR\rpaymentSystem\x12\x1b\n" +
	"\tuser_uuid\x18\x04 \x01(\tR\buserUuid\x12!\n" +
	"\fis_preferred\x18\x05 \x01(\bR\visPreferred\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\x83\x02\n" +
	"\aPayment\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12!\n" +
	"\fsession_uuid\x18\x02 \x01(\tR\vsessionUuid\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x02R\x06amount\x12!\n" +
	"\fplatform_fee\x18\a \x01(\x02R\vplatformFee\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\xd0\x01\n" +
	"\x10CreatePaymentReq\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x02R\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tuser_uuid\x18\x05 \x01(\tR\buserUuid\x12\x1b\n" +
	"\tcard_uuid\x18\x06 \x01(\tR\bcardUuid\"=\n" +
	"\x11CreatePaymentResp\x12(\n" +
	"\aPayment\x18\x01 \x01(\v2\x0e.order.PaymentR\aPayment2\xd3\x01\n" +
	"\x05Order\x123\n" +
	"\bSaveCard\x12\x12.order.SaveCardReq\x1a\x13.order.SaveCardResp\x12Q\n" +
	"\x16GetPreferredByUserUUID\x12\x1a.order.GetPreferredCardReq\x1a\x1b.order.GetPreferredCardResp\x12B\n" +
	"\rCreatePayment\x12\x17.order.CreatePaymentReq\x1a\x18.order.CreatePaymentRespB\x15Z\x13contracts/pkg/protob\x06proto3"

var (
	file_order_service_proto_rawDescOnce sync.Once
	file_order_service_proto_rawDescData []byte
)

func file_order_service_proto_rawDescGZIP() []byte {
	file_order_service_proto_rawDescOnce.Do(func() {
		file_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)))
	})
	return file_order_service_proto_rawDescData
}

var file_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_order_service_proto_goTypes = []any{
	(*SaveCardReq)(nil),          // 0: order.SaveCardReq
	(*SaveCardResp)(nil),         // 1: order.SaveCardResp
	(*GetPreferredCardReq)(nil),  // 2: order.GetPreferredCardReq
	(*GetPreferredCardResp)(nil), // 3: order.GetPreferredCardResp
	(*Card)(nil),                 // 4: order.Card
	(*Payment)(nil),              // 5: order.Payment
	(*CreatePaymentReq)(nil),     // 6: order.CreatePaymentReq
	(*CreatePaymentResp)(nil),    // 7: order.CreatePaymentResp
}
var file_order_service_proto_depIdxs = []int32{
	4, // 0: order.GetPreferredCardResp.Card:type_name -> order.Card
	5, // 1: order.CreatePaymentResp.Payment:type_name -> order.Payment
	0, // 2: order.Order.SaveCard:input_type -> order.SaveCardReq
	2, // 3: order.Order.GetPreferredByUserUUID:input_type -> order.GetPreferredCardReq
	6, // 4: order.Order.CreatePayment:input_type -> order.CreatePaymentReq
	1, // 5: order.Order.SaveCard:output_type -> order.SaveCardResp
	3, // 6: order.Order.GetPreferredByUserUUID:output_type -> order.GetPreferredCardResp
	7, // 7: order.Order.CreatePayment:output_type -> order.CreatePaymentResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_service_proto_init() }
func file_order_service_proto_init() {
	if File_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_proto_goTypes,
		DependencyIndexes: file_order_service_proto_depIdxs,
		MessageInfos:      file_order_service_proto_msgTypes,
	}.Build()
	File_order_service_proto = out.File
	file_order_service_proto_goTypes = nil
	file_order_service_proto_depIdxs = nil
}
