// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package k071123

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Car struct {
	Uuid         pgtype.UUID
	UserUuid     pgtype.UUID
	GosNumber    string
	IsActive     bool
	SettingsUuid pgtype.UUID
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type CarSetting struct {
	Uuid pgtype.UUID
	Vin  string
}
