// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package k071123

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getParkingByUUID = `-- name: GetParkingByUUID :one
select uuid, user_uuid, gos_number, is_active, settings_uuid, created_at, updated_at, deleted_at from cars where uuid = $1 LIMIT 1
`

func (q *Queries) GetParkingByUUID(ctx context.Context, uuid pgtype.UUID) (Car, error) {
	row := q.db.QueryRow(ctx, getParkingByUUID, uuid)
	var i Car
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.GosNumber,
		&i.IsActive,
		&i.SettingsUuid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
